gMonPortraitsGroup0_Gfx:: @ 0x0

	.incbin "graphics/mon_portraits/252_treecko_portrait.4bpp"

	.incbin "graphics/mon_portraits/253_grovyle_portrait.4bpp"

	.incbin "graphics/mon_portraits/254_sceptile_portrait.4bpp"

	.incbin "graphics/mon_portraits/255_torchic_portrait.4bpp"

	.incbin "graphics/mon_portraits/256_combusken_portrait.4bpp"

	.incbin "graphics/mon_portraits/257_blaziken_portrait.4bpp"

	.incbin "graphics/mon_portraits/258_mudkip_portrait.4bpp"

	.incbin "graphics/mon_portraits/259_marshtomp_portrait.4bpp"

	.incbin "graphics/mon_portraits/260_swampert_portrait.4bpp"

	.incbin "graphics/mon_portraits/261_poochyena_portrait.4bpp"

	.incbin "graphics/mon_portraits/262_mightyena_portrait.4bpp"

	.incbin "graphics/mon_portraits/263_zigzagoon_portrait.4bpp"

	.incbin "graphics/mon_portraits/264_linoone_portrait.4bpp"

	.incbin "graphics/mon_portraits/265_wurmple_portrait.4bpp"

	.incbin "graphics/mon_portraits/266_silcoon_portrait.4bpp"



gMonPortraitsGroup1_Gfx:: @ 0x0

	.incbin "graphics/mon_portraits/267_beautifly_portrait.4bpp"

	.incbin "graphics/mon_portraits/268_cascoon_portrait.4bpp"

	.incbin "graphics/mon_portraits/269_dustox_portrait.4bpp"

	.incbin "graphics/mon_portraits/270_lotad_portrait.4bpp"

	.incbin "graphics/mon_portraits/271_lombre_portrait.4bpp"

	.incbin "graphics/mon_portraits/272_ludicolo_portrait.4bpp"

	.incbin "graphics/mon_portraits/273_seedot_portrait.4bpp"

	.incbin "graphics/mon_portraits/274_nuzleaf_portrait.4bpp"

	.incbin "graphics/mon_portraits/275_shiftry_portrait.4bpp"

	.incbin "graphics/mon_portraits/276_taillow_portrait.4bpp"

	.incbin "graphics/mon_portraits/277_swellow_portrait.4bpp"

	.incbin "graphics/mon_portraits/278_wingull_portrait.4bpp"

	.incbin "graphics/mon_portraits/279_pelipper_portrait.4bpp"

	.incbin "graphics/mon_portraits/280_ralts_portrait.4bpp"

	.incbin "graphics/mon_portraits/281_kirlia_portrait.4bpp"



gMonPortraitsGroup2_Gfx:: @ 0x0

	.incbin "graphics/mon_portraits/282_gardevoir_portrait.4bpp"

	.incbin "graphics/mon_portraits/283_surskit_portrait.4bpp"

	.incbin "graphics/mon_portraits/284_masquerain_portrait.4bpp"

	.incbin "graphics/mon_portraits/285_shroomish_portrait.4bpp"

	.incbin "graphics/mon_portraits/286_breloom_portrait.4bpp"

	.incbin "graphics/mon_portraits/287_slakoth_portrait.4bpp"

	.incbin "graphics/mon_portraits/288_vigoroth_portrait.4bpp"

	.incbin "graphics/mon_portraits/289_slaking_portrait.4bpp"

	.incbin "graphics/mon_portraits/63_abra_portrait.4bpp"

	.incbin "graphics/mon_portraits/64_kadabra_portrait.4bpp"

	.incbin "graphics/mon_portraits/65_alakazam_portrait.4bpp"

	.incbin "graphics/mon_portraits/290_nincada_portrait.4bpp"

	.incbin "graphics/mon_portraits/291_ninjask_portrait.4bpp"

	.incbin "graphics/mon_portraits/292_shedinja_portrait.4bpp"

	.incbin "graphics/mon_portraits/293_whismur_portrait.4bpp"



gMonPortraitsGroup3_Gfx:: @ 0x0

	.incbin "graphics/mon_portraits/294_loudred_portrait.4bpp"

	.incbin "graphics/mon_portraits/295_exploud_portrait.4bpp"

	.incbin "graphics/mon_portraits/296_makuhita_portrait.4bpp"

	.incbin "graphics/mon_portraits/297_hariyama_portrait.4bpp"

	.incbin "graphics/mon_portraits/118_goldeen_portrait.4bpp"

	.incbin "graphics/mon_portraits/119_seaking_portrait.4bpp"

	.incbin "graphics/mon_portraits/129_magikarp_portrait.4bpp"

	.incbin "graphics/mon_portraits/130_gyarados_portrait.4bpp"

	.incbin "graphics/mon_portraits/298_azurill_portrait.4bpp"

	.incbin "graphics/mon_portraits/183_marill_portrait.4bpp"

	.incbin "graphics/mon_portraits/184_azumarill_portrait.4bpp"

	.incbin "graphics/mon_portraits/74_geodude_portrait.4bpp"

	.incbin "graphics/mon_portraits/75_graveler_portrait.4bpp"

	.incbin "graphics/mon_portraits/76_golem_portrait.4bpp"

	.incbin "graphics/mon_portraits/299_nosepass_portrait.4bpp"



gMonPortraitsGroup4_Gfx:: @ 0x0

	.incbin "graphics/mon_portraits/300_skitty_portrait.4bpp"

	.incbin "graphics/mon_portraits/301_delcatty_portrait.4bpp"

	.incbin "graphics/mon_portraits/41_zubat_portrait.4bpp"

	.incbin "graphics/mon_portraits/42_golbat_portrait.4bpp"

	.incbin "graphics/mon_portraits/169_crobat_portrait.4bpp"

	.incbin "graphics/mon_portraits/72_tentacool_portrait.4bpp"

	.incbin "graphics/mon_portraits/73_tentacruel_portrait.4bpp"

	.incbin "graphics/mon_portraits/302_sableye_portrait.4bpp"

	.incbin "graphics/mon_portraits/303_mawile_portrait.4bpp"

	.incbin "graphics/mon_portraits/304_aron_portrait.4bpp"

	.incbin "graphics/mon_portraits/305_lairon_portrait.4bpp"

	.incbin "graphics/mon_portraits/306_aggron_portrait.4bpp"

	.incbin "graphics/mon_portraits/66_machop_portrait.4bpp"

	.incbin "graphics/mon_portraits/67_machoke_portrait.4bpp"

	.incbin "graphics/mon_portraits/68_machamp_portrait.4bpp"



gMonPortraitsGroup5_Gfx:: @ 0x0

	.incbin "graphics/mon_portraits/307_meditite_portrait.4bpp"

	.incbin "graphics/mon_portraits/308_medicham_portrait.4bpp"

	.incbin "graphics/mon_portraits/309_electrike_portrait.4bpp"

	.incbin "graphics/mon_portraits/310_manectric_portrait.4bpp"

	.incbin "graphics/mon_portraits/311_plusle_portrait.4bpp"

	.incbin "graphics/mon_portraits/312_minun_portrait.4bpp"

	.incbin "graphics/mon_portraits/81_magnemite_portrait.4bpp"

	.incbin "graphics/mon_portraits/82_magneton_portrait.4bpp"

	.incbin "graphics/mon_portraits/100_voltorb_portrait.4bpp"

	.incbin "graphics/mon_portraits/101_electrode_portrait.4bpp"

	.incbin "graphics/mon_portraits/313_volbeat_portrait.4bpp"

	.incbin "graphics/mon_portraits/314_illumise_portrait.4bpp"

	.incbin "graphics/mon_portraits/43_oddish_portrait.4bpp"

	.incbin "graphics/mon_portraits/44_gloom_portrait.4bpp"

	.incbin "graphics/mon_portraits/45_vileplume_portrait.4bpp"



gMonPortraitsGroup6_Gfx:: @ 0x0

	.incbin "graphics/mon_portraits/182_bellossom_portrait.4bpp"

	.incbin "graphics/mon_portraits/84_doduo_portrait.4bpp"

	.incbin "graphics/mon_portraits/85_dodrio_portrait.4bpp"

	.incbin "graphics/mon_portraits/315_roselia_portrait.4bpp"

	.incbin "graphics/mon_portraits/316_gulpin_portrait.4bpp"

	.incbin "graphics/mon_portraits/317_swalot_portrait.4bpp"

	.incbin "graphics/mon_portraits/318_carvanha_portrait.4bpp"

	.incbin "graphics/mon_portraits/319_sharpedo_portrait.4bpp"

	.incbin "graphics/mon_portraits/320_wailmer_portrait.4bpp"

	.incbin "graphics/mon_portraits/321_wailord_portrait.4bpp"

	.incbin "graphics/mon_portraits/322_numel_portrait.4bpp"

	.incbin "graphics/mon_portraits/323_camerupt_portrait.4bpp"

	.incbin "graphics/mon_portraits/218_slugma_portrait.4bpp"

	.incbin "graphics/mon_portraits/219_magcargo_portrait.4bpp"

	.incbin "graphics/mon_portraits/324_torkoal_portrait.4bpp"



gMonPortraitsGroup7_Gfx:: @ 0x0

	.incbin "graphics/mon_portraits/88_grimer_portrait.4bpp"

	.incbin "graphics/mon_portraits/89_muk_portrait.4bpp"

	.incbin "graphics/mon_portraits/109_koffing_portrait.4bpp"

	.incbin "graphics/mon_portraits/110_weezing_portrait.4bpp"

	.incbin "graphics/mon_portraits/325_spoink_portrait.4bpp"

	.incbin "graphics/mon_portraits/326_grumpig_portrait.4bpp"

	.incbin "graphics/mon_portraits/27_sandshrew_portrait.4bpp"

	.incbin "graphics/mon_portraits/28_sandslash_portrait.4bpp"

	.incbin "graphics/mon_portraits/327_spinda_portrait.4bpp"

	.incbin "graphics/mon_portraits/227_skarmory_portrait.4bpp"

	.incbin "graphics/mon_portraits/328_trapinch_portrait.4bpp"

	.incbin "graphics/mon_portraits/329_vibrava_portrait.4bpp"

	.incbin "graphics/mon_portraits/330_flygon_portrait.4bpp"

	.incbin "graphics/mon_portraits/331_cacnea_portrait.4bpp"

	.incbin "graphics/mon_portraits/332_cacturne_portrait.4bpp"



gMonPortraitsGroup8_Gfx:: @ 0x0

	.incbin "graphics/mon_portraits/333_swablu_portrait.4bpp"

	.incbin "graphics/mon_portraits/334_altaria_portrait.4bpp"

	.incbin "graphics/mon_portraits/335_zangoose_portrait.4bpp"

	.incbin "graphics/mon_portraits/336_seviper_portrait.4bpp"

	.incbin "graphics/mon_portraits/337_lunatone_portrait.4bpp"

	.incbin "graphics/mon_portraits/338_solrock_portrait.4bpp"

	.incbin "graphics/mon_portraits/339_barboach_portrait.4bpp"

	.incbin "graphics/mon_portraits/340_whiscash_portrait.4bpp"

	.incbin "graphics/mon_portraits/341_corphish_portrait.4bpp"

	.incbin "graphics/mon_portraits/342_crawdaunt_portrait.4bpp"

	.incbin "graphics/mon_portraits/343_baltoy_portrait.4bpp"

	.incbin "graphics/mon_portraits/344_claydol_portrait.4bpp"

	.incbin "graphics/mon_portraits/345_lileep_portrait.4bpp"

	.incbin "graphics/mon_portraits/346_cradily_portrait.4bpp"

	.incbin "graphics/mon_portraits/347_anorith_portrait.4bpp"



gMonPortraitsGroup9_Gfx:: @ 0x0

	.incbin "graphics/mon_portraits/348_armaldo_portrait.4bpp"

	.incbin "graphics/mon_portraits/174_igglybuff_portrait.4bpp"

	.incbin "graphics/mon_portraits/39_jigglypuff_portrait.4bpp"

	.incbin "graphics/mon_portraits/40_wigglytuff_portrait.4bpp"

	.incbin "graphics/mon_portraits/349_feebas_portrait.4bpp"

	.incbin "graphics/mon_portraits/350_milotic_portrait.4bpp"

	.incbin "graphics/mon_portraits/351_castform_portrait.4bpp"

	.incbin "graphics/mon_portraits/120_staryu_portrait.4bpp"

	.incbin "graphics/mon_portraits/121_starmie_portrait.4bpp"

	.incbin "graphics/mon_portraits/352_kecleon_portrait.4bpp"

	.incbin "graphics/mon_portraits/353_shuppet_portrait.4bpp"

	.incbin "graphics/mon_portraits/354_banette_portrait.4bpp"

	.incbin "graphics/mon_portraits/355_duskull_portrait.4bpp"

	.incbin "graphics/mon_portraits/356_dusclops_portrait.4bpp"

	.incbin "graphics/mon_portraits/357_tropius_portrait.4bpp"



gMonPortraitsGroup10_Gfx:: @ 0x0

	.incbin "graphics/mon_portraits/358_chimecho_portrait.4bpp"

	.incbin "graphics/mon_portraits/359_absol_portrait.4bpp"

	.incbin "graphics/mon_portraits/37_vulpix_portrait.4bpp"

	.incbin "graphics/mon_portraits/38_ninetales_portrait.4bpp"

	.incbin "graphics/mon_portraits/172_pichu_portrait.4bpp"

	.incbin "graphics/mon_portraits/25_pikachu_portrait.4bpp"

	.incbin "graphics/mon_portraits/26_raichu_portrait.4bpp"

	.incbin "graphics/mon_portraits/54_psyduck_portrait.4bpp"

	.incbin "graphics/mon_portraits/55_golduck_portrait.4bpp"

	.incbin "graphics/mon_portraits/360_wynaut_portrait.4bpp"

	.incbin "graphics/mon_portraits/202_wobbuffet_portrait.4bpp"

	.incbin "graphics/mon_portraits/177_natu_portrait.4bpp"

	.incbin "graphics/mon_portraits/178_xatu_portrait.4bpp"

	.incbin "graphics/mon_portraits/203_girafarig_portrait.4bpp"

	.incbin "graphics/mon_portraits/231_phanpy_portrait.4bpp"



gMonPortraitsGroup11_Gfx:: @ 0x0

	.incbin "graphics/mon_portraits/232_donphan_portrait.4bpp"

	.incbin "graphics/mon_portraits/127_pinsir_portrait.4bpp"

	.incbin "graphics/mon_portraits/214_heracross_portrait.4bpp"

	.incbin "graphics/mon_portraits/111_rhyhorn_portrait.4bpp"

	.incbin "graphics/mon_portraits/112_rhydon_portrait.4bpp"

	.incbin "graphics/mon_portraits/361_snorunt_portrait.4bpp"

	.incbin "graphics/mon_portraits/362_glalie_portrait.4bpp"

	.incbin "graphics/mon_portraits/363_spheal_portrait.4bpp"

	.incbin "graphics/mon_portraits/364_sealeo_portrait.4bpp"

	.incbin "graphics/mon_portraits/365_walrein_portrait.4bpp"

	.incbin "graphics/mon_portraits/366_clamperl_portrait.4bpp"

	.incbin "graphics/mon_portraits/367_huntail_portrait.4bpp"

	.incbin "graphics/mon_portraits/368_gorebyss_portrait.4bpp"

	.incbin "graphics/mon_portraits/369_relicanth_portrait.4bpp"

	.incbin "graphics/mon_portraits/222_corsola_portrait.4bpp"



gMonPortraitsGroup12_Gfx:: @ 0x0

	.incbin "graphics/mon_portraits/170_chinchou_portrait.4bpp"

	.incbin "graphics/mon_portraits/171_lanturn_portrait.4bpp"

	.incbin "graphics/mon_portraits/370_luvdisc_portrait.4bpp"

	.incbin "graphics/mon_portraits/116_horsea_portrait.4bpp"

	.incbin "graphics/mon_portraits/117_seadra_portrait.4bpp"

	.incbin "graphics/mon_portraits/230_kingdra_portrait.4bpp"

	.incbin "graphics/mon_portraits/371_bagon_portrait.4bpp"

	.incbin "graphics/mon_portraits/372_shelgon_portrait.4bpp"

	.incbin "graphics/mon_portraits/373_salamence_portrait.4bpp"

	.incbin "graphics/mon_portraits/374_beldum_portrait.4bpp"

	.incbin "graphics/mon_portraits/375_metang_portrait.4bpp"

	.incbin "graphics/mon_portraits/376_metagross_portrait.4bpp"

	.incbin "graphics/mon_portraits/377_regirock_portrait.4bpp"

	.incbin "graphics/mon_portraits/378_regice_portrait.4bpp"

	.incbin "graphics/mon_portraits/379_registeel_portrait.4bpp"



gMonPortraitsGroup13_Gfx:: @ 0x0

	.incbin "graphics/mon_portraits/380_latias_portrait.4bpp"

	.incbin "graphics/mon_portraits/381_latios_portrait.4bpp"

	.incbin "graphics/mon_portraits/382_kyogre_portrait.4bpp"

	.incbin "graphics/mon_portraits/383_groudon_portrait.4bpp"

	.incbin "graphics/mon_portraits/384_rayquaza_portrait.4bpp"

	.incbin "graphics/mon_portraits/385_jirachi_portrait.4bpp"

	.incbin "graphics/mon_portraits/152_chikorita_portrait.4bpp"

	.incbin "graphics/mon_portraits/155_cyndaquil_portrait.4bpp"

	.incbin "graphics/mon_portraits/158_totodile_portrait.4bpp"

	.incbin "graphics/mon_portraits/142_aerodactyl_portrait.4bpp"

	.incbin "graphics/mon_portraits/522_blitzle_portrait.4bpp"

	.incbin "graphics/mon_portraits/523_zebstrika_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"



gMonPortraitsGroup14_Gfx:: @ 0x0

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"



gMonPortraitsGroup15_Gfx:: @ 0x0

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"



gMonPortraitsGroup16_Gfx:: @ 0x0

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"



gMonPortraitsGroup17_Gfx:: @ 0x0

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"



gMonPortraitsGroup18_Gfx:: @ 0x0

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"



gMonPortraitsGroup19_Gfx:: @ 0x0

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"



gMonPortraitsGroup20_Gfx:: @ 0x0

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"



gMonPortraitsGroup21_Gfx:: @ 0x0

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"



gMonPortraitsGroup22_Gfx:: @ 0x0

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"



gMonPortraitsGroup23_Gfx:: @ 0x0

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"



gMonPortraitsGroup24_Gfx:: @ 0x0

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"



gMonPortraitsGroup25_Gfx:: @ 0x0

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"
