gMonCatchSpriteGroup0_Pal:: @ 0x081AEBE4
	.incbin "graphics/mon_catch_sprites/catch_mon_252_treecko.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_255_torchic.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_258_mudkip.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_261_poochyena.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_263_zigzagoon.gbapal"

    .incbin "baserom.gba", 0x1AEC84, 0x160

gMonCatchSpriteGroup1_Pal::
	.incbin "graphics/mon_catch_sprites/catch_mon_266_silcoon.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_268_cascoon.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_271_lombre.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_274_nuzleaf.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_276_taillow.gbapal"

    .incbin "baserom.gba", 0x1AEE84, 0x160

gMonCatchSpriteGroup2_Pal::
	.incbin "graphics/mon_catch_sprites/catch_mon_278_wingull.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_287_slakoth.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_63_abra.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_290_nincada.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_294_loudred.gbapal"

    .incbin "baserom.gba", 0x1AF084, 0x160

gMonCatchSpriteGroup3_Pal::
	.incbin "graphics/mon_catch_sprites/catch_mon_296_makuhita.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_118_goldeen.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_129_magikarp.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_183_marill.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_74_geodude.gbapal"

    .incbin "baserom.gba", 0x1AF284, 0x160

gMonCatchSpriteGroup4_Pal::
	.incbin "graphics/mon_catch_sprites/catch_mon_299_nosepass.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_72_tentacool.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_302_sableye.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_303_mawile.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_66_machop.gbapal"

    .incbin "baserom.gba", 0x1AF484, 0x160

gMonCatchSpriteGroup5_Pal::
	.incbin "graphics/mon_catch_sprites/catch_mon_307_meditite.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_309_electrike.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_81_magnemite.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_100_voltorb.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_313_volbeat.gbapal"

    .incbin "baserom.gba", 0x1AF684, 0x160

gMonCatchSpriteGroup6_Pal::
	.incbin "graphics/mon_catch_sprites/catch_mon_314_illumise.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_84_doduo.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_315_roselia.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_318_carvanha.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_320_wailmer.gbapal"

    .incbin "baserom.gba", 0x1AF884, 0x160

gMonCatchSpriteGroup7_Pal::
	.incbin "graphics/mon_catch_sprites/catch_mon_322_numel.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_218_slugma.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_324_torkoal.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_88_grimer.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_109_koffing.gbapal"

    .incbin "baserom.gba", 0x1AFA84, 0x160

gMonCatchSpriteGroup8_Pal::
	.incbin "graphics/mon_catch_sprites/catch_mon_227_skarmory.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_329_vibrava.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_331_cacnea.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_333_swablu.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_335_zangoose.gbapal"

    .incbin "baserom.gba", 0x1AFC84, 0x160

gMonCatchSpriteGroup9_Pal::
	.incbin "graphics/mon_catch_sprites/catch_mon_336_seviper.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_337_lunatone.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_338_solrock.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_339_barboach.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_341_corphish.gbapal"

    .incbin "baserom.gba", 0x1AFE84, 0x160

gMonCatchSpriteGroup10_Pal::
	.incbin "graphics/mon_catch_sprites/catch_mon_343_baltoy.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_345_lileep.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_347_anorith.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_39_jigglypuff.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_349_feebas.gbapal"

    .incbin "baserom.gba", 0x1B0084, 0x160

gMonCatchSpriteGroup11_Pal::
	.incbin "graphics/mon_catch_sprites/catch_mon_351_castform.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_120_staryu.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_352_kecleon.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_355_duskull.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_357_tropius.gbapal"

    .incbin "baserom.gba", 0x1B0284, 0x160

gMonCatchSpriteGroup12_Pal::
	.incbin "graphics/mon_catch_sprites/catch_mon_359_absol.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_37_vulpix.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_25_pikachu.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_54_psyduck.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_202_wobbuffet.gbapal"

    .incbin "baserom.gba", 0x1B0484, 0x160

gMonCatchSpriteGroup13_Pal::
	.incbin "graphics/mon_catch_sprites/catch_mon_203_girafarig.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_127_pinsir.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_214_heracross.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_111_rhyhorn.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_366_clamperl.gbapal"

    .incbin "baserom.gba", 0x1B0684, 0x160

gMonCatchSpriteGroup14_Pal::
	.incbin "graphics/mon_catch_sprites/catch_mon_369_relicanth.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_370_luvdisc.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_372_shelgon.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_374_beldum.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_377_regirock.gbapal"

    .incbin "baserom.gba", 0x1B0884, 0x160

gMonCatchSpriteGroup15_Pal::
	.incbin "graphics/mon_catch_sprites/catch_mon_378_regice.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_379_registeel.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_380_latias.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_381_latios.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_385_jirachi.gbapal"

    .incbin "baserom.gba", 0x1B0A84, 0x160

gMonCatchSpriteGroup16_Pal::
	.incbin "graphics/mon_catch_sprites/catch_mon_152_chikorita.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_155_cyndaquil.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_158_totodile.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_142_aerodactyl.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_522_blitzle.gbapal"
