gMonCatchSpriteGroup0_Gfx:: @ 0x08400C8C
	.incbin "graphics/mon_catch_sprites/catch_mon_252_treecko.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_255_torchic.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_258_mudkip.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_261_poochyena.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_263_zigzagoon.4bpp"

gMonCatchSpriteGroup1_Gfx::
	.incbin "graphics/mon_catch_sprites/catch_mon_266_silcoon.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_268_cascoon.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_271_lombre.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_274_nuzleaf.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_276_taillow.4bpp"

gMonCatchSpriteGroup2_Gfx::
	.incbin "graphics/mon_catch_sprites/catch_mon_278_wingull.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_287_slakoth.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_63_abra.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_290_nincada.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_294_loudred.4bpp"

gMonCatchSpriteGroup3_Gfx::
	.incbin "graphics/mon_catch_sprites/catch_mon_296_makuhita.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_118_goldeen.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_129_magikarp.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_183_marill.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_74_geodude.4bpp"

gMonCatchSpriteGroup4_Gfx::
	.incbin "graphics/mon_catch_sprites/catch_mon_299_nosepass.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_72_tentacool.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_302_sableye.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_303_mawile.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_66_machop.4bpp"

gMonCatchSpriteGroup5_Gfx::
	.incbin "graphics/mon_catch_sprites/catch_mon_307_meditite.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_309_electrike.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_81_magnemite.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_100_voltorb.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_313_volbeat.4bpp"

gMonCatchSpriteGroup6_Gfx::
	.incbin "graphics/mon_catch_sprites/catch_mon_314_illumise.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_84_doduo.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_315_roselia.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_318_carvanha.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_320_wailmer.4bpp"

gMonCatchSpriteGroup7_Gfx::
	.incbin "graphics/mon_catch_sprites/catch_mon_322_numel.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_218_slugma.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_324_torkoal.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_88_grimer.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_109_koffing.4bpp"

gMonCatchSpriteGroup8_Gfx::
	.incbin "graphics/mon_catch_sprites/catch_mon_227_skarmory.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_329_vibrava.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_331_cacnea.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_333_swablu.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_335_zangoose.4bpp"

gMonCatchSpriteGroup9_Gfx::
	.incbin "graphics/mon_catch_sprites/catch_mon_336_seviper.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_337_lunatone.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_338_solrock.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_339_barboach.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_341_corphish.4bpp"

gMonCatchSpriteGroup10_Gfx::
	.incbin "graphics/mon_catch_sprites/catch_mon_343_baltoy.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_345_lileep.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_347_anorith.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_39_jigglypuff.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_349_feebas.4bpp"

gMonCatchSpriteGroup11_Gfx::
	.incbin "graphics/mon_catch_sprites/catch_mon_351_castform.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_120_staryu.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_352_kecleon.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_355_duskull.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_357_tropius.4bpp"

gMonCatchSpriteGroup12_Gfx::
	.incbin "graphics/mon_catch_sprites/catch_mon_359_absol.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_37_vulpix.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_25_pikachu.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_54_psyduck.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_202_wobbuffet.4bpp"

gMonCatchSpriteGroup13_Gfx::
	.incbin "graphics/mon_catch_sprites/catch_mon_203_girafarig.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_127_pinsir.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_214_heracross.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_111_rhyhorn.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_366_clamperl.4bpp"

gMonCatchSpriteGroup14_Gfx::
	.incbin "graphics/mon_catch_sprites/catch_mon_369_relicanth.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_370_luvdisc.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_372_shelgon.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_374_beldum.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_377_regirock.4bpp"

gMonCatchSpriteGroup15_Gfx::
	.incbin "graphics/mon_catch_sprites/catch_mon_378_regice.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_379_registeel.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_380_latias.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_381_latios.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_385_jirachi.4bpp"

gMonCatchSpriteGroup16_Gfx::
	.incbin "graphics/mon_catch_sprites/catch_mon_152_chikorita.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_155_cyndaquil.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_158_totodile.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_142_aerodactyl.4bpp"
	.incbin "graphics/mon_catch_sprites/catch_mon_522_blitzle.4bpp"
