gMonPortraitsGroup0_Pals:: @ 0x0

	.incbin "graphics/mon_portraits/252_treecko_portrait.gbapal"

	.incbin "graphics/mon_portraits/253_grovyle_portrait.gbapal"

	.incbin "graphics/mon_portraits/254_sceptile_portrait.gbapal"

	.incbin "graphics/mon_portraits/255_torchic_portrait.gbapal"

	.incbin "graphics/mon_portraits/256_combusken_portrait.gbapal"

	.incbin "graphics/mon_portraits/257_blaziken_portrait.gbapal"

	.incbin "graphics/mon_portraits/258_mudkip_portrait.gbapal"

	.incbin "graphics/mon_portraits/259_marshtomp_portrait.gbapal"

	.incbin "graphics/mon_portraits/260_swampert_portrait.gbapal"

	.incbin "graphics/mon_portraits/261_poochyena_portrait.gbapal"

	.incbin "graphics/mon_portraits/262_mightyena_portrait.gbapal"

	.incbin "graphics/mon_portraits/263_zigzagoon_portrait.gbapal"

	.incbin "graphics/mon_portraits/264_linoone_portrait.gbapal"

	.incbin "graphics/mon_portraits/265_wurmple_portrait.gbapal"

	.incbin "graphics/mon_portraits/266_silcoon_portrait.gbapal"

	.incbin "graphics/mon_portraits/silhouette.gbapal"



gMonPortraitsGroup1_Pals:: @ 0x0

	.incbin "graphics/mon_portraits/267_beautifly_portrait.gbapal"

	.incbin "graphics/mon_portraits/268_cascoon_portrait.gbapal"

	.incbin "graphics/mon_portraits/269_dustox_portrait.gbapal"

	.incbin "graphics/mon_portraits/270_lotad_portrait.gbapal"

	.incbin "graphics/mon_portraits/271_lombre_portrait.gbapal"

	.incbin "graphics/mon_portraits/272_ludicolo_portrait.gbapal"

	.incbin "graphics/mon_portraits/273_seedot_portrait.gbapal"

	.incbin "graphics/mon_portraits/274_nuzleaf_portrait.gbapal"

	.incbin "graphics/mon_portraits/275_shiftry_portrait.gbapal"

	.incbin "graphics/mon_portraits/276_taillow_portrait.gbapal"

	.incbin "graphics/mon_portraits/277_swellow_portrait.gbapal"

	.incbin "graphics/mon_portraits/278_wingull_portrait.gbapal"

	.incbin "graphics/mon_portraits/279_pelipper_portrait.gbapal"

	.incbin "graphics/mon_portraits/280_ralts_portrait.gbapal"

	.incbin "graphics/mon_portraits/281_kirlia_portrait.gbapal"

	.incbin "graphics/mon_portraits/silhouette.gbapal"



gMonPortraitsGroup2_Pals:: @ 0x0

	.incbin "graphics/mon_portraits/282_gardevoir_portrait.gbapal"

	.incbin "graphics/mon_portraits/283_surskit_portrait.gbapal"

	.incbin "graphics/mon_portraits/284_masquerain_portrait.gbapal"

	.incbin "graphics/mon_portraits/285_shroomish_portrait.gbapal"

	.incbin "graphics/mon_portraits/286_breloom_portrait.gbapal"

	.incbin "graphics/mon_portraits/287_slakoth_portrait.gbapal"

	.incbin "graphics/mon_portraits/288_vigoroth_portrait.gbapal"

	.incbin "graphics/mon_portraits/289_slaking_portrait.gbapal"

	.incbin "graphics/mon_portraits/63_abra_portrait.gbapal"

	.incbin "graphics/mon_portraits/64_kadabra_portrait.gbapal"

	.incbin "graphics/mon_portraits/65_alakazam_portrait.gbapal"

	.incbin "graphics/mon_portraits/290_nincada_portrait.gbapal"

	.incbin "graphics/mon_portraits/291_ninjask_portrait.gbapal"

	.incbin "graphics/mon_portraits/292_shedinja_portrait.gbapal"

	.incbin "graphics/mon_portraits/293_whismur_portrait.gbapal"

	.incbin "graphics/mon_portraits/silhouette.gbapal"



gMonPortraitsGroup3_Pals:: @ 0x0

	.incbin "graphics/mon_portraits/294_loudred_portrait.gbapal"

	.incbin "graphics/mon_portraits/295_exploud_portrait.gbapal"

	.incbin "graphics/mon_portraits/296_makuhita_portrait.gbapal"

	.incbin "graphics/mon_portraits/297_hariyama_portrait.gbapal"

	.incbin "graphics/mon_portraits/118_goldeen_portrait.gbapal"

	.incbin "graphics/mon_portraits/119_seaking_portrait.gbapal"

	.incbin "graphics/mon_portraits/129_magikarp_portrait.gbapal"

	.incbin "graphics/mon_portraits/130_gyarados_portrait.gbapal"

	.incbin "graphics/mon_portraits/298_azurill_portrait.gbapal"

	.incbin "graphics/mon_portraits/183_marill_portrait.gbapal"

	.incbin "graphics/mon_portraits/184_azumarill_portrait.gbapal"

	.incbin "graphics/mon_portraits/74_geodude_portrait.gbapal"

	.incbin "graphics/mon_portraits/75_graveler_portrait.gbapal"

	.incbin "graphics/mon_portraits/76_golem_portrait.gbapal"

	.incbin "graphics/mon_portraits/299_nosepass_portrait.gbapal"

	.incbin "graphics/mon_portraits/silhouette.gbapal"



gMonPortraitsGroup4_Pals:: @ 0x0

	.incbin "graphics/mon_portraits/300_skitty_portrait.gbapal"

	.incbin "graphics/mon_portraits/301_delcatty_portrait.gbapal"

	.incbin "graphics/mon_portraits/41_zubat_portrait.gbapal"

	.incbin "graphics/mon_portraits/42_golbat_portrait.gbapal"

	.incbin "graphics/mon_portraits/169_crobat_portrait.gbapal"

	.incbin "graphics/mon_portraits/72_tentacool_portrait.gbapal"

	.incbin "graphics/mon_portraits/73_tentacruel_portrait.gbapal"

	.incbin "graphics/mon_portraits/302_sableye_portrait.gbapal"

	.incbin "graphics/mon_portraits/303_mawile_portrait.gbapal"

	.incbin "graphics/mon_portraits/304_aron_portrait.gbapal"

	.incbin "graphics/mon_portraits/305_lairon_portrait.gbapal"

	.incbin "graphics/mon_portraits/306_aggron_portrait.gbapal"

	.incbin "graphics/mon_portraits/66_machop_portrait.gbapal"

	.incbin "graphics/mon_portraits/67_machoke_portrait.gbapal"

	.incbin "graphics/mon_portraits/68_machamp_portrait.gbapal"

	.incbin "graphics/mon_portraits/silhouette.gbapal"



gMonPortraitsGroup5_Pals:: @ 0x0

	.incbin "graphics/mon_portraits/307_meditite_portrait.gbapal"

	.incbin "graphics/mon_portraits/308_medicham_portrait.gbapal"

	.incbin "graphics/mon_portraits/309_electrike_portrait.gbapal"

	.incbin "graphics/mon_portraits/310_manectric_portrait.gbapal"

	.incbin "graphics/mon_portraits/311_plusle_portrait.gbapal"

	.incbin "graphics/mon_portraits/312_minun_portrait.gbapal"

	.incbin "graphics/mon_portraits/81_magnemite_portrait.gbapal"

	.incbin "graphics/mon_portraits/82_magneton_portrait.gbapal"

	.incbin "graphics/mon_portraits/100_voltorb_portrait.gbapal"

	.incbin "graphics/mon_portraits/101_electrode_portrait.gbapal"

	.incbin "graphics/mon_portraits/313_volbeat_portrait.gbapal"

	.incbin "graphics/mon_portraits/314_illumise_portrait.gbapal"

	.incbin "graphics/mon_portraits/43_oddish_portrait.gbapal"

	.incbin "graphics/mon_portraits/44_gloom_portrait.gbapal"

	.incbin "graphics/mon_portraits/45_vileplume_portrait.gbapal"

	.incbin "graphics/mon_portraits/silhouette.gbapal"



gMonPortraitsGroup6_Pals:: @ 0x0

	.incbin "graphics/mon_portraits/182_bellossom_portrait.gbapal"

	.incbin "graphics/mon_portraits/84_doduo_portrait.gbapal"

	.incbin "graphics/mon_portraits/85_dodrio_portrait.gbapal"

	.incbin "graphics/mon_portraits/315_roselia_portrait.gbapal"

	.incbin "graphics/mon_portraits/316_gulpin_portrait.gbapal"

	.incbin "graphics/mon_portraits/317_swalot_portrait.gbapal"

	.incbin "graphics/mon_portraits/318_carvanha_portrait.gbapal"

	.incbin "graphics/mon_portraits/319_sharpedo_portrait.gbapal"

	.incbin "graphics/mon_portraits/320_wailmer_portrait.gbapal"

	.incbin "graphics/mon_portraits/321_wailord_portrait.gbapal"

	.incbin "graphics/mon_portraits/322_numel_portrait.gbapal"

	.incbin "graphics/mon_portraits/323_camerupt_portrait.gbapal"

	.incbin "graphics/mon_portraits/218_slugma_portrait.gbapal"

	.incbin "graphics/mon_portraits/219_magcargo_portrait.gbapal"

	.incbin "graphics/mon_portraits/324_torkoal_portrait.gbapal"

	.incbin "graphics/mon_portraits/silhouette.gbapal"



gMonPortraitsGroup7_Pals:: @ 0x0

	.incbin "graphics/mon_portraits/88_grimer_portrait.gbapal"

	.incbin "graphics/mon_portraits/89_muk_portrait.gbapal"

	.incbin "graphics/mon_portraits/109_koffing_portrait.gbapal"

	.incbin "graphics/mon_portraits/110_weezing_portrait.gbapal"

	.incbin "graphics/mon_portraits/325_spoink_portrait.gbapal"

	.incbin "graphics/mon_portraits/326_grumpig_portrait.gbapal"

	.incbin "graphics/mon_portraits/27_sandshrew_portrait.gbapal"

	.incbin "graphics/mon_portraits/28_sandslash_portrait.gbapal"

	.incbin "graphics/mon_portraits/327_spinda_portrait.gbapal"

	.incbin "graphics/mon_portraits/227_skarmory_portrait.gbapal"

	.incbin "graphics/mon_portraits/328_trapinch_portrait.gbapal"

	.incbin "graphics/mon_portraits/329_vibrava_portrait.gbapal"

	.incbin "graphics/mon_portraits/330_flygon_portrait.gbapal"

	.incbin "graphics/mon_portraits/331_cacnea_portrait.gbapal"

	.incbin "graphics/mon_portraits/332_cacturne_portrait.gbapal"

	.incbin "graphics/mon_portraits/silhouette.gbapal"



gMonPortraitsGroup8_Pals:: @ 0x0

	.incbin "graphics/mon_portraits/333_swablu_portrait.gbapal"

	.incbin "graphics/mon_portraits/334_altaria_portrait.gbapal"

	.incbin "graphics/mon_portraits/335_zangoose_portrait.gbapal"

	.incbin "graphics/mon_portraits/336_seviper_portrait.gbapal"

	.incbin "graphics/mon_portraits/337_lunatone_portrait.gbapal"

	.incbin "graphics/mon_portraits/338_solrock_portrait.gbapal"

	.incbin "graphics/mon_portraits/339_barboach_portrait.gbapal"

	.incbin "graphics/mon_portraits/340_whiscash_portrait.gbapal"

	.incbin "graphics/mon_portraits/341_corphish_portrait.gbapal"

	.incbin "graphics/mon_portraits/342_crawdaunt_portrait.gbapal"

	.incbin "graphics/mon_portraits/343_baltoy_portrait.gbapal"

	.incbin "graphics/mon_portraits/344_claydol_portrait.gbapal"

	.incbin "graphics/mon_portraits/345_lileep_portrait.gbapal"

	.incbin "graphics/mon_portraits/346_cradily_portrait.gbapal"

	.incbin "graphics/mon_portraits/347_anorith_portrait.gbapal"

	.incbin "graphics/mon_portraits/silhouette.gbapal"



gMonPortraitsGroup9_Pals:: @ 0x0

	.incbin "graphics/mon_portraits/348_armaldo_portrait.gbapal"

	.incbin "graphics/mon_portraits/174_igglybuff_portrait.gbapal"

	.incbin "graphics/mon_portraits/39_jigglypuff_portrait.gbapal"

	.incbin "graphics/mon_portraits/40_wigglytuff_portrait.gbapal"

	.incbin "graphics/mon_portraits/349_feebas_portrait.gbapal"

	.incbin "graphics/mon_portraits/350_milotic_portrait.gbapal"

	.incbin "graphics/mon_portraits/351_castform_portrait.gbapal"

	.incbin "graphics/mon_portraits/120_staryu_portrait.gbapal"

	.incbin "graphics/mon_portraits/121_starmie_portrait.gbapal"

	.incbin "graphics/mon_portraits/352_kecleon_portrait.gbapal"

	.incbin "graphics/mon_portraits/353_shuppet_portrait.gbapal"

	.incbin "graphics/mon_portraits/354_banette_portrait.gbapal"

	.incbin "graphics/mon_portraits/355_duskull_portrait.gbapal"

	.incbin "graphics/mon_portraits/356_dusclops_portrait.gbapal"

	.incbin "graphics/mon_portraits/357_tropius_portrait.gbapal"

	.incbin "graphics/mon_portraits/silhouette.gbapal"



gMonPortraitsGroup10_Pals:: @ 0x0

	.incbin "graphics/mon_portraits/358_chimecho_portrait.gbapal"

	.incbin "graphics/mon_portraits/359_absol_portrait.gbapal"

	.incbin "graphics/mon_portraits/37_vulpix_portrait.gbapal"

	.incbin "graphics/mon_portraits/38_ninetales_portrait.gbapal"

	.incbin "graphics/mon_portraits/172_pichu_portrait.gbapal"

	.incbin "graphics/mon_portraits/25_pikachu_portrait.gbapal"

	.incbin "graphics/mon_portraits/26_raichu_portrait.gbapal"

	.incbin "graphics/mon_portraits/54_psyduck_portrait.gbapal"

	.incbin "graphics/mon_portraits/55_golduck_portrait.gbapal"

	.incbin "graphics/mon_portraits/360_wynaut_portrait.gbapal"

	.incbin "graphics/mon_portraits/202_wobbuffet_portrait.gbapal"

	.incbin "graphics/mon_portraits/177_natu_portrait.gbapal"

	.incbin "graphics/mon_portraits/178_xatu_portrait.gbapal"

	.incbin "graphics/mon_portraits/203_girafarig_portrait.gbapal"

	.incbin "graphics/mon_portraits/231_phanpy_portrait.gbapal"

	.incbin "graphics/mon_portraits/silhouette.gbapal"



gMonPortraitsGroup11_Pals:: @ 0x0

	.incbin "graphics/mon_portraits/232_donphan_portrait.gbapal"

	.incbin "graphics/mon_portraits/127_pinsir_portrait.gbapal"

	.incbin "graphics/mon_portraits/214_heracross_portrait.gbapal"

	.incbin "graphics/mon_portraits/111_rhyhorn_portrait.gbapal"

	.incbin "graphics/mon_portraits/112_rhydon_portrait.gbapal"

	.incbin "graphics/mon_portraits/361_snorunt_portrait.gbapal"

	.incbin "graphics/mon_portraits/362_glalie_portrait.gbapal"

	.incbin "graphics/mon_portraits/363_spheal_portrait.gbapal"

	.incbin "graphics/mon_portraits/364_sealeo_portrait.gbapal"

	.incbin "graphics/mon_portraits/365_walrein_portrait.gbapal"

	.incbin "graphics/mon_portraits/366_clamperl_portrait.gbapal"

	.incbin "graphics/mon_portraits/367_huntail_portrait.gbapal"

	.incbin "graphics/mon_portraits/368_gorebyss_portrait.gbapal"

	.incbin "graphics/mon_portraits/369_relicanth_portrait.gbapal"

	.incbin "graphics/mon_portraits/222_corsola_portrait.gbapal"

	.incbin "graphics/mon_portraits/silhouette.gbapal"



gMonPortraitsGroup12_Pals:: @ 0x0

	.incbin "graphics/mon_portraits/170_chinchou_portrait.gbapal"

	.incbin "graphics/mon_portraits/171_lanturn_portrait.gbapal"

	.incbin "graphics/mon_portraits/370_luvdisc_portrait.gbapal"

	.incbin "graphics/mon_portraits/116_horsea_portrait.gbapal"

	.incbin "graphics/mon_portraits/117_seadra_portrait.gbapal"

	.incbin "graphics/mon_portraits/230_kingdra_portrait.gbapal"

	.incbin "graphics/mon_portraits/371_bagon_portrait.gbapal"

	.incbin "graphics/mon_portraits/372_shelgon_portrait.gbapal"

	.incbin "graphics/mon_portraits/373_salamence_portrait.gbapal"

	.incbin "graphics/mon_portraits/374_beldum_portrait.gbapal"

	.incbin "graphics/mon_portraits/375_metang_portrait.gbapal"

	.incbin "graphics/mon_portraits/376_metagross_portrait.gbapal"

	.incbin "graphics/mon_portraits/377_regirock_portrait.gbapal"

	.incbin "graphics/mon_portraits/378_regice_portrait.gbapal"

	.incbin "graphics/mon_portraits/379_registeel_portrait.gbapal"

	.incbin "graphics/mon_portraits/silhouette.gbapal"



gMonPortraitsGroup13_Pals:: @ 0x0

	.incbin "graphics/mon_portraits/380_latias_portrait.gbapal"

	.incbin "graphics/mon_portraits/381_latios_portrait.gbapal"

	.incbin "graphics/mon_portraits/382_kyogre_portrait.gbapal"

	.incbin "graphics/mon_portraits/383_groudon_portrait.gbapal"

	.incbin "graphics/mon_portraits/384_rayquaza_portrait.gbapal"

	.incbin "graphics/mon_portraits/385_jirachi_portrait.gbapal"

	.incbin "graphics/mon_portraits/152_chikorita_portrait.gbapal"

	.incbin "graphics/mon_portraits/155_cyndaquil_portrait.gbapal"

	.incbin "graphics/mon_portraits/158_totodile_portrait.gbapal"

	.incbin "graphics/mon_portraits/142_aerodactyl_portrait.gbapal"

	.incbin "graphics/mon_portraits/522_blitzle_portrait.gbapal"

	.incbin "graphics/mon_portraits/523_zebstrika_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/silhouette.gbapal"



gMonPortraitsGroup14_Pals:: @ 0x0

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/silhouette.gbapal"



gMonPortraitsGroup15_Pals:: @ 0x0

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/silhouette.gbapal"



gMonPortraitsGroup16_Pals:: @ 0x0

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/silhouette.gbapal"



gMonPortraitsGroup17_Pals:: @ 0x0

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/silhouette.gbapal"



gMonPortraitsGroup18_Pals:: @ 0x0

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/silhouette.gbapal"



gMonPortraitsGroup19_Pals:: @ 0x0

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/silhouette.gbapal"



gMonPortraitsGroup20_Pals:: @ 0x0

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/silhouette.gbapal"



gMonPortraitsGroup21_Pals:: @ 0x0

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/silhouette.gbapal"



gMonPortraitsGroup22_Pals:: @ 0x0

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/silhouette.gbapal"



gMonPortraitsGroup23_Pals:: @ 0x0

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/silhouette.gbapal"



gMonPortraitsGroup24_Pals:: @ 0x0

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/silhouette.gbapal"



gMonPortraitsGroup25_Pals:: @ 0x0

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

	.incbin "graphics/mon_portraits/silhouette.gbapal"
