#ifndef GUARD_CONSTANTS_DUSCLOPS_STATES_H
#define GUARD_CONSTANTS_DUSCLOPS_STATES_H

enum DusclopsBoardStates{
    DUSCLOPS_BOARD_STATE_0_INTRO = 0,
    DUSCLOPS_BOARD_STATE_1_DUSKULL_PHASE = 1,
    DUSCLOPS_BOARD_STATE_2_INIT_DUSCLOPS_PHASE = 2,
    DUSCLOPS_BOARD_STATE_3_DUSCLOPS_PHASE = 3,
    DUSCLOPS_BOARD_STATE_4 = 4,
    DUSCLOPS_BOARD_STATE_5 = 5,
    DUSCLOPS_BOARD_STATE_6 = 6
};

enum DusclopsFramesetIx{
    DUSCLOPS_FRAMESET_MOVE_LEFT_START = 0,
    DUSCLOPS_FRAMESET_MOVE_LEFT_END = 3,
    DUSCLOPS_FRAMESET_NEUTRAL_FACING = 6,
    DUSCLOPS_FRAMESET_MOVE_RIGHT_START = 7,
    DUSCLOPS_FRAMESET_MOVE_RIGHT_END = 10,
    DUSCLOPS_FRAMESET_TURN_TO_FACE_LEFT_END = 13,
    DUSCLOPS_FRAMESET_HIT = 14,
    DUSCLOPS_FRAMESET_DYING = 15,
    DUSCLOPS_FRAMESET_ESCAPE_PREP = 18,
    DUSCLOPS_FRAMESET_ESCAPE = 25
};

enum DuskullEntityState{
    DUSKULL_ENTITY_STATE_SPAWN = 0,
    DUSKULL_ENTITY_STATE_APPEARS = 1,
    DUSKULL_ENTITY_STATE_MOVE_LEFT = 2,
    DUSKULL_ENTITY_STATE_MOVE_RIGHT = 3,
    DUSKULL_ENTITY_STATE_HIT = 4,
    DUSKULL_ENTITY_STATE_DYING = 5,
    DUSKULL_ENTITY_STATE_ESCAPE_WHILE_WALKING_LEFT = 6,
    DUSKULL_ENTITY_STATE_ESCAPE_WHILE_WALKING_RIGHT = 7,
    DUSKULL_ENTITY_STATE_ESCAPE = 8,
    DUSKULL_ENTITY_STATE_CLEANUP = 9
};

enum DusclopsEntityState{
    DUSCLOPS_ENTITY_STATE_0 = 0,
    DUSCLOPS_ENTITY_STATE_1 = 1,
    DUSCLOPS_ENTITY_STATE_2 = 2,
    DUSCLOPS_ENTITY_STATE_3 = 3,
    DUSCLOPS_ENTITY_STATE_4 = 4,
    DUSCLOPS_ENTITY_STATE_5 = 5,
    DUSCLOPS_ENTITY_STATE_6 = 6,
    DUSCLOPS_ENTITY_STATE_7 = 7,
    DUSCLOPS_ENTITY_STATE_8 = 8
};

enum DusclopsEntityColisionMode{
    DUSCLOPS_ENTITY_COLISION_MODE_NONE = 0,
    DUSCLOPS_ENTITY_COLISION_MODE_DUSKULL = 1,
    DUSCLOPS_ENTITY_COLISION_MODE_DUSCLOPS = 2
};

#endif // GUARD_CONSTANTS_DUSCLOPS_STATES_H