#ifndef GUARD_CONSTANTS_GENERATIONS_H
#define GUARD_CONSTANTS_GENERATIONS_H

#define GENERATION_1 0
#define GENERATION_2 1
#define GENERATION_3 2
#define GENERATION_4 3
#define GENERATION_5 4
#define GENERATION_6 5
#define GENERATION_7 6
#define GENERATION_8 7
#define GENERATION_9 8
#define GENERATION_EXTRA 9

#define GENERATION_COUNT 10
#define DEFAULT_GENERATION GENERATION_3

#endif // GUARD_CONSTANTS_GENERATIONS_H
