#ifndef GUARD_CONSTANTS_GROUDON_STATES_H
#define GUARD_CONSTANTS_GROUDON_STATES_H

enum GroudonBoardState{
    GROUDON_BOARD_STATE_INTRO = 0,
    GROUDON_BOARD_STATE_BATTLE_PHASE = 1,
    GROUDON_BOARD_STATE_SUCCESS_BANNER = 2,
    GROUDON_BOARD_STATE_SUCCESS_SCORING = 3,
    GROUDON_BOARD_STATE_CATCH_BANNER = 4,
    GROUDON_BOARD_STATE_CATCH_SCORING = 5,
    GROUDON_BOARD_STATE_SCORE_COUNTING_FINISHED = 6,
};

enum GroudonEntityState{
    GROUDON_ENTITY_STATE_SPAWN = 0,
    GROUDON_ENTITY_STATE_ENTRY = 1,
    GROUDON_ENTITY_STATE_IDLE = 2,
    GROUDON_ENTITY_STATE_FIREBALL = 3,
    GROUDON_ENTITY_STATE_SHOCKWAVE = 4,
    GROUDON_ENTITY_STATE_JUMP = 5,
    GROUDON_ENTITY_STATE_SUFFICIENT_HITS = 6,
    GROUDON_ENTITY_STATE_PREPARE_LEAVING = 7,
    GROUDON_ENTITY_STATE_LEAVES = 8,
    GROUDON_ENTITY_STATE_CAPTURE = 9,
    GROUDON_ENTITY_STATE_FINISHED = 10,
};

enum GroudonBoulderState{
    GROUDON_BOULDER_STATE_SPAWN = 0,
    GROUDON_BOULDER_STATE_DROP = 1,
    GROUDON_BOULDER_STATE_UNHIT = 2,
    GROUDON_BOULDER_STATE_HIT_ONCE = 3,
    GROUDON_BOULDER_STATE_HIT_TWICE = 4,
    GROUDON_BOULDER_STATE_CLEANUP = 5,
};

#endif // GUARD_CONSTANTS_GROUDON_STATES_H
