#ifndef GUARD_CONSTANTS_MAIN_BOARD_H
#define GUARD_CONSTANTS_MAIN_BOARD_H

#include "center_screen_states.h"

enum MainBoardTrapHoles{
    NOT_TRAPPED = 0,
    TRAP_CATCH_HOLE = 1,
    TRAP_EGG_HOLE = 2,
    TRAP_EVO_SHOP_HOLE = 3,
    TRAP_CENTER_HOLE = 4,
};

enum MainBoardState{
    MAIN_BOARD_STATE_AREA_ROULETTE = 0,
    MAIN_BOARD_STATE_DEFAULT = 1,
    MAIN_BOARD_STATE_BONUS_HOLE_ACTIVE = 2,
    MAIN_BOARD_STATE_BOSS_HOLE_ACTIVE = 3,
    MAIN_BOARD_STATE_CATCH_EM_MODE = 4,
    MAIN_BOARD_STATE_EGG_HATCH_MODE = 5,
    MAIN_BOARD_STATE_EVO_MODE = 6,
    MAIN_BOARD_STATE_TRAVEL_MODE = 7,
    MAIN_BOARD_STATE_JIRACHI_CATCH_MODE = 8,
};

#endif // GUARD_CONSTANTS_MAIN_BOARD_H