#ifndef GUARD_CONSTANTS_RUBY_STATES_H
#define GUARD_CONSTANTS_RUBY_STATES_H

enum RubyPondStates{
    RUBY_POND_STATE_CHINCHOU_STAGGERED = 0,
    RUBY_POND_STATE_CHINCHOU_CLOCKWISE = 1,
    RUBY_POND_STATE_CHINCHOU_COUNTERCLOCKWISE = 2,
    RUBY_POND_STATE_CHINCHOU_ROWS = 3,
    RUBY_POND_STATE_LOTAD = 4,
    RUBY_POND_STATE_CHINCHOU_SINGLE_CLOCKWISE = 5,
    RUBY_POND_STATE_WHISCASH = 6
};

enum WhiscashStates{
    WHISCASH_STATE_0 = 0,
    WHISCASH_STATE_1 = 1,
    WHISCASH_STATE_2 = 2,
    WHISCASH_STATE_3 = 3,
    WHISCASH_STATE_4 = 4,
    WHISCASH_STATE_5 = 5,
    WHISCASH_STATE_6 = 6,
    WHISCASH_STATE_7 = 7,
    WHISCASH_STATE_8 = 8,
    WHISCASH_STATE_9 = 9,
    WHISCASH_STATE_10 = 10,
};

#endif // GUARD_CONSTANTS_RUBY_STATES_H