#ifndef GUARD_CONSTANTS_RUBY_STATES_H
#define GUARD_CONSTANTS_RUBY_STATES_H

enum RubyPondStates{
    RUBY_POND_STATE_CHINCHOU_STAGGERED = 0,
    RUBY_POND_STATE_CHINCHOU_CLOCKWISE = 1,
    RUBY_POND_STATE_CHINCHOU_COUNTERCLOCKWISE = 2,
    RUBY_POND_STATE_CHINCHOU_ROWS = 3,
    RUBY_POND_STATE_LOTAD = 4,
    RUBY_POND_STATE_CHINCHOU_SINGLE_CLOCKWISE = 5,
    RUBY_POND_STATE_WHISCASH = 6
};

enum WhiscashStates{
    WHISCASH_STATE_ARRIVAL = 0,
    WHISCASH_STATE_SITTING = 1,
    WHISCASH_STATE_ABSORB_ZONE_HIT = 2,
    WHISCASH_STATE_ABSORBING = 3,
    WHISCASH_STATE_TO_SPHEAL_BOARD = 4,
    WHISCASH_STATE_INIT_RETURN_FROM_BONUS = 5,
    WHISCASH_STATE_RISE_SPIT_LEAVE = 6,
    WHISCASH_STATE_HIT = 7,
    WHISCASH_STATE_ANGRY = 8,
    WHISCASH_STATE_LEAVING = 9,
    WHISCASH_STATE_CLEANUP = 10,
};

#endif // GUARD_CONSTANTS_RUBY_STATES_H