#ifndef GUARD_CONSTANTS_SPECIES_H
#define GUARD_CONSTANTS_SPECIES_H

#define SPECIES_TREECKO         0
#define SPECIES_GROVYLE         1
#define SPECIES_SCEPTILE        2
#define SPECIES_TORCHIC         3
#define SPECIES_COMBUSKEN       4
#define SPECIES_BLAZIKEN        5
#define SPECIES_MUDKIP          6
#define SPECIES_MARSHTOMP       7
#define SPECIES_SWAMPERT        8
#define SPECIES_POOCHYENA       9
#define SPECIES_MIGHTYENA       10
#define SPECIES_ZIGZAGOON       11
#define SPECIES_LINOONE         12
#define SPECIES_WURMPLE         13
#define SPECIES_SILCOON         14
#define SPECIES_BEAUTIFLY       15
#define SPECIES_CASCOON         16
#define SPECIES_DUSTOX          17
#define SPECIES_LOTAD           18
#define SPECIES_LOMBRE          19
#define SPECIES_LUDICOLO        20
#define SPECIES_SEEDOT          21
#define SPECIES_NUZLEAF         22
#define SPECIES_SHIFTRY         23
#define SPECIES_TAILLOW         24
#define SPECIES_SWELLOW         25
#define SPECIES_WINGULL         26
#define SPECIES_PELIPPER        27
#define SPECIES_RALTS           28
#define SPECIES_KIRLIA          29
#define SPECIES_GARDEVOIR       30
#define SPECIES_SURSKIT         31
#define SPECIES_MASQUERAIN      32
#define SPECIES_SHROOMISH       33
#define SPECIES_BRELOOM         34
#define SPECIES_SLAKOTH         35
#define SPECIES_VIGOROTH        36
#define SPECIES_SLAKING         37
#define SPECIES_ABRA            38
#define SPECIES_KADABRA         39
#define SPECIES_ALAKAZAM        40
#define SPECIES_NINCADA         41
#define SPECIES_NINJASK         42
#define SPECIES_SHEDINJA        43
#define SPECIES_WHISMUR         44
#define SPECIES_LOUDRED         45
#define SPECIES_EXPLOUD         46
#define SPECIES_MAKUHITA        47
#define SPECIES_HARIYAMA        48
#define SPECIES_GOLDEEN         49
#define SPECIES_SEAKING         50
#define SPECIES_MAGIKARP        51
#define SPECIES_GYARADOS        52
#define SPECIES_AZURILL         53
#define SPECIES_MARILL          54
#define SPECIES_AZUMARILL       55
#define SPECIES_GEODUDE         56
#define SPECIES_GRAVELER        57
#define SPECIES_GOLEM           58
#define SPECIES_NOSEPASS        59
#define SPECIES_SKITTY          60
#define SPECIES_DELCATTY        61
#define SPECIES_ZUBAT           62
#define SPECIES_GOLBAT          63
#define SPECIES_CROBAT          64
#define SPECIES_TENTACOOL       65
#define SPECIES_TENTACRUEL      66
#define SPECIES_SABLEYE         67
#define SPECIES_MAWILE          68
#define SPECIES_ARON            69
#define SPECIES_LAIRON          70
#define SPECIES_AGGRON          71
#define SPECIES_MACHOP          72
#define SPECIES_MACHOKE         73
#define SPECIES_MACHAMP         74
#define SPECIES_MEDITITE        75
#define SPECIES_MEDICHAM        76
#define SPECIES_ELECTRIKE       77
#define SPECIES_MANECTRIC       78
#define SPECIES_PLUSLE          79
#define SPECIES_MINUN           80
#define SPECIES_MAGNEMITE       81
#define SPECIES_MAGNETON        82
#define SPECIES_VOLTORB         83
#define SPECIES_ELECTRODE       84
#define SPECIES_VOLBEAT         85
#define SPECIES_ILLUMISE        86
#define SPECIES_ODDISH          87
#define SPECIES_GLOOM           88
#define SPECIES_VILEPLUME       89
#define SPECIES_BELLOSSOM       90
#define SPECIES_DODUO           91
#define SPECIES_DODRIO          92
#define SPECIES_ROSELIA         93
#define SPECIES_GULPIN          94
#define SPECIES_SWALOT          95
#define SPECIES_CARVANHA        96
#define SPECIES_SHARPEDO        97
#define SPECIES_WAILMER         98
#define SPECIES_WAILORD         99
#define SPECIES_NUMEL           100
#define SPECIES_CAMERUPT        101
#define SPECIES_SLUGMA          102
#define SPECIES_MAGCARGO        103
#define SPECIES_TORKOAL         104
#define SPECIES_GRIMER          105
#define SPECIES_MUK             106
#define SPECIES_KOFFING         107
#define SPECIES_WEEZING         108
#define SPECIES_SPOINK          109
#define SPECIES_GRUMPIG         110
#define SPECIES_SANDSHREW       111
#define SPECIES_SANDSLASH       112
#define SPECIES_SPINDA          113
#define SPECIES_SKARMORY        114
#define SPECIES_TRAPINCH        115
#define SPECIES_VIBRAVA         116
#define SPECIES_FLYGON          117
#define SPECIES_CACNEA          118
#define SPECIES_CACTURNE        119
#define SPECIES_SWABLU          120
#define SPECIES_ALTARIA         121
#define SPECIES_ZANGOOSE        122
#define SPECIES_SEVIPER         123
#define SPECIES_LUNATONE        124
#define SPECIES_SOLROCK         125
#define SPECIES_BARBOACH        126
#define SPECIES_WHISCASH        127
#define SPECIES_CORPHISH        128
#define SPECIES_CRAWDAUNT       129
#define SPECIES_BALTOY          130
#define SPECIES_CLAYDOL         131
#define SPECIES_LILEEP          132
#define SPECIES_CRADILY         133
#define SPECIES_ANORITH         134
#define SPECIES_ARMALDO         135
#define SPECIES_IGGLYBUFF       136
#define SPECIES_JIGGLYPUFF      137
#define SPECIES_WIGGLYTUFF      138
#define SPECIES_FEEBAS          139
#define SPECIES_MILOTIC         140
#define SPECIES_CASTFORM        141
#define SPECIES_STARYU          142
#define SPECIES_STARMIE         143
#define SPECIES_KECLEON         144
#define SPECIES_SHUPPET         145
#define SPECIES_BANETTE         146
#define SPECIES_DUSKULL         147
#define SPECIES_DUSCLOPS        148
#define SPECIES_TROPIUS         149
#define SPECIES_CHIMECHO        150
#define SPECIES_ABSOL           151
#define SPECIES_VULPIX          152
#define SPECIES_NINETALES       153
#define SPECIES_PICHU           154
#define SPECIES_PIKACHU         155
#define SPECIES_RAICHU          156
#define SPECIES_PSYDUCK         157
#define SPECIES_GOLDUCK         158
#define SPECIES_WYNAUT          159
#define SPECIES_WOBBUFFET       160
#define SPECIES_NATU            161
#define SPECIES_XATU            162
#define SPECIES_GIRAFARIG       163
#define SPECIES_PHANPY          164
#define SPECIES_DONPHAN         165
#define SPECIES_PINSIR          166
#define SPECIES_HERACROSS       167
#define SPECIES_RHYHORN         168
#define SPECIES_RHYDON          169
#define SPECIES_SNORUNT         170
#define SPECIES_GLALIE          171
#define SPECIES_SPHEAL          172
#define SPECIES_SEALEO          173
#define SPECIES_WALREIN         174
#define SPECIES_CLAMPERL        175
#define SPECIES_HUNTAIL         176
#define SPECIES_GOREBYSS        177
#define SPECIES_RELICANTH       178
#define SPECIES_CORSOLA         179
#define SPECIES_CHINCHOU        180
#define SPECIES_LANTURN         181
#define SPECIES_LUVDISC         182
#define SPECIES_HORSEA          183
#define SPECIES_SEADRA          184
#define SPECIES_KINGDRA         185
#define SPECIES_BAGON           186
#define SPECIES_SHELGON         187
#define SPECIES_SALAMENCE       188
#define SPECIES_BELDUM          189
#define SPECIES_METANG          190
#define SPECIES_METAGROSS       191
#define SPECIES_REGIROCK        192
#define SPECIES_REGICE          193
#define SPECIES_REGISTEEL       194
#define SPECIES_LATIAS          195
#define SPECIES_LATIOS          196
#define SPECIES_KYOGRE          197
#define SPECIES_GROUDON         198
#define SPECIES_RAYQUAZA        199
#define SPECIES_JIRACHI         200
#define SPECIES_CHIKORITA       201
#define SPECIES_CYNDAQUIL       202
#define SPECIES_TOTODILE        203
#define SPECIES_AERODACTYL      204
#define SPECIES_TEST_EXTRA      205
#define SPECIES_ZEBSTRIKA       206
#define SPECIES_BULBASAUR         207
#define SPECIES_IVYSAUR           208
#define SPECIES_VENUSAUR          209
#define SPECIES_CHARMANDER        210
#define SPECIES_CHARMELEON        211
#define SPECIES_CHARIZARD         212
#define SPECIES_SQUIRTLE          213
#define SPECIES_WARTORTLE         214
#define SPECIES_BLASTOISE         215
#define SPECIES_CATERPIE          216
#define SPECIES_METAPOD           217
#define SPECIES_BUTTERFREE        218
#define SPECIES_WEEDLE            219
#define SPECIES_KAKUNA            220
#define SPECIES_BEEDRILL          221
#define SPECIES_PIDGEY            222
#define SPECIES_PIDGEOTTO         223
#define SPECIES_PIDGEOT           224
#define SPECIES_RATTATA           225
#define SPECIES_RATICATE          226
#define SPECIES_SPEAROW           227
#define SPECIES_FEAROW            228
#define SPECIES_EKANS             229
#define SPECIES_ARBOK             230
#define SPECIES_NIDORAN_F         231
#define SPECIES_NIDORINA          232
#define SPECIES_NIDOQUEEN         233
#define SPECIES_NIDORAN_M         234
#define SPECIES_NIDORINO          235
#define SPECIES_NIDOKING          236
#define SPECIES_CLEFAIRY          237
#define SPECIES_CLEFABLE          238
#define SPECIES_PARAS             239
#define SPECIES_PARASECT          240
#define SPECIES_VENONAT           241
#define SPECIES_VENOMOTH          242
#define SPECIES_DIGLETT           243
#define SPECIES_DUGTRIO           244
#define SPECIES_MEOWTH            245
#define SPECIES_PERSIAN           246
#define SPECIES_MANKEY            247
#define SPECIES_PRIMEAPE          248
#define SPECIES_GROWLITHE         249
#define SPECIES_ARCANINE          250
#define SPECIES_POLIWAG           251
#define SPECIES_POLIWHIRL         252
#define SPECIES_POLIWRATH         253
#define SPECIES_BELLSPROUT        254
#define SPECIES_WEEPINBELL        255
#define SPECIES_VICTREEBEL        256
#define SPECIES_PONYTA            257
#define SPECIES_RAPIDASH          258
#define SPECIES_SLOWPOKE          259
#define SPECIES_SLOWBRO           260
#define SPECIES_FARFETCHD         261
#define SPECIES_SEEL              262
#define SPECIES_DEWGONG           263
#define SPECIES_SHELLDER          264
#define SPECIES_CLOYSTER          265
#define SPECIES_GASTLY            266
#define SPECIES_HAUNTER           267
#define SPECIES_GENGAR            268
#define SPECIES_ONIX              269
#define SPECIES_DROWZEE           270
#define SPECIES_HYPNO             271
#define SPECIES_KRABBY            272
#define SPECIES_KINGLER           273
#define SPECIES_EXEGGCUTE         274
#define SPECIES_EXEGGUTOR         275
#define SPECIES_CUBONE            276
#define SPECIES_MAROWAK           277
#define SPECIES_HITMONLEE         278
#define SPECIES_HITMONCHAN        279
#define SPECIES_LICKITUNG         280
#define SPECIES_CHANSEY           281
#define SPECIES_TANGELA           282
#define SPECIES_KANGASKHAN        283
#define SPECIES_MR_MIME           284
#define SPECIES_SCYTHER           285
#define SPECIES_JYNX              286
#define SPECIES_ELECTABUZZ        287
#define SPECIES_MAGMAR            288
#define SPECIES_TAUROS            289
#define SPECIES_LAPRAS            290
#define SPECIES_DITTO             291
#define SPECIES_EEVEE             292
#define SPECIES_VAPOREON          293
#define SPECIES_JOLTEON           294
#define SPECIES_FLAREON           295
#define SPECIES_PORYGON           296
#define SPECIES_OMANYTE           297
#define SPECIES_OMASTAR           298
#define SPECIES_KABUTO            299
#define SPECIES_KABUTOPS          300
#define SPECIES_SNORLAX           301
#define SPECIES_ARTICUNO          302
#define SPECIES_ZAPDOS            303
#define SPECIES_MOLTRES           304
#define SPECIES_DRATINI           305
#define SPECIES_DRAGONAIR         306
#define SPECIES_DRAGONITE         307
#define SPECIES_MEWTWO            308
#define SPECIES_MEW               309
#define SPECIES_BAYLEEF           310
#define SPECIES_MEGANIUM          311
#define SPECIES_QUILAVA           312
#define SPECIES_TYPHLOSION        313
#define SPECIES_CROCONAW          314
#define SPECIES_FERALIGATR        315
#define SPECIES_SENTRET           316
#define SPECIES_FURRET            317
#define SPECIES_HOOTHOOT          318
#define SPECIES_NOCTOWL           319
#define SPECIES_LEDYBA            320
#define SPECIES_LEDIAN            321
#define SPECIES_SPINARAK          322
#define SPECIES_ARIADOS           323
#define SPECIES_CLEFFA            324
#define SPECIES_TOGEPI            325
#define SPECIES_TOGETIC           326
#define SPECIES_MAREEP            327
#define SPECIES_FLAAFFY           328
#define SPECIES_AMPHAROS          329
#define SPECIES_SUDOWOODO         330
#define SPECIES_POLITOED          331
#define SPECIES_HOPPIP            332
#define SPECIES_SKIPLOOM          333
#define SPECIES_JUMPLUFF          334
#define SPECIES_AIPOM             335
#define SPECIES_SUNKERN           336
#define SPECIES_SUNFLORA          337
#define SPECIES_YANMA             338
#define SPECIES_WOOPER            339
#define SPECIES_QUAGSIRE          340
#define SPECIES_ESPEON            341
#define SPECIES_UMBREON           342
#define SPECIES_MURKROW           343
#define SPECIES_SLOWKING          344
#define SPECIES_MISDREAVUS        345
#define SPECIES_UNOWN             346
#define SPECIES_PINECO            347
#define SPECIES_FORRETRESS        348
#define SPECIES_DUNSPARCE         349
#define SPECIES_GLIGAR            350
#define SPECIES_STEELIX           351
#define SPECIES_SNUBBULL          352
#define SPECIES_GRANBULL          353
#define SPECIES_QWILFISH          354
#define SPECIES_SCIZOR            355
#define SPECIES_SHUCKLE           356
#define SPECIES_SNEASEL           357
#define SPECIES_TEDDIURSA         358
#define SPECIES_URSARING          359
#define SPECIES_SWINUB            360
#define SPECIES_PILOSWINE         361
#define SPECIES_REMORAID          362
#define SPECIES_OCTILLERY         363
#define SPECIES_DELIBIRD          364
#define SPECIES_MANTINE           365
#define SPECIES_HOUNDOUR          366
#define SPECIES_HOUNDOOM          367
#define SPECIES_PORYGON2          368
#define SPECIES_STANTLER          369
#define SPECIES_SMEARGLE          370
#define SPECIES_TYROGUE           371
#define SPECIES_HITMONTOP         372
#define SPECIES_SMOOCHUM          373
#define SPECIES_ELEKID            374
#define SPECIES_MAGBY             375
#define SPECIES_MILTANK           376
#define SPECIES_BLISSEY           377
#define SPECIES_RAIKOU            378
#define SPECIES_ENTEI             379
#define SPECIES_SUICUNE           380
#define SPECIES_LARVITAR          381
#define SPECIES_PUPITAR           382
#define SPECIES_TYRANITAR         383
#define SPECIES_LUGIA             384
#define SPECIES_HO_OH             385
#define SPECIES_CELEBI            386
#define SPECIES_NONE            387

#define BONUS_SPECIES_START SPECIES_CHIKORITA
#define NUM_BONUS_SPECIES (SPECIES_TEST_EXTRA - SPECIES_CHIKORITA)
#define NUM_SPECIES SPECIES_NONE
#define NUM_SAVE_SPECIES 205

#endif // GUARD_CONSTANTS_SPECIES_H
