#ifndef GUARD_CONSTANTS_MEM_LAYOUT_RUBY
#define GUARD_CONSTANTS_MEM_LAYOUT_RUBY

#include "constants/mem_layout/shared.h"


#define BG_VRAM_ADDR_RUBY_LAYER_3_TILEMAP   BG_TILE_ADDR(TILE_INDEX(0,0,0))
#define BG_VRAM_ADDR_RUBY_LAYER_2_TILEMAP   BG_TILE_ADDR(TILE_INDEX(0,4,0))
// Tile_Index(0,8,0) - Tile(0,11,31) shared, for BG0 hud layer/debug

// Shop is shared with sapphire, and inside the HUD tilemap region
#define BG_VRAM_ADDR_MAIN_BOARD_SHOP_BG_TILEMAP   BG_TILE_ADDR(TILE_INDEX(0,8,0))
#define SIZE_OF_VRAM_MAIN_BOARD_SHOP_BG_TILEMAP   49 * MEM_SIZE_OF_TILEMAP_FOR_32_TILE_ROW

#define BG_VRAM_ADDR_RUBY_LAYER_1_TILEMAP   BG_TILE_ADDR(TILE_INDEX(0,12,0))

// Tiles

#define BG_VRAM_ADDR_RUBY_RAMP_TILES               BG_TILE_ADDR(TILE_INDEX(1,0,0))
// BG TILE_INDEX(1, 10, 0) - BG TILE_INDEX(1, 12, 31) shared for hud
#define BG_VRAM_ADDR_MAIN_SCROLL_SEGMENT_TILES          BG_TILE_ADDR(TILE_INDEX(2,0,0))
#define BG_VRAM_ADDR_RUBY_SCROLL_SEGMENT_TILES          BG_TILE_ADDR(TILE_INDEX(2,0,0))
#define SIZE_OF_VRAM_RUBY_INITIAL_BOTTOM_SCROLL_TILES   13 * MEM_SIZE_OF_TILE_ROW
#define BG_VRAM_ADDR_RUBY_INITIAL_TOP_SCROLL_TILES      BG_TILE_ADDR(TILE_INDEX(2,13,0))
#define SIZE_OF_VRAM_RUBY_INITIAL_TOP_SCROLL_TILES      9 * MEM_SIZE_OF_TILE_ROW




#define BG_VRAM_ADDR_RUBY_BMULT_SIGN_ROW0_TILES    BG_TILE_ADDR(TILE_INDEX(3, 6, 1))
#define BG_VRAM_ADDR_RUBY_BMULT_SIGN_ROW1_TILES    BG_TILE_ADDR(TILE_INDEX(3, 6, 2))

#define BG_VRAM_ADDR_RUBY_SHOP_SIGN_ROW0_TILES     BG_TILE_ADDR(TILE_INDEX(3, 6, 3))
#define BG_VRAM_ADDR_RUBY_SHOP_SIGN_ROW1_TILES     BG_TILE_ADDR(TILE_INDEX(3, 6, 9))
#define BG_VRAM_ADDR_RUBY_SHOP_SIGN_ROW2_TILES     BG_TILE_ADDR(TILE_INDEX(3, 6, 15))

#define BG_VRAM_ADDR_RUBY_LSLINGSHOT_ROW0_TILES    BG_TILE_ADDR(TILE_INDEX(3, 6, 16))
#define BG_VRAM_ADDR_RUBY_LSLINGSHOT_ROW1_TILES    BG_TILE_ADDR(TILE_INDEX(3, 6, 17))
#define BG_VRAM_ADDR_RUBY_LSLINGSHOT_ROW2_TILES    BG_TILE_ADDR(TILE_INDEX(3, 6, 19))
#define BG_VRAM_ADDR_RUBY_LSLINGSHOT_ROW3_TILES    BG_TILE_ADDR(TILE_INDEX(3, 6, 22))
#define BG_VRAM_ADDR_RUBY_LSLINGSHOT_ROW4_TILES    BG_TILE_ADDR(TILE_INDEX(3, 6, 25))

#define BG_VRAM_ADDR_RUBY_RSLINGSHOT_ROW0_TILES    BG_TILE_ADDR(TILE_INDEX(3, 6, 27))
#define BG_VRAM_ADDR_RUBY_RSLINGSHOT_ROW1_TILES    BG_TILE_ADDR(TILE_INDEX(3, 6, 28))
#define BG_VRAM_ADDR_RUBY_RSLINGSHOT_ROW2_TILES    BG_TILE_ADDR(TILE_INDEX(3, 6, 30))
#define BG_VRAM_ADDR_RUBY_RSLINGSHOT_ROW3_TILES    BG_TILE_ADDR(TILE_INDEX(3, 7, 1))
#define BG_VRAM_ADDR_RUBY_RSLINGSHOT_ROW4_TILES    BG_TILE_ADDR(TILE_INDEX(3, 7, 4))


#endif