
    .align 2, 0
dexEntry1::
    .2byte 2, 5, 2, 0xA, 1, 0, 8, 0xA, 0xA, 1, 1, 0
    .dexName "TREECKO"
    .dexCategory "WOOD GECKO"
    .dexText "TREECKO has small hooks on the bottom"
    .dexText "of its feet that enable it to scale"
    .dexText "vertical walls."
    .dexText "This POKéMON attacks by slamming foes"
    .dexText "with its thick tail."
    .dexText ""

    .align 2, 0
dexEntry2::
    .2byte 2, 5, 3, 0xA, 2, 1, 1, 0xA, 0xA, 4, 7, 6
    .dexName "GROVYLE"
    .dexCategory "WOOD GECKO"
    .dexText "The leaves growing out of GROVYLE`s"
    .dexText "body are convenient for camouflaging"
    .dexText "it from enemies in the forest."
    .dexText "This POKéMON is a master at climbing"
    .dexText "trees in jungles."
    .dexText ""

    .align 2, 0
dexEntry3::
    .2byte 2, 5, 4, 0xA, 5, 0, 7, 0xA, 1, 1, 5, 1
    .dexName "SCEPTILE"
    .dexCategory "FOREST"
    .dexText "The leaves growing on SCEPTILE`s body"
    .dexText "are very sharp edged. This POKéMON is"
    .dexText "very agile - it leaps all over the"
    .dexText "branches of trees and jumps on its foe"
    .dexText "from above or behind."
    .dexText ""

    .align 2, 0
dexEntry4::
    .2byte 2, 5, 5, 0xA, 1, 0, 4, 0xA, 0xA, 0xA, 5, 5
    .dexName "TORCHIC"
    .dexCategory "CHICK"
    .dexText "TORCHIC sticks with its TRAINER,"
    .dexText "following behind with unsteady"
    .dexText "steps."
    .dexText "This POKéMON breathes fire of over"
    .dexText "1,800 degrees F, including fireballs"
    .dexText "that leave the foe scorched black."

    .align 2, 0
dexEntry5::
    .2byte 2, 5, 6, 0xA, 2, 1, 1, 0xA, 0xA, 4, 3, 0
    .dexName "COMBUSKEN"
    .dexCategory "YOUNG FOWL"
    .dexText "COMBUSKEN toughens up its legs and"
    .dexText "thighs by running through fields and"
    .dexText "mountains."
    .dexText "This POKéMON`s legs possess both speed"
    .dexText "and power, enabling it to dole out ten"
    .dexText "kicks in one second."

    .align 2, 0
dexEntry6::
    .2byte 2, 5, 7, 0xA, 6, 0, 3, 0xA, 1, 1, 4, 6
    .dexName "BLAZIKEN"
    .dexCategory "BLAZE"
    .dexText "In battle, BLAZIKEN blows out intense"
    .dexText "flames from its wrists and attacks foes"
    .dexText "courageously."
    .dexText "The stronger the foe, the more"
    .dexText "intensely this POKéMON`s wrists burn."
    .dexText ""

    .align 2, 0
dexEntry7::
    .2byte 2, 5, 8, 0xA, 1, 0, 4, 0xA, 0xA, 1, 6, 8
    .dexName "MUDKIP"
    .dexCategory "MUD FISH"
    .dexText "In water, MUDKIP breathes using the"
    .dexText "gills on its cheeks."
    .dexText "If it is faced with a tight situation in"
    .dexText "battle, this POKéMON will unleash its"
    .dexText "amazing power - it can crush rocks"
    .dexText "bigger than itself."

    .align 2, 0
dexEntry8::
    .2byte 2, 5, 9, 0xA, 2, 0, 4, 0xA, 0xA, 6, 1, 7
    .dexName "MARSHTOMP"
    .dexCategory "MUD FISH"
    .dexText "MARSHTOMP is much faster at traveling"
    .dexText "through mud than it is at swimming."
    .dexText "This POKéMON`s hindquarters exhibit"
    .dexText "obvious development, giving it the"
    .dexText "ability to walk on just its hind legs."
    .dexText ""

    .align 2, 0
dexEntry9::
    .2byte 2, 6, 0, 0xA, 4, 1, 1, 0xA, 1, 8, 0, 6
    .dexName "SWAMPERT"
    .dexCategory "MUD FISH"
    .dexText "SWAMPERT predicts storms by sensing"
    .dexText "subtle differences in the sounds of"
    .dexText "waves and tidal winds with its fins."
    .dexText "If a storm is approaching, it piles up"
    .dexText "boulders to protect itself."
    .dexText ""

    .align 2, 0
dexEntry10::
    .2byte 2, 6, 1, 0xA, 1, 0, 8, 0xA, 0xA, 3, 0, 0
    .dexName "POOCHYENA"
    .dexCategory "BITE"
    .dexText "At first sight, POOCHYENA takes a bite"
    .dexText "at anything that moves."
    .dexText "This POKéMON chases after prey until"
    .dexText "the victim becomes exhausted."
    .dexText "However, it may turn tail if the prey"
    .dexText "strikes back."

    .align 2, 0
dexEntry11::
    .2byte 2, 6, 2, 0xA, 3, 0, 3, 0xA, 0xA, 8, 1, 6
    .dexName "MIGHTYENA"
    .dexCategory "BITE"
    .dexText "MIGHTYENA gives obvious signals when"
    .dexText "it is preparing to attack. It starts to"
    .dexText "growl deeply and then flattens its body."
    .dexText "This POKéMON will bite savagely with its"
    .dexText "sharply pointed fangs."
    .dexText ""

    .align 2, 0
dexEntry12::
    .2byte 2, 6, 3, 0xA, 1, 0, 4, 0xA, 0xA, 3, 8, 6
    .dexName "ZIGZAGOON"
    .dexCategory "TINYRACCOON"
    .dexText "ZIGZAGOON restlessly wanders"
    .dexText "everywhere at all times. This POKéMON"
    .dexText "does so because it is very curious."
    .dexText "It becomes interested in anything"
    .dexText "that it happens to see."
    .dexText ""

    .align 2, 0
dexEntry13::
    .2byte 2, 6, 4, 0xA, 1, 0, 8, 0xA, 0xA, 7, 1, 6
    .dexName "LINOONE"
    .dexCategory "RUSHING"
    .dexText "LINOONE always runs full speed and only"
    .dexText "in straight lines. If facing an obstacle,"
    .dexText "it makes a right-angle turn to evade it."
    .dexText "This POKéMON is very challenged by"
    .dexText "gently curving roads."
    .dexText ""

    .align 2, 0
dexEntry14::
    .2byte 2, 6, 5, 0xA, 1, 0, 0, 0xA, 0xA, 0xA, 7, 9
    .dexName "WURMPLE"
    .dexCategory "WORM"
    .dexText "WURMPLE is targeted by SWELLOW as"
    .dexText "prey. This POKéMON will try to resist by"
    .dexText "pointing the spikes on its rear at the"
    .dexText "attacking predator."
    .dexText "It will weaken the foe by leaking poison"
    .dexText "from the spikes."

    .align 2, 0
dexEntry15::
    .2byte 2, 6, 6, 0xA, 2, 0, 0, 0xA, 0xA, 2, 2, 0
    .dexName "SILCOON"
    .dexCategory "COCOON"
    .dexText "SILCOON was thought to endure hunger"
    .dexText "and not consume anything before its"
    .dexText "evolution. However, it is now thought"
    .dexText "that this POKéMON slakes its thirst by"
    .dexText "drinking rainwater that collects on its"
    .dexText "silk."

    .align 2, 0
dexEntry16::
    .2byte 2, 6, 7, 0xA, 3, 0, 3, 0xA, 0xA, 6, 2, 6
    .dexName "BEAUTIFLY"
    .dexCategory "BUTTERFLY"
    .dexText "BEAUTIFLY has a long mouth like a coiled"
    .dexText "needle, which is very convenient for"
    .dexText "collecting pollen from flowers."
    .dexText "This POKéMON rides the spring winds as"
    .dexText "it flits around gathering pollen."
    .dexText ""

    .align 2, 0
dexEntry17::
    .2byte 2, 6, 8, 0xA, 2, 0, 4, 0xA, 0xA, 2, 5, 4
    .dexName "CASCOON"
    .dexCategory "COCOON"
    .dexText "If it is attacked, CASCOON remains"
    .dexText "motionless however badly it may be"
    .dexText "hurt. It does so because if it were to"
    .dexText "move, its body would be weak upon"
    .dexText "evolution. This POKéMON will also not"
    .dexText "forget the pain it endured."

    .align 2, 0
dexEntry18::
    .2byte 2, 6, 9, 0xA, 3, 1, 1, 0xA, 0xA, 6, 9, 7
    .dexName "DUSTOX"
    .dexCategory "POISON MOTH"
    .dexText "When DUSTOX flaps its wings, a fine"
    .dexText "dust is scattered all over. This dust is"
    .dexText "actually a powerful poison that will"
    .dexText "even make a pro wrestler sick."
    .dexText "This POKéMON searches for food using"
    .dexText "its antennae like radar."

    .align 2, 0
dexEntry19::
    .2byte 2, 7, 0, 0xA, 1, 0, 8, 0xA, 0xA, 0xA, 5, 7
    .dexName "LOTAD"
    .dexCategory "WATER WEED"
    .dexText "LOTAD is said to have dwelled on land"
    .dexText "before. However, this POKéMON is"
    .dexText "thought to have returned to water"
    .dexText "because the leaf on its head grew large"
    .dexText "and heavy. It now lives by floating"
    .dexText "atop the water."

    .align 2, 0
dexEntry20::
    .2byte 2, 7, 1, 0xA, 3, 1, 1, 0xA, 0xA, 7, 1, 6
    .dexName "LOMBRE"
    .dexCategory "JOLLY"
    .dexText "LOMBRE`s entire body is covered by a"
    .dexText "slippery, slimy film. It feels horribly"
    .dexText "unpleasant to be touched by this"
    .dexText "POKéMON`s hands."
    .dexText "LOMBRE is often mistaken for a human"
    .dexText "child."

    .align 2, 0
dexEntry21::
    .2byte 2, 7, 2, 0xA, 4, 1, 1, 0xA, 1, 2, 1, 3
    .dexName "LUDICOLO"
    .dexCategory "CAREFREE"
    .dexText "Upon hearing an upbeat and cheerful"
    .dexText "rhythm, the cells in LUDICOLO`s body"
    .dexText "become very energetic and active."
    .dexText "Even in battle, this POKéMON will"
    .dexText "exhibit an amazing amount of power."
    .dexText ""

    .align 2, 0
dexEntry22::
    .2byte 2, 7, 3, 0xA, 1, 0, 8, 0xA, 0xA, 0xA, 8, 8
    .dexName "SEEDOT"
    .dexCategory "ACORN"
    .dexText "SEEDOT attaches itself to a tree"
    .dexText "branch using the top of its head."
    .dexText "It sucks moisture from the tree while"
    .dexText "hanging off the branch."
    .dexText "The more water it drinks, the glossier"
    .dexText "this POKéMON`s body becomes."

    .align 2, 0
dexEntry23::
    .2byte 2, 7, 4, 0xA, 3, 0, 3, 0xA, 0xA, 6, 1, 7
    .dexName "NUZLEAF"
    .dexCategory "WILY"
    .dexText "NUZLEAF live in densely overgrown"
    .dexText "forests. They occasionally venture out"
    .dexText "of the forest to startle people."
    .dexText "This POKéMON dislikes having its long"
    .dexText "nose pinched."
    .dexText ""

    .align 2, 0
dexEntry24::
    .2byte 2, 7, 5, 0xA, 4, 0, 3, 0xA, 1, 3, 1, 4
    .dexName "SHIFTRY"
    .dexCategory "WICKED"
    .dexText "SHIFTRY is a mysterious POKéMON that"
    .dexText "is said to live atop towering trees"
    .dexText "dating back over a thousand years."
    .dexText "It creates terrific windstorms with"
    .dexText "the fans it holds."
    .dexText ""

    .align 2, 0
dexEntry25::
    .2byte 2, 7, 6, 0xA, 1, 0, 0, 0xA, 0xA, 0xA, 5, 1
    .dexName "TAILLOW"
    .dexCategory "TINYSWALLOW"
    .dexText "TAILLOW courageously stands its"
    .dexText "ground against foes, however strong"
    .dexText "they may be."
    .dexText "This gutsy POKéMON will remain defiant"
    .dexText "even after a loss. On the other hand,"
    .dexText "it cries loudly if it becomes hungry."

    .align 2, 0
dexEntry26::
    .2byte 2, 7, 7, 0xA, 2, 0, 4, 0xA, 0xA, 4, 3, 7
    .dexName "SWELLOW"
    .dexCategory "SWALLOW"
    .dexText "SWELLOW flies high above our heads,"
    .dexText "making graceful arcs in the sky."
    .dexText "This POKéMON dives at a steep angle as"
    .dexText "soon as it spots its prey. The hapless"
    .dexText "prey is tightly grasped by SWELLOW`s"
    .dexText "clawed feet, preventing escape."

    .align 2, 0
dexEntry27::
    .2byte 2, 7, 8, 0xA, 2, 0, 0, 0xA, 0xA, 2, 0, 9
    .dexName "WINGULL"
    .dexCategory "SEAGULL"
    .dexText "WINGULL has the habit of carrying prey"
    .dexText "and valuables in its beak and hiding"
    .dexText "them in all sorts of locations."
    .dexText "This POKéMON rides the winds and flies"
    .dexText "as if it were skating across the sky."
    .dexText ""

    .align 2, 0
dexEntry28::
    .2byte 2, 7, 9, 0xA, 3, 1, 1, 0xA, 0xA, 6, 1, 7
    .dexName "PELIPPER"
    .dexCategory "WATER BIRD"
    .dexText "PELIPPER is a flying transporter that"
    .dexText "carries small POKéMON and eggs inside"
    .dexText "its massive bill."
    .dexText "This POKéMON builds its nest on steep"
    .dexText "cliffs facing the sea."
    .dexText ""

    .align 2, 0
dexEntry29::
    .2byte 2, 8, 0, 0xA, 1, 0, 4, 0xA, 0xA, 1, 4, 6
    .dexName "RALTS"
    .dexCategory "FEELING"
    .dexText "RALTS senses the emotions of"
    .dexText "people using the horns on its head."
    .dexText "This POKéMON rarely appears before"
    .dexText "people. But when it does, it draws"
    .dexText "closer if it senses that the person has"
    .dexText "a positive disposition."

    .align 2, 0
dexEntry30::
    .2byte 2, 8, 1, 0xA, 2, 0, 7, 0xA, 0xA, 4, 4, 5
    .dexName "KIRLIA"
    .dexCategory "EMOTION"
    .dexText "It is said that a KIRLIA that is"
    .dexText "exposed to the positive emotions of"
    .dexText "its TRAINER grows beautiful."
    .dexText "This POKéMON controls psychokinetic"
    .dexText "powers with its highly developed brain."
    .dexText ""

    .align 2, 0
dexEntry31::
    .2byte 2, 8, 2, 0xA, 5, 0, 3, 0xA, 1, 0, 6, 7
    .dexName "GARDEVOIR"
    .dexCategory "EMBRACE"
    .dexText "GARDEVOIR has the ability to read the"
    .dexText "future. If it senses impending danger"
    .dexText "to its TRAINER, this POKéMON is said to"
    .dexText "unleash its psychokinetic energy at"
    .dexText "full power."
    .dexText ""

    .align 2, 0
dexEntry32::
    .2byte 2, 8, 3, 0xA, 1, 0, 8, 0xA, 0xA, 0xA, 3, 7
    .dexName "SURSKIT"
    .dexCategory "POND SKATER"
    .dexText "If SURSKIT senses danger, it secretes"
    .dexText "a thick, sugary syrup from the tip of"
    .dexText "its head."
    .dexText "There are some POKéMON that love"
    .dexText "eating this syrup."
    .dexText ""

    .align 2, 0
dexEntry33::
    .2byte 2, 8, 4, 0xA, 2, 0, 7, 0xA, 0xA, 0xA, 7, 9
    .dexName "MASQUERAIN"
    .dexCategory "EYEBALL"
    .dexText "MASQUERAIN`s antennas have eyelike"
    .dexText "patterns that usually give it an angry"
    .dexText "look. If the “eyes” are droopy and"
    .dexText "appear sad, it is said to be a sign"
    .dexText "that a heavy rainfall is on its way."
    .dexText ""

    .align 2, 0
dexEntry34::
    .2byte 2, 8, 5, 0xA, 1, 0, 4, 0xA, 0xA, 0xA, 9, 9
    .dexName "SHROOMISH"
    .dexCategory "MUSHROOM"
    .dexText "SHROOMISH live in damp soil in the dark"
    .dexText "depths of forests. They are often"
    .dexText "found keeping still under fallen leaves."
    .dexText "This POKéMON feeds on compost that"
    .dexText "is made up of fallen, rotted leaves."
    .dexText ""

    .align 2, 0
dexEntry35::
    .2byte 2, 8, 6, 0xA, 3, 1, 1, 0xA, 0xA, 8, 6, 4
    .dexName "BRELOOM"
    .dexCategory "MUSHROOM"
    .dexText "BRELOOM closes in on its foe with light"
    .dexText "and sprightly footwork, then throws"
    .dexText "punches with its stretchy arms."
    .dexText "This POKéMON`s fighting technique puts"
    .dexText "boxers to shame."
    .dexText ""

    .align 2, 0
dexEntry36::
    .2byte 2, 8, 7, 0xA, 2, 0, 7, 0xA, 0xA, 5, 2, 9
    .dexName "SLAKOTH"
    .dexCategory "SLACKER"
    .dexText "SLAKOTH`s heart beats just once a"
    .dexText "minute. Whatever happens, it is"
    .dexText "content to loaf around motionless."
    .dexText "It is rare to see this POKéMON in"
    .dexText "motion."
    .dexText ""

    .align 2, 0
dexEntry37::
    .2byte 2, 8, 8, 0xA, 4, 0, 7, 0xA, 1, 0, 2, 5
    .dexName "VIGOROTH"
    .dexCategory "WILD MONKEY"
    .dexText "VIGOROTH is simply incapable of"
    .dexText "remaining still. Even when it tries to"
    .dexText "sleep, the blood in its veins grows"
    .dexText "agitated, compelling this POKéMON to"
    .dexText "run wild throughout the jungle before"
    .dexText "it can settle down."

    .align 2, 0
dexEntry38::
    .2byte 2, 8, 9, 0xA, 6, 0, 7, 0xA, 2, 8, 7, 7
    .dexName "SLAKING"
    .dexCategory "LAZY"
    .dexText "Wherever SLAKING live, rings of over"
    .dexText "a yard in diameter appear in grassy"
    .dexText "fields. They are made by the POKéMON"
    .dexText "as it eats all the grass within reach"
    .dexText "while lying prone on the ground."
    .dexText ""

    .align 2, 0
dexEntry39::
    .2byte 0, 6, 3, 0xA, 2, 1, 1, 0xA, 0xA, 4, 3, 0
    .dexName "ABRA"
    .dexCategory "PSI"
    .dexText "ABRA needs to sleep for eighteen hours"
    .dexText "a day. If it doesn`t, this POKéMON loses"
    .dexText "its ability to use telekinetic powers."
    .dexText "If it is attacked, ABRA escapes using"
    .dexText "TELEPORT while it is still sleeping."
    .dexText ""

    .align 2, 0
dexEntry40::
    .2byte 0, 6, 4, 0xA, 4, 0, 3, 0xA, 1, 2, 4, 6
    .dexName "KADABRA"
    .dexCategory "PSI"
    .dexText "KADABRA holds a silver spoon in its"
    .dexText "hand. The spoon is used to amplify the"
    .dexText "alpha waves in its brain."
    .dexText "Without the spoon, the POKéMON is said"
    .dexText "to be limited to half the usual amount"
    .dexText "of its telekinetic powers."

    .align 2, 0
dexEntry41::
    .2byte 0, 6, 5, 0xA, 4, 1, 1, 0xA, 1, 0, 5, 8
    .dexName "ALAKAZAM"
    .dexCategory "PSI"
    .dexText "ALAKAZAM`s brain continually grows,"
    .dexText "infinitely multiplying brain cells."
    .dexText "This amazing brain gives this POKéMON"
    .dexText "an astoundingly high IQ of 5,000."
    .dexText "It has a thorough memory of everything"
    .dexText "that has occurred in the world."

    .align 2, 0
dexEntry42::
    .2byte 2, 9, 0, 0xA, 1, 0, 8, 0xA, 0xA, 1, 2, 1
    .dexName "NINCADA"
    .dexCategory "TRAINEE"
    .dexText "NINCADA lives underground for many"
    .dexText "years in complete darkness."
    .dexText "This POKéMON absorbs nutrients from"
    .dexText "the roots of trees. It stays motionless"
    .dexText "as it waits for evolution."
    .dexText ""

    .align 2, 0
dexEntry43::
    .2byte 2, 9, 1, 0xA, 2, 0, 7, 0xA, 0xA, 2, 6, 5
    .dexName "NINJASK"
    .dexCategory "NINJA"
    .dexText "NINJASK moves around at such a high"
    .dexText "speed that it cannot be seen, even"
    .dexText "while its crying can be clearly heard."
    .dexText "For that reason, this POKéMON was long"
    .dexText "believed to be invisible."
    .dexText ""

    .align 2, 0
dexEntry44::
    .2byte 2, 9, 2, 0xA, 2, 0, 7, 0xA, 0xA, 0xA, 2, 6
    .dexName "SHEDINJA"
    .dexCategory "SHED"
    .dexText "SHEDINJA`s hard body doesn`t move -"
    .dexText "not even a twitch. In fact, its body"
    .dexText "appears to be merely a hollow shell."
    .dexText "It is believed that this POKéMON will"
    .dexText "steal the spirit of anyone peering into"
    .dexText "its hollow body from its back."

    .align 2, 0
dexEntry45::
    .2byte 2, 9, 3, 0xA, 2, 0, 0, 0xA, 0xA, 3, 5, 9
    .dexName "WHISMUR"
    .dexCategory "WHISPER"
    .dexText "WHISMUR is very timid. If it starts to"
    .dexText "cry loudly, it becomes startled by its"
    .dexText "own crying and cries even harder."
    .dexText "When it finally stops crying, the"
    .dexText "POKéMON goes to sleep, all tired out."
    .dexText ""

    .align 2, 0
dexEntry46::
    .2byte 2, 9, 4, 0xA, 3, 0, 3, 0xA, 0xA, 8, 9, 3
    .dexName "LOUDRED"
    .dexCategory "BIG VOICE"
    .dexText "LOUDRED shouts while stamping its feet."
    .dexText "After it finishes shouting, this"
    .dexText "POKéMON becomes incapable of hearing"
    .dexText "anything for a while. This is considered"
    .dexText "to be a weak point."
    .dexText ""

    .align 2, 0
dexEntry47::
    .2byte 2, 9, 5, 0xA, 4, 1, 1, 0xA, 1, 8, 5, 2
    .dexName "EXPLOUD"
    .dexCategory "LOUD NOISE"
    .dexText "EXPLOUD communicates its feelings to"
    .dexText "the others by emitting whistle-like"
    .dexText "sounds from the tubes on its body."
    .dexText "This POKéMON only raises its voice when"
    .dexText "it is in battle."
    .dexText ""

    .align 2, 0
dexEntry48::
    .2byte 2, 9, 6, 0xA, 3, 0, 3, 0xA, 1, 9, 0, 5
    .dexName "MAKUHITA"
    .dexCategory "GUTS"
    .dexText "MAKUHITA has a tireless spirit -"
    .dexText "it will never give up hope. It eats a lot"
    .dexText "of food, gets plenty of sleep, and it"
    .dexText "trains very rigorously. By living that"
    .dexText "way, this POKéMON packs its body with"
    .dexText "energy."

    .align 2, 0
dexEntry49::
    .2byte 2, 9, 7, 0xA, 7, 0, 7, 0xA, 5, 5, 9, 5
    .dexName "HARIYAMA"
    .dexCategory "ARM THRUST"
    .dexText "HARIYAMA`s thick body may appear fat,"
    .dexText "but it is actually a hunk of solid muscle."
    .dexText "If this POKéMON bears down and"
    .dexText "tightens all its muscles, its body"
    .dexText "becomes as hard as a rock."
    .dexText ""

    .align 2, 0
dexEntry50::
    .2byte 1, 1, 8, 0xA, 2, 0, 0, 0xA, 0xA, 3, 3, 1
    .dexName "GOLDEEN"
    .dexCategory "GOLDFISH"
    .dexText "GOLDEEN loves swimming wild and free"
    .dexText "in rivers and ponds."
    .dexText "If one of these POKéMON is placed in an"
    .dexText "aquarium, it will shatter even the"
    .dexText "thickest glass with one ram of its horn"
    .dexText "and make its escape."

    .align 2, 0
dexEntry51::
    .2byte 1, 1, 9, 0xA, 4, 0, 3, 0xA, 0xA, 8, 6, 0
    .dexName "SEAKING"
    .dexCategory "GOLDFISH"
    .dexText "SEAKING is very protective of its eggs."
    .dexText "The male and female will take turns"
    .dexText "patrolling around their nest and eggs."
    .dexText "The guarding of eggs by these POKéMON"
    .dexText "goes on for over a month."
    .dexText ""

    .align 2, 0
dexEntry52::
    .2byte 1, 2, 9, 0xA, 2, 1, 1, 0xA, 0xA, 2, 2, 0
    .dexName "MAGIKARP"
    .dexCategory "FISH"
    .dexText "MAGIKARP is virtually useless in battle"
    .dexText "as it can only splash around."
    .dexText "As a result, it is considered to be weak."
    .dexText "However, it is actually a very hardy"
    .dexText "POKéMON that can survive in any body of"
    .dexText "water no matter how polluted it is."

    .align 2, 0
dexEntry53::
    .2byte 1, 3, 0, 2, 1, 0, 4, 0xA, 5, 1, 8, 1
    .dexName "GYARADOS"
    .dexCategory "ATROCIOUS"
    .dexText "Once GYARADOS goes on a rampage, its"
    .dexText "ferociously violent blood doesn`t calm"
    .dexText "until it has burned everything down."
    .dexText "There are records of this POKéMON`s"
    .dexText "rampages lasting a whole month."
    .dexText ""

    .align 2, 0
dexEntry54::
    .2byte 2, 9, 8, 0xA, 0, 0, 8, 0xA, 0xA, 0xA, 4, 4
    .dexName "AZURILL"
    .dexCategory "POLKA DOT"
    .dexText "AZURILL`s tail is large and bouncy."
    .dexText "It is packed full of the nutrients this"
    .dexText "POKéMON needs to grow."
    .dexText "AZURILL can be seen bouncing and"
    .dexText "playing on its big, rubbery tail."
    .dexText ""

    .align 2, 0
dexEntry55::
    .2byte 1, 8, 3, 0xA, 1, 0, 4, 0xA, 0xA, 1, 8, 7
    .dexName "MARILL"
    .dexCategory "AQUA MOUSE"
    .dexText "When fishing for food at the edge of a"
    .dexText "fast-running stream, MARILL wraps its"
    .dexText "tail around the trunk of a tree."
    .dexText "This POKéMON`s tail is flexible and"
    .dexText "configured to stretch."
    .dexText ""

    .align 2, 0
dexEntry56::
    .2byte 1, 8, 4, 0xA, 2, 0, 7, 0xA, 0xA, 6, 2, 8
    .dexName "AZUMARILL"
    .dexCategory "AQUA RABBIT"
    .dexText "AZUMARILL can make balloons out of"
    .dexText "air. It makes these air balloons if it"
    .dexText "spots a drowning POKéMON."
    .dexText "The air balloons enable the POKéMON in"
    .dexText "trouble to breathe."
    .dexText ""

    .align 2, 0
dexEntry57::
    .2byte 0, 7, 4, 0xA, 1, 0, 4, 0xA, 0xA, 4, 4, 1
    .dexName "GEODUDE"
    .dexCategory "ROCK"
    .dexText "When GEODUDE sleeps deeply, it buries"
    .dexText "itself halfway into the ground."
    .dexText "It will not awaken even if hikers step"
    .dexText "on it unwittingly."
    .dexText "In the morning, this POKéMON rolls"
    .dexText "downhill in search of food."

    .align 2, 0
dexEntry58::
    .2byte 0, 7, 5, 0xA, 3, 0, 3, 0xA, 2, 3, 1, 5
    .dexName "GRAVELER"
    .dexCategory "ROCK"
    .dexText "Rocks are GRAVELER`s favorite food."
    .dexText "This POKéMON will climb a mountain from"
    .dexText "the base to the summit, crunchingly"
    .dexText "feasting on rocks all the while."
    .dexText "Upon reaching the peak, it rolls back"
    .dexText "down to the bottom."

    .align 2, 0
dexEntry59::
    .2byte 0, 7, 6, 0xA, 4, 0, 7, 0xA, 6, 6, 1, 4
    .dexName "GOLEM"
    .dexCategory "MEGATON"
    .dexText "GOLEM is known for rolling down from"
    .dexText "mountains. To prevent them from rolling"
    .dexText "into the homes of people downhill,"
    .dexText "grooves have been dug into the sides of"
    .dexText "mountains to serve as guideways for"
    .dexText "diverting this POKéMON`s course."

    .align 2, 0
dexEntry60::
    .2byte 2, 9, 9, 0xA, 3, 0, 3, 0xA, 2, 1, 3, 8
    .dexName "NOSEPASS"
    .dexCategory "COMPASS"
    .dexText "NOSEPASS`s magnetic nose is always"
    .dexText "pointed to the north. If two of these"
    .dexText "POKéMON meet, they cannot turn"
    .dexText "their faces to each other when they"
    .dexText "are close because their magnetic noses"
    .dexText "repel one another."

    .align 2, 0
dexEntry61::
    .2byte 3, 0, 0, 0xA, 2, 0, 0, 0xA, 0xA, 2, 4, 3
    .dexName "SKITTY"
    .dexCategory "KITTEN"
    .dexText "SKITTY has the habit of becoming"
    .dexText "fascinated by moving objects and"
    .dexText "chasing them around."
    .dexText "This POKéMON is known to chase after"
    .dexText "its own tail and become dizzy."
    .dexText ""

    .align 2, 0
dexEntry62::
    .2byte 3, 0, 1, 0xA, 3, 0, 7, 0xA, 0xA, 7, 1, 9
    .dexName "DELCATTY"
    .dexCategory "PRIM"
    .dexText "DELCATTY prefers to live an unfettered"
    .dexText "existence in which it can do as it"
    .dexText "pleases at its own pace."
    .dexText "Because this POKéMON eats and sleeps"
    .dexText "whenever it decides, its daily routines"
    .dexText "are completely random."

    .align 2, 0
dexEntry63::
    .2byte 0, 4, 1, 0xA, 2, 0, 7, 0xA, 0xA, 1, 6, 5
    .dexName "ZUBAT"
    .dexCategory "BAT"
    .dexText "ZUBAT avoids sunlight because exposure"
    .dexText "causes it to become unhealthy."
    .dexText "During the daytime, it stays in caves or"
    .dexText "under the eaves of old houses, sleeping"
    .dexText "while hanging upside down."
    .dexText ""

    .align 2, 0
dexEntry64::
    .2byte 0, 4, 2, 0xA, 5, 0, 3, 0xA, 1, 2, 1, 3
    .dexName "GOLBAT"
    .dexCategory "BAT"
    .dexText "GOLBAT bites down on prey with its four"
    .dexText "fangs and drinks the victim`s blood."
    .dexText "It becomes active on inky dark"
    .dexText "moonless nights, flying around to"
    .dexText "attack people and POKéMON."
    .dexText ""

    .align 2, 0
dexEntry65::
    .2byte 1, 6, 9, 0xA, 5, 1, 1, 0xA, 1, 6, 5, 3
    .dexName "CROBAT"
    .dexCategory "BAT"
    .dexText "CROBAT sneaks up on its intended prey"
    .dexText "using wings that barely make a sound."
    .dexText "This POKéMON rests by hanging on a"
    .dexText "tree branch with its rear legs that"
    .dexText "serve as wings."
    .dexText ""

    .align 2, 0
dexEntry66::
    .2byte 0, 7, 2, 0xA, 2, 1, 1, 0xA, 1, 0, 0, 3
    .dexName "TENTACOOL"
    .dexCategory "JELLYFISH"
    .dexText "TENTACOOL`s body is largely composed"
    .dexText "of water. If it is removed from the"
    .dexText "sea, it dries up like parchment."
    .dexText "If this POKéMON happens to become"
    .dexText "dehydrated, put it back into the sea."
    .dexText ""

    .align 2, 0
dexEntry67::
    .2byte 0, 7, 3, 0xA, 5, 0, 3, 0xA, 1, 2, 1, 3
    .dexName "TENTACRUEL"
    .dexCategory "JELLYFISH"
    .dexText "TENTACRUEL has large red orbs on its"
    .dexText "head. The orbs glow before lashing the"
    .dexText "vicinity with a harsh ultrasonic blast."
    .dexText "This POKéMON`s outburst creates rough"
    .dexText "waves around it."
    .dexText ""

    .align 2, 0
dexEntry68::
    .2byte 3, 0, 2, 0xA, 1, 0, 8, 0xA, 0xA, 2, 4, 3
    .dexName "SABLEYE"
    .dexCategory "DARKNESS"
    .dexText "SABLEYE digs the ground with sharpened"
    .dexText "claws to find rocks that it eats."
    .dexText "Substances in the eaten rocks"
    .dexText "crystallize and rise up to the POKéMON`s"
    .dexText "body surface."
    .dexText ""

    .align 2, 0
dexEntry69::
    .2byte 3, 0, 3, 0xA, 2, 0, 0, 0xA, 0xA, 2, 5, 4
    .dexName "MAWILE"
    .dexCategory "DECEIVER"
    .dexText "MAWILE`s huge jaws are actually steel"
    .dexText "horns that have been transformed."
    .dexText "Its docile-looking face serves to lull"
    .dexText "its foe into letting down its guard."
    .dexText "When the foe least expects it, MAWILE"
    .dexText "chomps it with its gaping jaws."

    .align 2, 0
dexEntry70::
    .2byte 3, 0, 4, 0xA, 1, 0, 4, 0xA, 1, 3, 2, 3
    .dexName "ARON"
    .dexCategory "IRON ARMOR"
    .dexText "ARON has a body of steel."
    .dexText "With one all-out charge, this POKéMON"
    .dexText "can demolish even a heavy dump truck."
    .dexText "The destroyed dump truck then becomes"
    .dexText "a handy meal for the POKéMON."
    .dexText ""

    .align 2, 0
dexEntry71::
    .2byte 3, 0, 5, 0xA, 2, 1, 1, 0xA, 2, 6, 4, 6
    .dexName "LAIRON"
    .dexCategory "IRON ARMOR"
    .dexText "LAIRON feeds on iron contained in"
    .dexText "rocks and water. It makes its nest on"
    .dexText "mountains where iron ore is buried."
    .dexText "As a result, the POKéMON often clashes"
    .dexText "with humans mining the iron ore."
    .dexText ""

    .align 2, 0
dexEntry72::
    .2byte 3, 0, 6, 0xA, 6, 1, 1, 0xA, 7, 9, 3, 7
    .dexName "AGGRON"
    .dexCategory "IRON ARMOR"
    .dexText "AGGRON is surprisingly protective"
    .dexText "of its environment. If its mountain"
    .dexText "is ravaged by a landslide or a fire, this"
    .dexText "POKéMON will haul topsoil to the area,"
    .dexText "plant trees, and beautifully restore its"
    .dexText "own territory."

    .align 2, 0
dexEntry73::
    .2byte 0, 6, 6, 0xA, 2, 0, 7, 0xA, 0xA, 4, 3, 0
    .dexName "MACHOP"
    .dexCategory "SUPERPOWER"
    .dexText "MACHOP`s muscles are special - they"
    .dexText "never get sore no matter how much they"
    .dexText "are used in exercise."
    .dexText "This POKéMON has sufficient power to"
    .dexText "hurl a hundred adult humans."
    .dexText ""

    .align 2, 0
dexEntry74::
    .2byte 0, 6, 7, 0xA, 4, 1, 1, 0xA, 1, 5, 5, 4
    .dexName "MACHOKE"
    .dexCategory "SUPERPOWER"
    .dexText "MACHOKE`s thoroughly toned muscles"
    .dexText "possess the hardness of steel."
    .dexText "This POKéMON has so much strength,"
    .dexText "it can easily hold aloft a sumo wrestler"
    .dexText "on just one finger."
    .dexText ""

    .align 2, 0
dexEntry75::
    .2byte 0, 6, 8, 0xA, 5, 0, 3, 0xA, 2, 8, 6, 6
    .dexName "MACHAMP"
    .dexCategory "SUPERPOWER"
    .dexText "MACHAMP has the power to hurl anything"
    .dexText "aside. However, trying to do any work"
    .dexText "requiring care and dexterity causes"
    .dexText "its arms to get tangled."
    .dexText "This POKéMON tends to leap into action"
    .dexText "before it thinks."

    .align 2, 0
dexEntry76::
    .2byte 3, 0, 7, 0xA, 2, 0, 0, 0xA, 0xA, 2, 4, 7
    .dexName "MEDITITE"
    .dexCategory "MEDITATE"
    .dexText "MEDITITE heightens its inner energy"
    .dexText "through meditation. It survives on"
    .dexText "just one berry a day."
    .dexText "Minimal eating is another aspect of"
    .dexText "this POKéMON`s training."
    .dexText ""

    .align 2, 0
dexEntry77::
    .2byte 3, 0, 8, 0xA, 4, 0, 3, 0xA, 0xA, 6, 9, 4
    .dexName "MEDICHAM"
    .dexCategory "MEDITATE"
    .dexText "Through the power of meditation,"
    .dexText "MEDICHAM developed its sixth sense."
    .dexText "It gained the ability to use"
    .dexText "psychokinetic powers. This POKéMON is"
    .dexText "known to meditate for a whole month"
    .dexText "without eating."

    .align 2, 0
dexEntry78::
    .2byte 3, 0, 9, 0xA, 2, 0, 0, 0xA, 0xA, 3, 3, 5
    .dexName "ELECTRIKE"
    .dexCategory "LIGHTNING"
    .dexText "ELECTRIKE stores electricity in its"
    .dexText "long body hair. This POKéMON stimulates"
    .dexText "its leg muscles with electric charges."
    .dexText "These jolts of power give its legs"
    .dexText "explosive acceleration performance."
    .dexText ""

    .align 2, 0
dexEntry79::
    .2byte 3, 1, 0, 0xA, 4, 1, 1, 0xA, 0xA, 8, 8, 6
    .dexName "MANECTRIC"
    .dexCategory "DISCHARGE"
    .dexText "MANECTRIC is constantly discharging"
    .dexText "electricity from its mane. The sparks"
    .dexText "sometimes ignite forest fires."
    .dexText "When it enters a battle, this POKéMON"
    .dexText "creates thunderclouds."
    .dexText ""

    .align 2, 0
dexEntry80::
    .2byte 3, 1, 1, 0xA, 1, 0, 4, 0xA, 0xA, 0xA, 9, 3
    .dexName "PLUSLE"
    .dexCategory "CHEERING"
    .dexText "PLUSLE always acts as a cheerleader"
    .dexText "for its partners. Whenever a teammate"
    .dexText "puts out a good effort in battle, this"
    .dexText "POKéMON shorts out its body to create"
    .dexText "the crackling noises of sparks to show"
    .dexText "its joy."

    .align 2, 0
dexEntry81::
    .2byte 3, 1, 2, 0xA, 1, 0, 4, 0xA, 0xA, 0xA, 9, 3
    .dexName "MINUN"
    .dexCategory "CHEERING"
    .dexText "MINUN is more concerned about cheering"
    .dexText "on its partners than its own safety."
    .dexText "It shorts out the electricity in its"
    .dexText "body to create brilliant showers of"
    .dexText "sparks to cheer on its teammates."
    .dexText ""

    .align 2, 0
dexEntry82::
    .2byte 0, 8, 1, 0xA, 1, 0, 0, 0xA, 0xA, 1, 3, 2
    .dexName "MAGNEMITE"
    .dexCategory "MAGNET"
    .dexText "MAGNEMITE floats in the air by emitting"
    .dexText "electromagnetic waves from the units"
    .dexText "at its sides. These waves block gravity."
    .dexText "This POKéMON becomes incapable of"
    .dexText "flight if its internal electrical supply"
    .dexText "is depleted."

    .align 2, 0
dexEntry83::
    .2byte 0, 8, 2, 0xA, 3, 0, 3, 0xA, 1, 3, 2, 3
    .dexName "MAGNETON"
    .dexCategory "MAGNET"
    .dexText "MAGNETON emits a powerful magnetic"
    .dexText "force that is fatal to electronics and"
    .dexText "precision instruments. Because of"
    .dexText "this, it is said that some towns warn"
    .dexText "people to keep this POKéMON inside"
    .dexText "a POKé BALL."

    .align 2, 0
dexEntry84::
    .2byte 1, 0, 0, 0xA, 1, 0, 8, 0xA, 0xA, 2, 2, 9
    .dexName "VOLTORB"
    .dexCategory "BALL"
    .dexText "VOLTORB was first sighted at a company"
    .dexText "that manufactures POKé BALLS."
    .dexText "The link between that sighting and"
    .dexText "the fact that this POKéMON looks very"
    .dexText "similar to a POKé BALL remains a"
    .dexText "mystery."

    .align 2, 0
dexEntry85::
    .2byte 1, 0, 1, 0xA, 3, 1, 1, 0xA, 1, 4, 6, 8
    .dexName "ELECTRODE"
    .dexCategory "BALL"
    .dexText "ELECTRODE eats electricity in the"
    .dexText "atmosphere. On days when lightning"
    .dexText "strikes, you can see this POKéMON"
    .dexText "exploding all over the place from"
    .dexText "eating too much electricity."
    .dexText ""

    .align 2, 0
dexEntry86::
    .2byte 3, 1, 3, 0xA, 2, 0, 4, 0xA, 0xA, 3, 9, 0
    .dexName "VOLBEAT"
    .dexCategory "FIREFLY"
    .dexText "VOLBEAT`s tail glows like a lightbulb."
    .dexText "With other VOLBEAT, it uses its tail to"
    .dexText "draw geometric shapes in the night sky."
    .dexText "This POKéMON loves the sweet aroma"
    .dexText "given off by ILLUMISE."
    .dexText ""

    .align 2, 0
dexEntry87::
    .2byte 3, 1, 4, 0xA, 2, 0, 0, 0xA, 0xA, 3, 9, 0
    .dexName "ILLUMISE"
    .dexCategory "FIREFLY"
    .dexText "ILLUMISE attracts a swarm of VOLBEAT"
    .dexText "using a sweet fragrance. Once the"
    .dexText "VOLBEAT have gathered, this POKéMON"
    .dexText "leads the lit-up swarm in drawing"
    .dexText "geometric designs on the canvas of"
    .dexText "the night sky."

    .align 2, 0
dexEntry88::
    .2byte 0, 4, 3, 0xA, 1, 0, 8, 0xA, 0xA, 1, 1, 9
    .dexName "ODDISH"
    .dexCategory "WEED"
    .dexText "ODDISH searches for fertile, nutrient-"
    .dexText "rich soil, then plants itself."
    .dexText "During the daytime, while it is planted,"
    .dexText "this POKéMON`s feet are thought to"
    .dexText "change shape and become similar to"
    .dexText "the roots of trees."

    .align 2, 0
dexEntry89::
    .2byte 0, 4, 4, 0xA, 2, 0, 7, 0xA, 0xA, 1, 9, 0
    .dexName "GLOOM"
    .dexCategory "WEED"
    .dexText "From its mouth GLOOM drips honey that"
    .dexText "smells absolutely horrible."
    .dexText "Apparently, it loves the horrid stench."
    .dexText "It sniffs the noxious fumes and then"
    .dexText "drools even more of its honey."
    .dexText ""

    .align 2, 0
dexEntry90::
    .2byte 0, 4, 5, 0xA, 3, 1, 1, 0xA, 0xA, 4, 1, 0
    .dexName "VILEPLUME"
    .dexCategory "FLOWER"
    .dexText "VILEPLUME has the world`s largest"
    .dexText "petals. They are used to attract prey"
    .dexText "that are then doused with toxic spores."
    .dexText "Once the prey are immobilized, this"
    .dexText "POKéMON catches and devours them."
    .dexText ""

    .align 2, 0
dexEntry91::
    .2byte 1, 8, 2, 0xA, 1, 0, 4, 0xA, 0xA, 1, 2, 8
    .dexName "BELLOSSOM"
    .dexCategory "FLOWER"
    .dexText "A BELLOSSOM grows flowers more"
    .dexText "beautifully if it has evolved from a"
    .dexText "smelly GLOOM - the stinkier the better."
    .dexText "At night, this POKéMON closes its"
    .dexText "petals and goes to sleep."
    .dexText ""

    .align 2, 0
dexEntry92::
    .2byte 0, 8, 4, 0xA, 4, 0, 7, 0xA, 0xA, 8, 6, 4
    .dexName "DODUO"
    .dexCategory "TWIN BIRD"
    .dexText "DODUO`s two heads never sleep at the"
    .dexText "same time."
    .dexText "Its two heads take turns sleeping,"
    .dexText "so one head can always keep watch for"
    .dexText "enemies while the other one sleeps."
    .dexText ""

    .align 2, 0
dexEntry93::
    .2byte 0, 8, 5, 0xA, 5, 1, 1, 0xA, 1, 8, 7, 8
    .dexName "DODRIO"
    .dexCategory "TRIPLE BIRD"
    .dexText "Watch out if DODRIO`s three heads are"
    .dexText "looking in three separate directions."
    .dexText "It`s a sure sign that it is on its guard."
    .dexText "Don`t go near this POKéMON if it`s being"
    .dexText "wary - it may decide to peck you."
    .dexText ""

    .align 2, 0
dexEntry94::
    .2byte 3, 1, 5, 0xA, 1, 0, 0, 0xA, 0xA, 0xA, 4, 4
    .dexName "ROSELIA"
    .dexCategory "THORN"
    .dexText "On extremely rare occasions, a ROSELIA"
    .dexText "is said to appear with its flowers in"
    .dexText "unusual colors."
    .dexText "The thorns on this POKéMON`s head"
    .dexText "contain a vicious poison."
    .dexText ""

    .align 2, 0
dexEntry95::
    .2byte 3, 1, 6, 0xA, 1, 0, 4, 0xA, 0xA, 2, 2, 7
    .dexName "GULPIN"
    .dexCategory "STOMACH"
    .dexText "Most of GULPIN`s body is made up of its"
    .dexText "stomach - its heart and brain are very"
    .dexText "small in comparison."
    .dexText "This POKéMON`s stomach contains"
    .dexText "special enzymes that dissolve anything."
    .dexText ""

    .align 2, 0
dexEntry96::
    .2byte 3, 1, 7, 0xA, 5, 0, 7, 0xA, 1, 7, 6, 4
    .dexName "SWALOT"
    .dexCategory "POISON BAG"
    .dexText "SWALOT has no teeth, so what it"
    .dexText "eats, it swallows whole, no matter what."
    .dexText "Its cavernous mouth yawns widely."
    .dexText "An automobile tire could easily fit"
    .dexText "inside this POKéMON`s mouth."
    .dexText ""

    .align 2, 0
dexEntry97::
    .2byte 3, 1, 8, 0xA, 2, 0, 7, 0xA, 0xA, 4, 5, 9
    .dexName "CARVANHA"
    .dexCategory "SAVAGE"
    .dexText "CARVANHA`s strongly developed jaws"
    .dexText "and its sharply pointed fangs pack the"
    .dexText "destructive power to rip out boat hulls."
    .dexText "Many boats have been attacked and"
    .dexText "sunk by this POKéMON."
    .dexText ""

    .align 2, 0
dexEntry98::
    .2byte 3, 1, 9, 0xA, 5, 1, 1, 0xA, 1, 9, 5, 8
    .dexName "SHARPEDO"
    .dexCategory "BRUTAL"
    .dexText "Nicknamed “the bully of the sea,”"
    .dexText "SHARPEDO is widely feared."
    .dexText "Its cruel fangs grow back immediately"
    .dexText "if they snap off."
    .dexText "Just one of these POKéMON can"
    .dexText "thoroughly tear apart a supertanker."

    .align 2, 0
dexEntry99::
    .2byte 3, 2, 0, 0xA, 6, 0, 7, 0xA, 2, 8, 6, 6
    .dexName "WAILMER"
    .dexCategory "BALL WHALE"
    .dexText "WAILMER`s nostrils are located above"
    .dexText "its eyes. This playful POKéMON loves"
    .dexText "to startle people by forcefully snorting"
    .dexText "out seawater it stores inside its body"
    .dexText "out of its nostrils."
    .dexText ""

    .align 2, 0
dexEntry100::
    .2byte 3, 2, 1, 4, 7, 0, 7, 0xA, 8, 7, 7, 4
    .dexName "WAILORD"
    .dexCategory "FLOAT WHALE"
    .dexText "WAILORD is the largest of all identified"
    .dexText "POKéMON up to now."
    .dexText "This giant POKéMON swims languorously"
    .dexText "in the vast open sea, eating massive"
    .dexText "amounts of food at once with its"
    .dexText "enormous mouth."

    .align 2, 0
dexEntry101::
    .2byte 3, 2, 2, 0xA, 2, 0, 4, 0xA, 0xA, 5, 2, 9
    .dexName "NUMEL"
    .dexCategory "NUMB"
    .dexText "NUMEL is extremely dull witted - it"
    .dexText "doesn`t notice being hit. However, it"
    .dexText "can`t stand hunger for even a second."
    .dexText "This POKéMON`s body is a seething"
    .dexText "cauldron of boiling magma."
    .dexText ""

    .align 2, 0
dexEntry102::
    .2byte 3, 2, 3, 0xA, 6, 0, 3, 0xA, 4, 8, 5, 0
    .dexName "CAMERUPT"
    .dexCategory "ERUPTION"
    .dexText "CAMERUPT has a volcano inside its body."
    .dexText "Magma of 18,000 degrees F courses"
    .dexText "through its body."
    .dexText "Occasionally, the humps on this"
    .dexText "POKéMON`s back erupt, spewing the"
    .dexText "superheated magma."

    .align 2, 0
dexEntry103::
    .2byte 2, 1, 8, 0xA, 2, 0, 4, 0xA, 0xA, 7, 7, 2
    .dexName "SLUGMA"
    .dexCategory "LAVA"
    .dexText "Molten magma courses throughout"
    .dexText "SLUGMA`s circulatory system."
    .dexText "If this POKéMON is chilled, the magma"
    .dexText "cools and hardens. Its body turns"
    .dexText "brittle and chunks fall off, reducing"
    .dexText "its size."

    .align 2, 0
dexEntry104::
    .2byte 2, 1, 9, 0xA, 2, 0, 7, 0xA, 1, 2, 1, 3
    .dexName "MAGCARGO"
    .dexCategory "LAVA"
    .dexText "MAGCARGO`s shell is actually its skin"
    .dexText "that hardened as a result of cooling."
    .dexText "Its shell is very brittle and fragile -"
    .dexText "just touching it causes it to crumble"
    .dexText "apart. This POKéMON returns to its"
    .dexText "original size by dipping itself in magma."

    .align 2, 0
dexEntry105::
    .2byte 3, 2, 4, 0xA, 1, 0, 8, 0xA, 1, 7, 7, 2
    .dexName "TORKOAL"
    .dexCategory "COAL"
    .dexText "TORKOAL digs through mountains in"
    .dexText "search of coal. If it finds some, it fills"
    .dexText "hollow spaces on its shell with the coal"
    .dexText "and burns it."
    .dexText "If it is attacked, this POKéMON spouts"
    .dexText "thick black smoke to beat a retreat."

    .align 2, 0
dexEntry106::
    .2byte 0, 8, 8, 0xA, 2, 1, 1, 0xA, 0xA, 6, 6, 1
    .dexName "GRIMER"
    .dexCategory "SLUDGE"
    .dexText "GRIMER emerged from the sludge that"
    .dexText "settled on a polluted seabed."
    .dexText "This POKéMON loves anything filthy."
    .dexText "It constantly leaks a horribly germ-"
    .dexText "infested fluid from all over its body."
    .dexText ""

    .align 2, 0
dexEntry107::
    .2byte 0, 8, 9, 0xA, 3, 1, 1, 0xA, 0xA, 6, 6, 1
    .dexName "MUK"
    .dexCategory "SLUDGE"
    .dexText "This POKéMON`s favorite food is"
    .dexText "anything that is repugnantly filthy."
    .dexText "In dirty towns where people think"
    .dexText "nothing of throwing away litter on the"
    .dexText "streets, MUK are certain to gather."
    .dexText ""

    .align 2, 0
dexEntry108::
    .2byte 1, 0, 9, 0xA, 2, 0, 0, 0xA, 0xA, 0xA, 2, 2
    .dexName "KOFFING"
    .dexCategory "POISON GAS"
    .dexText "If KOFFING becomes agitated, it raises"
    .dexText "the toxicity of its internal gases and"
    .dexText "jets them out from all over its body."
    .dexText "This POKéMON may also overinflate its"
    .dexText "round body, then explode."
    .dexText ""

    .align 2, 0
dexEntry109::
    .2byte 1, 1, 0, 0xA, 3, 1, 1, 0xA, 0xA, 2, 0, 9
    .dexName "WEEZING"
    .dexCategory "POISON GAS"
    .dexText "WEEZING loves the gases given off by"
    .dexText "rotted kitchen garbage. This POKéMON"
    .dexText "will find a dirty, unkempt house and"
    .dexText "make it its home. At night, when the"
    .dexText "people in the house are asleep, it will"
    .dexText "go through the trash."

    .align 2, 0
dexEntry110::
    .2byte 3, 2, 5, 0xA, 2, 0, 4, 0xA, 0xA, 6, 7, 5
    .dexName "SPOINK"
    .dexCategory "BOUNCE"
    .dexText "SPOINK bounces around on its tail."
    .dexText "The shock of its bouncing makes its"
    .dexText "heart pump. As a result, this POKéMON"
    .dexText "cannot afford to stop bouncing - if it"
    .dexText "stops, its heart will stop."
    .dexText ""

    .align 2, 0
dexEntry111::
    .2byte 3, 2, 6, 0xA, 2, 1, 1, 0xA, 1, 5, 7, 6
    .dexName "GRUMPIG"
    .dexCategory "MANIPULATE"
    .dexText "GRUMPIG uses the black pearls on its"
    .dexText "body to amplify its psychic power waves"
    .dexText "for gaining total control over its foe."
    .dexText "When this POKéMON uses its special"
    .dexText "power, its snorting breath grows"
    .dexText "labored."

    .align 2, 0
dexEntry112::
    .2byte 0, 2, 7, 0xA, 2, 0, 0, 0xA, 0xA, 2, 6, 5
    .dexName "SANDSHREW"
    .dexCategory "MOUSE"
    .dexText "SANDSHREW has a very dry hide that is"
    .dexText "extremely tough. The POKéMON can roll"
    .dexText "into a ball that repels any attack."
    .dexText "At night, it burrows into the desert"
    .dexText "sand to sleep."
    .dexText ""

    .align 2, 0
dexEntry113::
    .2byte 0, 2, 8, 0xA, 3, 0, 3, 0xA, 0xA, 6, 5, 0
    .dexName "SANDSLASH"
    .dexCategory "MOUSE"
    .dexText "SANDSLASH can roll up its body as if it"
    .dexText "were a ball covered with large spikes."
    .dexText "In battle, this POKéMON will try to make"
    .dexText "the foe flinch by jabbing it with its"
    .dexText "spines. It then leaps at the stunned"
    .dexText "foe to tear wildly with its sharp claws."

    .align 2, 0
dexEntry114::
    .2byte 3, 2, 7, 0xA, 3, 0, 7, 0xA, 0xA, 1, 1, 0
    .dexName "SPINDA"
    .dexCategory "SPOT PANDA"
    .dexText "All the SPINDA that exist in the"
    .dexText "world are said to have utterly unique"
    .dexText "spot patterns."
    .dexText "The shaky, tottering steps of this"
    .dexText "POKéMON give it the appearance of"
    .dexText "dancing."

    .align 2, 0
dexEntry115::
    .2byte 2, 2, 7, 0xA, 5, 0, 7, 0xA, 1, 1, 1, 3
    .dexName "SKARMORY"
    .dexCategory "ARMOR BIRD"
    .dexText "SKARMORY is entirely encased in hard,"
    .dexText "protective armor. This POKéMON flies at"
    .dexText "close to 190 mph."
    .dexText "It slashes foes with its wings that"
    .dexText "possess swordlike cutting edges."
    .dexText ""

    .align 2, 0
dexEntry116::
    .2byte 3, 2, 8, 0xA, 2, 0, 4, 0xA, 0xA, 3, 3, 1
    .dexName "TRAPINCH"
    .dexCategory "ANT PIT"
    .dexText "TRAPINCH is a patient hunter. It digs"
    .dexText "an inescapable pit in a desert and waits"
    .dexText "for its prey to come tumbling down."
    .dexText "This POKéMON can go a whole week"
    .dexText "without access to any water."
    .dexText ""

    .align 2, 0
dexEntry117::
    .2byte 3, 2, 9, 0xA, 3, 0, 7, 0xA, 0xA, 3, 3, 7
    .dexName "VIBRAVA"
    .dexCategory "VIBRATION"
    .dexText "VIBRAVA`s wings have not yet"
    .dexText "completed the process of growing."
    .dexText "Rather than flying long distances,"
    .dexText "they are more useful for generating"
    .dexText "ultrasonic waves by vibrating."
    .dexText ""

    .align 2, 0
dexEntry118::
    .2byte 3, 3, 0, 0xA, 6, 0, 7, 0xA, 1, 8, 0, 8
    .dexName "FLYGON"
    .dexCategory "MYSTIC"
    .dexText "FLYGON whips up a sandstorm by"
    .dexText "flapping its wings. The wings create a"
    .dexText "series of notes that sound like singing."
    .dexText "Because the “singing” is the only thing"
    .dexText "that can be heard in a sandstorm, this"
    .dexText "POKéMON is said to be the desert spirit."

    .align 2, 0
dexEntry119::
    .2byte 3, 3, 1, 0xA, 1, 0, 4, 0xA, 1, 1, 3, 1
    .dexName "CACNEA"
    .dexCategory "CACTUS"
    .dexText "The more arid and harsh the"
    .dexText "environment, the more pretty and"
    .dexText "fragrant a flower CACNEA grows."
    .dexText "This POKéMON battles by wildly swinging"
    .dexText "its thorny arms."
    .dexText ""

    .align 2, 0
dexEntry120::
    .2byte 3, 3, 2, 0xA, 4, 0, 3, 0xA, 1, 7, 0, 6
    .dexName "CACTURNE"
    .dexCategory "SCARECROW"
    .dexText "If a traveler is going through a desert"
    .dexText "in the thick of night, CACTURNE"
    .dexText "will follow in a ragtag group."
    .dexText "The POKéMON are biding their time,"
    .dexText "waiting for the traveler to tire and"
    .dexText "become incapable of moving."

    .align 2, 0
dexEntry121::
    .2byte 3, 3, 3, 0xA, 1, 0, 4, 0xA, 0xA, 0xA, 2, 6
    .dexName "SWABLU"
    .dexCategory "COTTON BIRD"
    .dexText "SWABLU loves to make things clean."
    .dexText "If it spots something dirty, it will wipe"
    .dexText "and polish it with its cottony wings."
    .dexText "If its wings become dirty, this POKéMON"
    .dexText "finds a stream and showers itself."
    .dexText ""

    .align 2, 0
dexEntry122::
    .2byte 3, 3, 4, 0xA, 3, 0, 7, 0xA, 0xA, 4, 5, 4
    .dexName "ALTARIA"
    .dexCategory "HUMMING"
    .dexText "ALTARIA sings in a gorgeous soprano."
    .dexText "Its wings are like cotton clouds."
    .dexText "This POKéMON catches updrafts with its"
    .dexText "buoyant wings and soars way up into"
    .dexText "the wild blue yonder."
    .dexText ""

    .align 2, 0
dexEntry123::
    .2byte 3, 3, 5, 0xA, 4, 0, 3, 0xA, 0xA, 8, 8, 8
    .dexName "ZANGOOSE"
    .dexCategory "CAT FERRET"
    .dexText "Memories of battling its arch-rival"
    .dexText "SEVIPER are etched into every cell of"
    .dexText "ZANGOOSE`s body."
    .dexText "This POKéMON adroitly dodges attacks"
    .dexText "with incredible agility."
    .dexText ""

    .align 2, 0
dexEntry124::
    .2byte 3, 3, 6, 0xA, 8, 1, 0, 0xA, 1, 1, 5, 7
    .dexName "SEVIPER"
    .dexCategory "FANG SNAKE"
    .dexText "SEVIPER`s swordlike tail serves two"
    .dexText "purposes - it slashes foes and douses"
    .dexText "them with secreted poison."
    .dexText "This POKéMON will not give up its long-"
    .dexText "running blood feud with ZANGOOSE."
    .dexText ""

    .align 2, 0
dexEntry125::
    .2byte 3, 3, 7, 0xA, 3, 0, 3, 0xA, 3, 7, 0, 4
    .dexName "LUNATONE"
    .dexCategory "METEORITE"
    .dexText "LUNATONE becomes active around the"
    .dexText "time of the full moon. Instead of"
    .dexText "walking, it moves by floating in midair."
    .dexText "The POKéMON`s intimidating red eyes"
    .dexText "cause all those who see it to become"
    .dexText "transfixed with fear."

    .align 2, 0
dexEntry126::
    .2byte 3, 3, 8, 0xA, 3, 1, 1, 0xA, 3, 3, 9, 5
    .dexName "SOLROCK"
    .dexCategory "METEORITE"
    .dexText "SOLROCK is a new species of POKéMON"
    .dexText "that is said to have fallen from space."
    .dexText "It floats in air and moves silently."
    .dexText "In battle, this POKéMON releases"
    .dexText "intensely bright light."
    .dexText ""

    .align 2, 0
dexEntry127::
    .2byte 3, 3, 9, 0xA, 1, 0, 4, 0xA, 0xA, 0xA, 4, 2
    .dexName "BARBOACH"
    .dexCategory "WHISKERS"
    .dexText "BARBOACH`s body is covered with a"
    .dexText "slimy film. If a foe grabs it, this"
    .dexText "POKéMON just slips out of the enemy`s"
    .dexText "grip."
    .dexText "This POKéMON grows weak if the slimy"
    .dexText "coating dries up."

    .align 2, 0
dexEntry128::
    .2byte 3, 4, 0, 0xA, 2, 1, 1, 0xA, 0xA, 5, 2, 0
    .dexName "WHISCASH"
    .dexCategory "WHISKERS"
    .dexText "If WHISCASH goes on a wild rampage,"
    .dexText "it sets off a quake-like tremor with a"
    .dexText "radius of over three miles."
    .dexText "This POKéMON has the ability to predict"
    .dexText "real earthquakes."
    .dexText ""

    .align 2, 0
dexEntry129::
    .2byte 3, 4, 1, 0xA, 2, 0, 0, 0xA, 0xA, 2, 5, 4
    .dexName "CORPHISH"
    .dexCategory "RUFFIAN"
    .dexText "CORPHISH catches prey with its sharp"
    .dexText "claws. It has no likes or dislikes when it"
    .dexText "comes to food - it will eat anything."
    .dexText "This POKéMON has no trouble living in"
    .dexText "filthy water."
    .dexText ""

    .align 2, 0
dexEntry130::
    .2byte 3, 4, 2, 0xA, 3, 0, 7, 0xA, 0xA, 7, 2, 3
    .dexName "CRAWDAUNT"
    .dexCategory "ROGUE"
    .dexText "CRAWDAUNT molts (sheds) its shell"
    .dexText "regularly. Immediately after molting,"
    .dexText "its shell is soft and tender."
    .dexText "Until the shell hardens, this POKéMON"
    .dexText "hides in its streambed burrow to avoid"
    .dexText "attack from its foes."

    .align 2, 0
dexEntry131::
    .2byte 3, 4, 3, 0xA, 1, 0, 8, 0xA, 0xA, 4, 7, 4
    .dexName "BALTOY"
    .dexCategory "CLAY DOLL"
    .dexText "As soon as it spots others of its kind,"
    .dexText "BALTOY congregates with them and"
    .dexText "then begins crying noisily in unison."
    .dexText "This POKéMON sleeps while cleverly"
    .dexText "balancing itself on its one foot."
    .dexText ""

    .align 2, 0
dexEntry132::
    .2byte 3, 4, 4, 0xA, 4, 1, 1, 0xA, 2, 3, 8, 1
    .dexName "CLAYDOL"
    .dexCategory "CLAY DOLL"
    .dexText "CLAYDOL is an enigma that appeared"
    .dexText "from a clay statue made by an ancient"
    .dexText "civilization dating back 20,000 years."
    .dexText "This POKéMON shoots beams from both"
    .dexText "its hands."
    .dexText ""

    .align 2, 0
dexEntry133::
    .2byte 3, 4, 5, 0xA, 3, 0, 3, 0xA, 0xA, 5, 2, 5
    .dexName "LILEEP"
    .dexCategory "SEA LILY"
    .dexText "LILEEP became extinct approximately"
    .dexText "a hundred million years ago."
    .dexText "This ancient POKéMON attaches itself"
    .dexText "to a rock on the seafloor and catches"
    .dexText "approaching prey using tentacles"
    .dexText "shaped like flower petals."

    .align 2, 0
dexEntry134::
    .2byte 3, 4, 6, 0xA, 4, 1, 1, 0xA, 1, 3, 3, 2
    .dexName "CRADILY"
    .dexCategory "BARNACLE"
    .dexText "CRADILY roams around the ocean floor"
    .dexText "in search of food. This POKéMON freely"
    .dexText "extends its tree trunk-like neck and"
    .dexText "captures unwary prey using its eight"
    .dexText "tentacles."
    .dexText ""

    .align 2, 0
dexEntry135::
    .2byte 3, 4, 7, 0xA, 2, 0, 4, 0xA, 0xA, 2, 7, 6
    .dexName "ANORITH"
    .dexCategory "OLD SHRIMP"
    .dexText "ANORITH is said to be a type of"
    .dexText "POKéMON predecessor, with eight wings"
    .dexText "at the sides of its body."
    .dexText "This POKéMON swam in the primordial sea"
    .dexText "by undulating these eight wings."
    .dexText ""

    .align 2, 0
dexEntry136::
    .2byte 3, 4, 8, 0xA, 4, 1, 1, 0xA, 1, 5, 0, 4
    .dexName "ARMALDO"
    .dexCategory "PLATE"
    .dexText "ARMALDO is a POKéMON species that"
    .dexText "became extinct in prehistoric times."
    .dexText "This POKéMON is said to have walked on"
    .dexText "its hind legs, which would have been"
    .dexText "more convenient for life on land."
    .dexText ""

    .align 2, 0
dexEntry137::
    .2byte 1, 7, 4, 0xA, 1, 0, 0, 0xA, 0xA, 0xA, 2, 2
    .dexName "IGGLYBUFF"
    .dexCategory "BALLOON"
    .dexText "IGGLYBUFF has a soft and plushy body"
    .dexText "that feels very much like a marshmallow."
    .dexText "From this body wafts a gently sweet"
    .dexText "fragrance that soothes and calms the"
    .dexText "emotions of its foes."
    .dexText ""

    .align 2, 0
dexEntry138::
    .2byte 0, 3, 9, 0xA, 1, 0, 8, 0xA, 0xA, 1, 2, 1
    .dexName "JIGGLYPUFF"
    .dexCategory "BALLOON"
    .dexText "When this POKéMON sings, it never"
    .dexText "pauses to breathe. If it is in a battle"
    .dexText "against an opponent that does not"
    .dexText "easily fall asleep, JIGGLYPUFF cannot"
    .dexText "breathe, endangering its life."
    .dexText ""

    .align 2, 0
dexEntry139::
    .2byte 0, 4, 0, 0xA, 3, 0, 3, 0xA, 0xA, 2, 6, 5
    .dexName "WIGGLYTUFF"
    .dexCategory "BALLOON"
    .dexText "WIGGLYTUFF`s body is very flexible."
    .dexText "By inhaling deeply, this POKéMON can"
    .dexText "inflate itself seemingly without end."
    .dexText "Once inflated, WIGGLYTUFF bounces"
    .dexText "along lightly like a balloon."
    .dexText ""

    .align 2, 0
dexEntry140::
    .2byte 3, 4, 9, 0xA, 2, 0, 0, 0xA, 0xA, 1, 6, 3
    .dexName "FEEBAS"
    .dexCategory "FISH"
    .dexText "While FEEBAS`s body is in tatters,"
    .dexText "it has a hardy and tenacious life force"
    .dexText "that enables it to live anywhere."
    .dexText "However, this POKéMON is also slow and"
    .dexText "dimwitted, making it an easy catch."
    .dexText ""

    .align 2, 0
dexEntry141::
    .2byte 3, 5, 0, 2, 0, 0, 4, 0xA, 3, 5, 7, 1
    .dexName "MILOTIC"
    .dexCategory "TENDER"
    .dexText "MILOTIC live at the bottom of large"
    .dexText "lakes. When this POKéMON`s body glows a"
    .dexText "vivid pink, it releases a pulsing wave of"
    .dexText "energy that brings soothing calm to"
    .dexText "restless spirits."
    .dexText ""

    .align 2, 0
dexEntry142::
    .2byte 3, 5, 1, 0xA, 1, 0, 0, 0xA, 0xA, 0xA, 1, 8
    .dexName "CASTFORM"
    .dexCategory "WEATHER"
    .dexText "CASTFORM borrows the power of nature"
    .dexText "to transform itself into the guises of"
    .dexText "the sun, rain clouds, and snow clouds."
    .dexText "This POKéMON`s feelings change with the"
    .dexText "weather."
    .dexText ""

    .align 2, 0
dexEntry143::
    .2byte 1, 2, 0, 0xA, 2, 0, 7, 0xA, 0xA, 7, 6, 1
    .dexName "STARYU"
    .dexCategory "STAR SHAPE"
    .dexText "STARYU`s center section has an organ"
    .dexText "called the core that shines bright red."
    .dexText "If you go to a beach toward the"
    .dexText "end of summer, the glowing cores of"
    .dexText "these POKéMON look like the stars"
    .dexText "in the sky."

    .align 2, 0
dexEntry144::
    .2byte 1, 2, 1, 0xA, 3, 0, 7, 0xA, 1, 7, 6, 4
    .dexName "STARMIE"
    .dexCategory "MYSTERIOUS"
    .dexText "STARMIE`s center section - the core -"
    .dexText "glows brightly in seven colors."
    .dexText "Because of its luminous nature, this"
    .dexText "POKéMON has been given the nickname"
    .dexText "“the gem of the sea.”"
    .dexText ""

    .align 2, 0
dexEntry145::
    .2byte 3, 5, 2, 0xA, 3, 0, 3, 0xA, 0xA, 4, 8, 5
    .dexName "KECLEON"
    .dexCategory "COLOR SWAP"
    .dexText "KECLEON alters its body coloration to"
    .dexText "blend in with its surroundings, allowing"
    .dexText "it to sneak up on its prey unnoticed."
    .dexText "Then it lashes out with its long,"
    .dexText "stretchy tongue to instantly ensnare"
    .dexText "the unsuspecting target."

    .align 2, 0
dexEntry146::
    .2byte 3, 5, 3, 0xA, 2, 0, 0, 0xA, 0xA, 0xA, 5, 1
    .dexName "SHUPPET"
    .dexCategory "PUPPET"
    .dexText "SHUPPET is attracted by feelings"
    .dexText "of jealousy and vindictiveness."
    .dexText "If someone develops strong feelings of"
    .dexText "vengeance, this POKéMON will appear"
    .dexText "in a swarm and line up beneath the eaves"
    .dexText "of that person`s home."

    .align 2, 0
dexEntry147::
    .2byte 3, 5, 4, 0xA, 3, 0, 7, 0xA, 0xA, 2, 7, 6
    .dexName "BANETTE"
    .dexCategory "MARIONETTE"
    .dexText "BANETTE generates energy for laying"
    .dexText "strong curses by sticking pins into its"
    .dexText "own body."
    .dexText "This POKéMON was originally a pitiful"
    .dexText "plush doll that was thrown away."
    .dexText ""

    .align 2, 0
dexEntry148::
    .2byte 3, 5, 5, 0xA, 2, 0, 7, 0xA, 0xA, 3, 3, 1
    .dexName "DUSKULL"
    .dexCategory "REQUIEM"
    .dexText "DUSKULL wanders lost among the deep"
    .dexText "darkness of midnight. There is an oft-"
    .dexText "told admonishment given to misbehaving"
    .dexText "children that this POKéMON will spirit"
    .dexText "away bad children who earn scoldings"
    .dexText "from their mothers."

    .align 2, 0
dexEntry149::
    .2byte 3, 5, 6, 0xA, 5, 0, 3, 0xA, 0xA, 6, 7, 5
    .dexName "DUSCLOPS"
    .dexCategory "BECKON"
    .dexText "DUSCLOPS absorbs anything, however"
    .dexText "large the object may be. This POKéMON"
    .dexText "hypnotizes its foe by waving its hands"
    .dexText "in a macabre manner and by bringing its"
    .dexText "single eye to bear. The hypnotized foe"
    .dexText "is made to do DUSCLOPS`s bidding."

    .align 2, 0
dexEntry150::
    .2byte 3, 5, 7, 0xA, 6, 0, 7, 0xA, 2, 2, 0, 5
    .dexName "TROPIUS"
    .dexCategory "FRUIT"
    .dexText "Children of the southern tropics eat"
    .dexText "as snacks the fruit that grows in"
    .dexText "bunches around the neck of TROPIUS."
    .dexText "This POKéMON flies by flapping the"
    .dexText "leaves on its back as if they were"
    .dexText "wings."

    .align 2, 0
dexEntry151::
    .2byte 3, 5, 8, 0xA, 2, 0, 0, 0xA, 0xA, 0xA, 2, 2
    .dexName "CHIMECHO"
    .dexCategory "WIND CHIME"
    .dexText "In high winds, CHIMECHO cries as it"
    .dexText "hangs from a tree branch or the eaves"
    .dexText "of a building using a suction cup on its"
    .dexText "head."
    .dexText "This POKéMON plucks berries with its"
    .dexText "long tail and eats them."

    .align 2, 0
dexEntry152::
    .2byte 3, 5, 9, 0xA, 3, 1, 1, 0xA, 1, 0, 3, 6
    .dexName "ABSOL"
    .dexCategory "DISASTER"
    .dexText "ABSOL has the ability to foretell the"
    .dexText "coming of natural disasters."
    .dexText "It lives in a harsh, rugged mountain"
    .dexText "environment. This POKéMON very rarely"
    .dexText "ventures down from the mountains."
    .dexText ""

    .align 2, 0
dexEntry153::
    .2byte 0, 3, 7, 0xA, 2, 0, 0, 0xA, 0xA, 2, 1, 8
    .dexName "VULPIX"
    .dexCategory "FOX"
    .dexText "At the time of its birth, VULPIX has one"
    .dexText "white tail. The tail separates into six"
    .dexText "if this POKéMON receives plenty of love"
    .dexText "from its TRAINER."
    .dexText "The six tails become magnificently"
    .dexText "curled."

    .align 2, 0
dexEntry154::
    .2byte 0, 3, 8, 0xA, 3, 0, 7, 0xA, 0xA, 4, 3, 9
    .dexName "NINETALES"
    .dexCategory "FOX"
    .dexText "NINETALES casts a sinister light from"
    .dexText "its bright red eyes to gain total"
    .dexText "control over its foe`s mind."
    .dexText "This POKéMON is said to live for a"
    .dexText "thousand years."
    .dexText ""

    .align 2, 0
dexEntry155::
    .2byte 1, 7, 2, 0xA, 1, 0, 0, 0xA, 0xA, 0xA, 4, 4
    .dexName "PICHU"
    .dexCategory "TINY MOUSE"
    .dexText "PICHU charges itself with electricity"
    .dexText "more easily on days with thunderclouds"
    .dexText "or when the air is very dry."
    .dexText "You can hear the crackling of static"
    .dexText "electricity coming off this POKéMON."
    .dexText ""

    .align 2, 0
dexEntry156::
    .2byte 0, 2, 5, 0xA, 1, 0, 4, 0xA, 0xA, 1, 3, 2
    .dexName "PIKACHU"
    .dexCategory "MOUSE"
    .dexText "Whenever PIKACHU comes across"
    .dexText "something new, it blasts it with a jolt"
    .dexText "of electricity."
    .dexText "If you come across a blackened berry,"
    .dexText "it`s evidence that this POKéMON"
    .dexText "mistook the intensity of its charge."

    .align 2, 0
dexEntry157::
    .2byte 0, 2, 6, 0xA, 2, 0, 7, 0xA, 0xA, 6, 6, 1
    .dexName "RAICHU"
    .dexCategory "MOUSE"
    .dexText "If the electrical sacks become"
    .dexText "excessively charged, RAICHU plants its"
    .dexText "tail in the ground and discharges."
    .dexText "Scorched patches of ground will be"
    .dexText "found near this POKéMON`s nest."
    .dexText ""

    .align 2, 0
dexEntry158::
    .2byte 0, 5, 4, 0xA, 2, 0, 7, 0xA, 0xA, 4, 3, 2
    .dexName "PSYDUCK"
    .dexCategory "DUCK"
    .dexText "PSYDUCK uses a mysterious power."
    .dexText "When it does so, this POKéMON"
    .dexText "generates brain waves that are"
    .dexText "supposedly only seen in sleepers."
    .dexText "This discovery spurred controversy"
    .dexText "among scholars."

    .align 2, 0
dexEntry159::
    .2byte 0, 5, 5, 0xA, 5, 0, 7, 0xA, 1, 6, 8, 9
    .dexName "GOLDUCK"
    .dexCategory "DUCK"
    .dexText "The webbed flippers on its forelegs and"
    .dexText "hind legs and the streamlined body of"
    .dexText "GOLDUCK give it frightening speed."
    .dexText "This POKéMON is definitely much faster"
    .dexText "than even the most athletic swimmer."
    .dexText ""

    .align 2, 0
dexEntry160::
    .2byte 3, 6, 0, 0xA, 2, 0, 0, 0xA, 0xA, 3, 0, 9
    .dexName "WYNAUT"
    .dexCategory "BRIGHT"
    .dexText "WYNAUT can always be seen with a big,"
    .dexText "happy smile on its face. Look at its tail"
    .dexText "to determine if it is angry."
    .dexText "When angered, this POKéMON will be"
    .dexText "slapping the ground with its tail."
    .dexText ""

    .align 2, 0
dexEntry161::
    .2byte 2, 0, 2, 0xA, 4, 0, 3, 0xA, 0xA, 6, 2, 8
    .dexName "WOBBUFFET"
    .dexCategory "PATIENT"
    .dexText "If two or more WOBBUFFET meet, they will"
    .dexText "turn competitive and try to outdo each"
    .dexText "other`s endurance."
    .dexText "However, they may try to see which one"
    .dexText "can endure the longest without food."
    .dexText "TRAINERS need to beware of this habit."

    .align 2, 0
dexEntry162::
    .2byte 1, 7, 7, 0xA, 0, 0, 8, 0xA, 0xA, 0xA, 4, 4
    .dexName "NATU"
    .dexCategory "TINY BIRD"
    .dexText "NATU cannot fly because its wings are"
    .dexText "not yet fully grown. If your eyes meet"
    .dexText "with this POKéMON`s eyes, it will stare"
    .dexText "back intently at you. But if you move"
    .dexText "even slightly, it will hop away to safety."
    .dexText ""

    .align 2, 0
dexEntry163::
    .2byte 1, 7, 8, 0xA, 4, 1, 1, 0xA, 0xA, 3, 3, 1
    .dexName "XATU"
    .dexCategory "MYSTIC"
    .dexText "XATU stands rooted and still in one"
    .dexText "spot all day long. People believe that"
    .dexText "this POKéMON does so out of fear of"
    .dexText "the terrible things it has foreseen in"
    .dexText "the future."
    .dexText ""

    .align 2, 0
dexEntry164::
    .2byte 2, 0, 3, 0xA, 4, 1, 1, 0xA, 0xA, 9, 1, 5
    .dexName "GIRAFARIG"
    .dexCategory "LONG NECK"
    .dexText "GIRAFARIG`s rear head also has a brain,"
    .dexText "but it is small. The rear head attacks in"
    .dexText "response to smells and sounds."
    .dexText "Approaching this POKéMON from behind"
    .dexText "can cause the rear head to suddenly"
    .dexText "lash out and bite."

    .align 2, 0
dexEntry165::
    .2byte 2, 3, 1, 0xA, 1, 0, 8, 0xA, 0xA, 7, 3, 9
    .dexName "PHANPY"
    .dexCategory "LONG NOSE"
    .dexText "PHANPY uses its long nose to shower"
    .dexText "itself. When others gather around, they"
    .dexText "thoroughly douse each other with"
    .dexText "water. These POKéMON can be seen"
    .dexText "drying their soaking-wet bodies at the"
    .dexText "edge of water."

    .align 2, 0
dexEntry166::
    .2byte 2, 3, 2, 0xA, 3, 0, 7, 0xA, 2, 6, 4, 6
    .dexName "DONPHAN"
    .dexCategory "ARMOR"
    .dexText "If DONPHAN were to tackle with its hard"
    .dexText "body, even a house could be destroyed."
    .dexText "Using its massive strength, the"
    .dexText "POKéMON helps clear rock and mud slides"
    .dexText "that block mountain trails."
    .dexText ""

    .align 2, 0
dexEntry167::
    .2byte 1, 2, 7, 0xA, 4, 1, 1, 0xA, 1, 2, 1, 3
    .dexName "PINSIR"
    .dexCategory "STAG BEETLE"
    .dexText "PINSIR is astoundingly strong. It can"
    .dexText "grip a foe weighing twice its weight"
    .dexText "in its horns and easily lift it."
    .dexText "This POKéMON`s movements turn sluggish"
    .dexText "in cold places."
    .dexText ""

    .align 2, 0
dexEntry168::
    .2byte 2, 1, 4, 0xA, 4, 1, 1, 0xA, 1, 1, 9, 0
    .dexName "HERACROSS"
    .dexCategory "SINGLE HORN"
    .dexText "HERACROSS charges in a straight line at"
    .dexText "its foe, slips beneath the foe`s grasp,"
    .dexText "and then scoops up and hurls the"
    .dexText "opponent with its mighty horn."
    .dexText "This POKéMON even has enough power"
    .dexText "to topple a massive tree."

    .align 2, 0
dexEntry169::
    .2byte 1, 1, 1, 0xA, 3, 0, 3, 0xA, 2, 5, 3, 5
    .dexName "RHYHORN"
    .dexCategory "SPIKES"
    .dexText "RHYHORN runs in a straight line,"
    .dexText "smashing everything in its path."
    .dexText "It is not bothered even if it rushes"
    .dexText "headlong into a block of steel."
    .dexText "This POKéMON may feel some pain from"
    .dexText "the collision the next day, however."

    .align 2, 0
dexEntry170::
    .2byte 1, 1, 2, 0xA, 6, 0, 3, 0xA, 2, 6, 4, 6
    .dexName "RHYDON"
    .dexCategory "DRILL"
    .dexText "RHYDON`s horn can crush even uncut"
    .dexText "diamonds. One sweeping blow of its tail"
    .dexText "can topple a building."
    .dexText "This POKéMON`s hide is extremely tough."
    .dexText "Even direct cannon hits don`t leave"
    .dexText "a scratch."

    .align 2, 0
dexEntry171::
    .2byte 3, 6, 1, 0xA, 2, 0, 4, 0xA, 0xA, 3, 7, 0
    .dexName "SNORUNT"
    .dexCategory "SNOW HAT"
    .dexText "SNORUNT live in regions with heavy"
    .dexText "snowfall. In seasons without snow, such"
    .dexText "as spring and summer, this POKéMON"
    .dexText "steals away to live quietly among"
    .dexText "stalactites and stalagmites deep in"
    .dexText "caverns."

    .align 2, 0
dexEntry172::
    .2byte 3, 6, 2, 0xA, 4, 1, 1, 0xA, 5, 6, 5, 5
    .dexName "GLALIE"
    .dexCategory "FACE"
    .dexText "GLALIE has a body made of rock, which it"
    .dexText "hardens with an armor of ice."
    .dexText "This POKéMON has the ability to freeze"
    .dexText "moisture in the atmosphere into any"
    .dexText "shape it desires."
    .dexText ""

    .align 2, 0
dexEntry173::
    .2byte 3, 6, 3, 0xA, 2, 0, 7, 0xA, 0xA, 8, 7, 1
    .dexName "SPHEAL"
    .dexCategory "CLAP"
    .dexText "SPHEAL is much faster rolling than"
    .dexText "walking to get around. When groups of"
    .dexText "this POKéMON eat, they all clap at once"
    .dexText "to show their pleasure. Because of"
    .dexText "this, their mealtimes are noisy."
    .dexText ""

    .align 2, 0
dexEntry174::
    .2byte 3, 6, 4, 0xA, 3, 0, 7, 0xA, 1, 9, 3, 1
    .dexName "SEALEO"
    .dexCategory "BALL ROLL"
    .dexText "SEALEO has the habit of always juggling"
    .dexText "on the tip of its nose anything it sees"
    .dexText "for the first time."
    .dexText "This POKéMON occasionally entertains"
    .dexText "itself by balancing and rolling a SPHEAL"
    .dexText "on its nose."

    .align 2, 0
dexEntry175::
    .2byte 3, 6, 5, 0xA, 4, 0, 7, 0xA, 3, 3, 2, 0
    .dexName "WALREIN"
    .dexCategory "ICE BREAK"
    .dexText "WALREIN`s two massively developed"
    .dexText "tusks can totally shatter blocks of"
    .dexText "ice weighing ten tons with one blow."
    .dexText "This POKéMON`s thick coat of blubber"
    .dexText "insulates it from subzero temperatures."
    .dexText ""

    .align 2, 0
dexEntry176::
    .2byte 3, 6, 6, 0xA, 1, 0, 4, 0xA, 1, 1, 5, 7
    .dexName "CLAMPERL"
    .dexCategory "BIVALVE"
    .dexText "CLAMPERL grows while being protected"
    .dexText "by its rock-hard shell. When its body"
    .dexText "becomes too large to fit inside the"
    .dexText "shell, it is sure evidence that this"
    .dexText "POKéMON is getting close to evolution."
    .dexText ""

    .align 2, 0
dexEntry177::
    .2byte 3, 6, 7, 0xA, 5, 0, 7, 0xA, 0xA, 5, 9, 5
    .dexName "HUNTAIL"
    .dexCategory "DEEP SEA"
    .dexText "HUNTAIL`s tail is shaped like a fish."
    .dexText "It uses the tail to attract prey, then"
    .dexText "swallows the prey whole with its large,"
    .dexText "gaping mouth."
    .dexText "This POKéMON swims by wiggling its"
    .dexText "slender body like a snake."

    .align 2, 0
dexEntry178::
    .2byte 3, 6, 8, 0xA, 5, 1, 1, 0xA, 0xA, 4, 9, 8
    .dexName "GOREBYSS"
    .dexCategory "SOUTH SEA"
    .dexText "Although GOREBYSS is the very picture"
    .dexText "of elegance and beauty while swimming,"
    .dexText "it is also cruel. When it spots prey, this"
    .dexText "POKéMON inserts its thin mouth into the"
    .dexText "prey`s body and drains the prey of its"
    .dexText "body fluids."

    .align 2, 0
dexEntry179::
    .2byte 3, 6, 9, 0xA, 3, 0, 3, 0xA, 0xA, 5, 1, 6
    .dexName "RELICANTH"
    .dexCategory "LONGEVITY"
    .dexText "RELICANTH is a POKéMON species that"
    .dexText "existed for a hundred million years"
    .dexText "without ever changing its form."
    .dexText "This ancient POKéMON feeds on"
    .dexText "microscopic organisms with its"
    .dexText "toothless mouth."

    .align 2, 0
dexEntry180::
    .2byte 2, 2, 2, 0xA, 2, 0, 0, 0xA, 0xA, 1, 1, 0
    .dexName "CORSOLA"
    .dexCategory "CORAL"
    .dexText "Clusters of CORSOLA congregate in warm"
    .dexText "seas where they serve as ideal hiding"
    .dexText "places for smaller POKéMON."
    .dexText "When the water temperature falls, this"
    .dexText "POKéMON migrates to the southern seas."
    .dexText ""

    .align 2, 0
dexEntry181::
    .2byte 1, 7, 0, 0xA, 1, 0, 8, 0xA, 0xA, 2, 6, 5
    .dexName "CHINCHOU"
    .dexCategory "ANGLER"
    .dexText "CHINCHOU`s two antennas are filled with"
    .dexText "cells that generate strong electricity."
    .dexText "This POKéMON`s cells create so much"
    .dexText "electrical power, it even makes itself"
    .dexText "tingle slightly."
    .dexText ""

    .align 2, 0
dexEntry182::
    .2byte 1, 7, 1, 0xA, 3, 1, 1, 0xA, 0xA, 4, 9, 6
    .dexName "LANTURN"
    .dexCategory "LIGHT"
    .dexText "LANTURN is known to emit light."
    .dexText "If you peer down into the dark sea from"
    .dexText "a ship at night, you can sometimes see"
    .dexText "this POKéMON`s light rising from the"
    .dexText "depths where it swims. It gives the sea"
    .dexText "an appearance of a starlit night."

    .align 2, 0
dexEntry183::
    .2byte 3, 7, 0, 0xA, 2, 0, 0, 0xA, 0xA, 1, 9, 2
    .dexName "LUVDISC"
    .dexCategory "RENDEZVOUS"
    .dexText "LUVDISC live in shallow seas in the"
    .dexText "tropics. This heart-shaped POKéMON"
    .dexText "earned its name by swimming after"
    .dexText "loving couples it spotted in the"
    .dexText "ocean`s waves."
    .dexText ""

    .align 2, 0
dexEntry184::
    .2byte 1, 1, 6, 0xA, 1, 0, 4, 0xA, 0xA, 1, 7, 6
    .dexName "HORSEA"
    .dexCategory "DRAGON"
    .dexText "If HORSEA senses danger, it will"
    .dexText "reflexively spray a dense black ink"
    .dexText "from its mouth and try to escape."
    .dexText "This POKéMON swims by cleverly flapping"
    .dexText "the fins on its back."
    .dexText ""

    .align 2, 0
dexEntry185::
    .2byte 1, 1, 7, 0xA, 3, 1, 1, 0xA, 0xA, 5, 5, 1
    .dexName "SEADRA"
    .dexCategory "DRAGON"
    .dexText "SEADRA generates whirlpools by spinning"
    .dexText "its body. The whirlpools are strong"
    .dexText "enough to swallow even fishing boats."
    .dexText "This POKéMON weakens prey with these"
    .dexText "currents, then swallows it whole."
    .dexText ""

    .align 2, 0
dexEntry186::
    .2byte 2, 3, 0, 0xA, 5, 1, 1, 0xA, 3, 3, 5, 1
    .dexName "KINGDRA"
    .dexCategory "DRAGON"
    .dexText "KINGDRA sleeps on the seafloor where"
    .dexText "it is otherwise devoid of life."
    .dexText "When a storm arrives, the POKéMON is"
    .dexText "said to awaken and wander about in"
    .dexText "search of prey."
    .dexText ""

    .align 2, 0
dexEntry187::
    .2byte 3, 7, 1, 0xA, 2, 0, 0, 0xA, 0xA, 9, 2, 8
    .dexName "BAGON"
    .dexCategory "ROCK HEAD"
    .dexText "BAGON has a dream of one day soaring"
    .dexText "in the sky. In doomed efforts to fly,"
    .dexText "this POKéMON hurls itself off cliffs."
    .dexText "As a result of its dives, its head has"
    .dexText "grown tough and as hard as tempered"
    .dexText "steel."

    .align 2, 0
dexEntry188::
    .2byte 3, 7, 2, 0xA, 3, 0, 7, 0xA, 2, 4, 3, 6
    .dexName "SHELGON"
    .dexCategory "ENDURANCE"
    .dexText "Inside SHELGON`s armor-like shell, cells"
    .dexText "are in the midst of transformation"
    .dexText "to create an entirely new body."
    .dexText "This POKéMON`s shell is extremely heavy,"
    .dexText "making its movements sluggish."
    .dexText ""

    .align 2, 0
dexEntry189::
    .2byte 3, 7, 3, 0xA, 4, 1, 1, 0xA, 2, 2, 6, 2
    .dexName "SALAMENCE"
    .dexCategory "DRAGON"
    .dexText "SALAMENCE came about as a result of a"
    .dexText "strong, long-held dream of growing"
    .dexText "wings. It is said that this powerful"
    .dexText "desire triggered a sudden mutation in"
    .dexText "this POKéMON`s cells, causing it to"
    .dexText "sprout its magnificent wings."

    .align 2, 0
dexEntry190::
    .2byte 3, 7, 4, 0xA, 2, 0, 0, 0xA, 2, 0, 9, 9
    .dexName "BELDUM"
    .dexCategory "IRON BALL"
    .dexText "BELDUM keeps itself floating by"
    .dexText "generating a magnetic force that"
    .dexText "repels earth`s natural magnetism."
    .dexText "When it sleeps, this POKéMON anchors"
    .dexText "itself to a cliff using the hooks on"
    .dexText "its rear."

    .align 2, 0
dexEntry191::
    .2byte 3, 7, 5, 0xA, 3, 1, 1, 0xA, 4, 4, 6, 4
    .dexName "METANG"
    .dexCategory "IRON CLAW"
    .dexText "When two BELDUM fuse together, METANG"
    .dexText "is formed. The brains of the BELDUM are"
    .dexText "joined by a magnetic nervous system."
    .dexText "This POKéMON turns its arms to the rear"
    .dexText "for traveling at high speed."
    .dexText ""

    .align 2, 0
dexEntry192::
    .2byte 3, 7, 6, 0xA, 5, 0, 3, 1, 2, 1, 2, 5
    .dexName "METAGROSS"
    .dexCategory "IRON LEG"
    .dexText "METAGROSS is the result of two METANG"
    .dexText "achieving fusion. When hunting, this"
    .dexText "POKéMON pins the prey to the ground"
    .dexText "under its massive body. It then eats"
    .dexText "the helpless victim using the large"
    .dexText "mouth on its stomach."

    .align 2, 0
dexEntry193::
    .2byte 3, 7, 7, 0xA, 5, 0, 7, 0xA, 5, 0, 7, 1
    .dexName "REGIROCK"
    .dexCategory "ROCK PEAK"
    .dexText "REGIROCK was sealed away by people"
    .dexText "long ago. If this POKéMON`s body is"
    .dexText "damaged in battle, it is said to seek"
    .dexText "out suitable rocks on its own to repair"
    .dexText "itself."
    .dexText ""

    .align 2, 0
dexEntry194::
    .2byte 3, 7, 8, 0xA, 5, 1, 1, 0xA, 3, 8, 5, 8
    .dexName "REGICE"
    .dexCategory "ICEBERG"
    .dexText "REGICE cloaks itself with frigid air of"
    .dexText "negative 328 degrees F."
    .dexText "Things will freeze solid just by going"
    .dexText "near this POKéMON."
    .dexText "Its icy body is so cold, it will not melt"
    .dexText "even if it is immersed in magma."

    .align 2, 0
dexEntry195::
    .2byte 3, 7, 9, 0xA, 6, 0, 3, 0xA, 4, 5, 1, 9
    .dexName "REGISTEEL"
    .dexCategory "IRON"
    .dexText "REGISTEEL has a body that is harder"
    .dexText "than any kind of metal."
    .dexText "Its body is apparently hollow."
    .dexText "No one has any idea what this POKéMON"
    .dexText "eats."
    .dexText ""

    .align 2, 0
dexEntry196::
    .2byte 3, 8, 0, 0xA, 4, 0, 7, 0xA, 0xA, 8, 8, 2
    .dexName "LATIAS"
    .dexCategory "EON"
    .dexText "LATIAS is highly intelligent and capable"
    .dexText "of understanding human speech."
    .dexText "It is covered with a glass-like down."
    .dexText "The POKéMON enfolds its body with its"
    .dexText "down and refracts light to alter its"
    .dexText "appearance."

    .align 2, 0
dexEntry197::
    .2byte 3, 8, 1, 0xA, 6, 0, 7, 0xA, 1, 3, 2, 3
    .dexName "LATIOS"
    .dexCategory "EON"
    .dexText "LATIOS has the ability to make its foe"
    .dexText "see an image of what it has seen or"
    .dexText "imagines in its head."
    .dexText "This POKéMON is intelligent and"
    .dexText "understands human speech."
    .dexText ""

    .align 2, 0
dexEntry198::
    .2byte 3, 8, 2, 1, 4, 0, 9, 0xA, 7, 7, 6, 0
    .dexName "KYOGRE"
    .dexCategory "SEA BASIN"
    .dexText "KYOGRE is named in mythology as the"
    .dexText "POKéMON that expanded the sea by"
    .dexText "covering the land with torrential rains"
    .dexText "and towering tidal waves."
    .dexText "It took to sleep after a cataclysmic"
    .dexText "battle with GROUDON."

    .align 2, 0
dexEntry199::
    .2byte 3, 8, 3, 1, 1, 0, 6, 2, 0, 9, 4, 4
    .dexName "GROUDON"
    .dexCategory "CONTINENT"
    .dexText "GROUDON has long been described in"
    .dexText "mythology as the POKéMON that raised"
    .dexText "lands and expanded continents."
    .dexText "This POKéMON took to sleep after a"
    .dexText "cataclysmic battle with KYOGRE."
    .dexText ""

    .align 2, 0
dexEntry200::
    .2byte 3, 8, 4, 2, 3, 0, 0, 0xA, 4, 5, 5, 2
    .dexName "RAYQUAZA"
    .dexCategory "SKY HIGH"
    .dexText "RAYQUAZA is said to have lived for"
    .dexText "hundreds of millions of years in the"
    .dexText "earth`s ozone layer, above the clouds."
    .dexText "Its existence had been completely"
    .dexText "unknown because it lived so high in"
    .dexText "the sky."

    .align 2, 0
dexEntry201::
    .2byte 3, 8, 5, 0xA, 1, 0, 0, 0xA, 0xA, 0xA, 2, 4
    .dexName "JIRACHI"
    .dexCategory "WISH"
    .dexText "A legend states that JIRACHI will make"
    .dexText "true any wish that is written on notes"
    .dexText "attached to its head when it awakens."
    .dexText "If this POKéMON senses danger, it will"
    .dexText "fight without awakening."
    .dexText ""

    .align 2, 0
dexEntry202::
    .2byte 1, 5, 2, 0xA, 2, 1, 1, 0xA, 0xA, 1, 4, 1
    .dexName "CHIKORITA"
    .dexCategory "LEAF"
    .dexText "Bonus appearance on Ruby Field."
    .dexText ""
    .dexText ""
    .dexText ""
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry203::
    .2byte 1, 5, 5, 0xA, 1, 0, 8, 0xA, 0xA, 1, 7, 4
    .dexName "CYNDAQUIL"
    .dexCategory "FIRE MOUSE"
    .dexText "Bonus appearance on Ruby Field."
    .dexText ""
    .dexText ""
    .dexText ""
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry204::
    .2byte 1, 5, 8, 0xA, 2, 0, 0, 0xA, 0xA, 2, 0, 9
    .dexName "TOTODILE"
    .dexCategory "BIG JAW"
    .dexText "Bonus appearance on Ruby Field."
    .dexText ""
    .dexText ""
    .dexText ""
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry205::
    .2byte 1, 4, 2, 0xA, 5, 1, 1, 0xA, 1, 3, 0, 1
    .dexName "AERODACTYL"
    .dexCategory "FOSSIL"
    .dexText "Bonus appearance on Ruby Field."
    .dexText ""
    .dexText ""
    .dexText ""
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry206::
    .2byte 3, 8, 6, 0xA, 5, 0, 7, 0, 1, 3, 4, 0
    .dexName "DEOXYS"
    .dexCategory "DNA"
    .dexText "A POKéMON that mutated from an"
    .dexText "extraterrestrial virus exposed to a laser"
    .dexText "beam. Its body is configured for superior"
    .dexText "agility and speed."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry207::
    .2byte 5, 2, 2, 0xA, 0, 0, 8, 0xA, 2, 9, 8, 0
    .dexName "BLITZLE"
    .dexCategory "ELECTRIFIED"
    .dexText "BLITZLE stores electricity in its mane."
    .dexText "When it discharges, its stripes flash"
    .dexText "with crackling light."
    .dexText "It dashes across open fields in"
    .dexText "sudden bursts."
    .dexText ""

    .align 2, 0
dexEntry208::
    .2byte 0, 0, 1, 0xA, 2, 0, 4, 0, 0, 1, 5, 2
    .dexName "BULBASAUR"
    .dexCategory "SEED"
    .dexText "There is a plant seed on its back right"
    .dexText "from the day this POKéMON is born. The"
    .dexText "seed slowly grows larger."
    .dexText ""
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry209::
    .2byte 0, 0, 2, 0xA, 3, 0, 3, 0, 0, 2, 8, 7
    .dexName "IVYSAUR"
    .dexCategory "SEED"
    .dexText "To support its bulb, IVYSAUR`s legs grow"
    .dexText "sturdy. If it spends more time lying in"
    .dexText "the sunlight, the bud will soon bloom into"
    .dexText "a large flower."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry210::
    .2byte 0, 0, 3, 0xA, 6, 0, 7, 0, 2, 2, 0, 5
    .dexName "VENUSAUR"
    .dexCategory "SEED"
    .dexText "VENUSAUR`s flower is said to take on vivid"
    .dexText "colors if it gets plenty of nutrition and"
    .dexText "sunlight. The flower`s aroma soothes the"
    .dexText "emotions of people."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry211::
    .2byte 0, 0, 4, 0xA, 2, 0, 0, 0, 0, 1, 8, 7
    .dexName "CHARMANDER"
    .dexCategory "LIZARD"
    .dexText "The flame that burns at the tip of its"
    .dexText "tail is an indication of its emotions. The"
    .dexText "flame wavers when CHARMANDER is happy, and"
    .dexText "blazes when it is enraged."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry212::
    .2byte 0, 0, 5, 0xA, 3, 0, 7, 0, 0, 4, 1, 9
    .dexName "CHARMELEON"
    .dexCategory "FLAME"
    .dexText "Without pity, its sharp claws destroy"
    .dexText "foes. If it encounters a strong enemy, it"
    .dexText "becomes agitated, and the flame on its"
    .dexText "tail flares with a bluish white color."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry213::
    .2byte 0, 0, 6, 0xA, 5, 0, 7, 0, 1, 9, 9, 5
    .dexName "CHARIZARD"
    .dexCategory "FLAME"
    .dexText "A CHARIZARD flies about in search of"
    .dexText "strong opponents. It breathes intense"
    .dexText "flames that can melt any material."
    .dexText "However, it will never torch a weaker foe."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry214::
    .2byte 0, 0, 7, 0xA, 1, 0, 8, 0, 0, 1, 9, 8
    .dexName "SQUIRTLE"
    .dexCategory "TINY TURTLE"
    .dexText "Its shell is not just for protection. Its"
    .dexText "rounded shape and the grooves on its"
    .dexText "surface minimize resistance in water,"
    .dexText "enabling SQUIRTLE to swim at high speeds."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry215::
    .2byte 0, 0, 8, 0xA, 3, 0, 3, 0, 0, 4, 9, 6
    .dexName "WARTORTLE"
    .dexCategory "TURTLE"
    .dexText "Its large tail is covered with rich, thick"
    .dexText "fur that deepens in color with age. The"
    .dexText "scratches on its shell are evidence of"
    .dexText "this POKéMON`s toughness in battle."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry216::
    .2byte 0, 0, 9, 0xA, 5, 0, 3, 0, 1, 8, 8, 5
    .dexName "BLASTOISE"
    .dexCategory "SHELLFISH"
    .dexText "The waterspouts that protrude from its"
    .dexText "shell are highly accurate. Their bullets"
    .dexText "of water can precisely nail tin cans from"
    .dexText "a distance of over 160 feet."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry217::
    .2byte 0, 1, 0, 0xA, 1, 0, 0, 0, 0, 0, 6, 4
    .dexName "CATERPIE"
    .dexCategory "WORM"
    .dexText "Its voracious appetite compels it to"
    .dexText "devour leaves bigger than itself without"
    .dexText "hesitation. It releases a terribly strong"
    .dexText "odor from its antennae."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry218::
    .2byte 0, 1, 1, 0xA, 2, 0, 4, 0, 0, 2, 1, 8
    .dexName "METAPOD"
    .dexCategory "COCOON"
    .dexText "Its shell is as hard as an iron slab. A"
    .dexText "METAPOD does not move very much because it"
    .dexText "is preparing its soft innards for"
    .dexText "evolution inside the shell."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry219::
    .2byte 0, 1, 2, 0xA, 3, 0, 7, 0, 0, 7, 0, 5
    .dexName "BUTTERFREE"
    .dexCategory "BUTTERFLY"
    .dexText "It has a superior ability to search for"
    .dexText "delicious honey from flowers. It can seek,"
    .dexText "extract, and carry honey from flowers"
    .dexText "blooming over six miles away."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry220::
    .2byte 0, 1, 3, 0xA, 1, 0, 0, 0, 0, 0, 7, 1
    .dexName "WEEDLE"
    .dexCategory "HAIRY BUG"
    .dexText "A WEEDLE has an extremely acute sense of"
    .dexText "smell. It distinguishes its favorite kinds"
    .dexText "of leaves from those it dislikes by"
    .dexText "sniffing with its big red proboscis"
    .dexText "(nose)."
    .dexText ""

    .align 2, 0
dexEntry221::
    .2byte 0, 1, 4, 0xA, 2, 0, 0, 0, 0, 2, 2, 0
    .dexName "KAKUNA"
    .dexCategory "COCOON"
    .dexText "It remains virtually immobile while it"
    .dexText "clings to a tree. However, on the inside,"
    .dexText "it busily prepares for evolution. This is"
    .dexText "evident from how hot its shell becomes."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry222::
    .2byte 0, 1, 5, 0xA, 3, 0, 3, 0, 0, 6, 5, 0
    .dexName "BEEDRILL"
    .dexCategory "POISON BEE"
    .dexText "A BEEDRILL is extremely territorial. For"
    .dexText "safety reasons, no one should ever"
    .dexText "approach its nest. If angered, they will"
    .dexText "attack in a swarm."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry223::
    .2byte 0, 1, 6, 0xA, 1, 0, 0, 0, 0, 0, 4, 0
    .dexName "PIDGEY"
    .dexCategory "TINY BIRD"
    .dexText "It has an extremely sharp sense of"
    .dexText "direction. It can unerringly return home"
    .dexText "to its nest, however far it may be removed"
    .dexText "from its familiar surroundings."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry224::
    .2byte 0, 1, 7, 0xA, 3, 0, 7, 0, 0, 6, 6, 1
    .dexName "PIDGEOTTO"
    .dexCategory "BIRD"
    .dexText "This POKéMON flies around, patrolling its"
    .dexText "large territory. If its living space is"
    .dexText "violated, it shows no mercy in thoroughly"
    .dexText "punishing the foe with its sharp claws."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry225::
    .2byte 0, 1, 8, 0xA, 4, 1, 1, 0, 0, 8, 7, 1
    .dexName "PIDGEOT"
    .dexCategory "BIRD"
    .dexText "This POKéMON has gorgeous, glossy"
    .dexText "feathers. Many TRAINERS are so captivated"
    .dexText "by the beautiful feathers on its head that"
    .dexText "they choose PIDGEOT as their POKéMON."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry226::
    .2byte 0, 1, 9, 0xA, 1, 0, 0, 0, 0, 0, 7, 7
    .dexName "RATTATA"
    .dexCategory "MOUSE"
    .dexText "A RATTATA is cautious in the extreme. Even"
    .dexText "while it is asleep, it constantly moves"
    .dexText "its ears and listens for danger. It will"
    .dexText "make its nest anywhere."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry227::
    .2byte 0, 2, 0, 0xA, 2, 0, 4, 0, 0, 4, 0, 8
    .dexName "RATICATE"
    .dexCategory "MOUSE"
    .dexText "A RATICATE`s sturdy fangs grow steadily."
    .dexText "To keep them ground down, it gnaws on"
    .dexText "rocks and logs. It may even chew on the"
    .dexText "walls of houses."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry228::
    .2byte 0, 2, 1, 0xA, 1, 0, 0, 0, 0, 0, 4, 4
    .dexName "SPEAROW"
    .dexCategory "TINY BIRD"
    .dexText "Its loud cry can be heard over half a mile"
    .dexText "away. If its high, keening cry is heard"
    .dexText "echoing all around, it is a sign that they"
    .dexText "are warning each other of danger."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry229::
    .2byte 0, 2, 2, 0xA, 3, 1, 1, 0, 0, 8, 3, 8
    .dexName "FEAROW"
    .dexCategory "BEAK"
    .dexText "Its long neck and elongated beak are ideal"
    .dexText "for catching prey in soil or water. It"
    .dexText "deftly moves this extended and skinny beak"
    .dexText "to pluck prey."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry230::
    .2byte 0, 2, 3, 0xA, 6, 0, 7, 0, 0, 1, 5, 2
    .dexName "EKANS"
    .dexCategory "SNAKE"
    .dexText "An EKANS curls itself up in a spiral while"
    .dexText "it rests. This position allows it to"
    .dexText "quickly respond to an enemy from any"
    .dexText "direction with a threat from its upraised"
    .dexText "head."
    .dexText ""

    .align 2, 0
dexEntry231::
    .2byte 0, 2, 4, 1, 1, 0, 6, 0, 1, 4, 3, 3
    .dexName "ARBOK"
    .dexCategory "COBRA"
    .dexText "This POKéMON has a terrifically strong"
    .dexText "constricting power. It can even flatten"
    .dexText "steel oil drums. Once it wraps its body"
    .dexText "around its foe, escaping is impossible."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry232::
    .2byte 0, 2, 9, 0xA, 1, 0, 4, 0, 0, 1, 5, 4
    .dexName "NIDORAN F"
    .dexCategory "POISON PIN"
    .dexText "Its highly toxic barbs are thought to have"
    .dexText "developed as protection for this small-"
    .dexText "bodied POKéMON. When enraged, it releases"
    .dexText "a horrible toxin from its horn."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry233::
    .2byte 0, 3, 0, 0xA, 2, 0, 7, 0, 0, 4, 4, 1
    .dexName "NIDORINA"
    .dexCategory "POISON PIN"
    .dexText "When it is with its friends or family, its"
    .dexText "barbs are tucked away to prevent injury."
    .dexText "It appears to become nervous if separated"
    .dexText "from the others."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry234::
    .2byte 0, 3, 1, 0xA, 4, 0, 3, 0, 1, 3, 2, 3
    .dexName "NIDOQUEEN"
    .dexCategory "DRILL"
    .dexText "It is adept at sending foes flying with"
    .dexText "harsh tackles using its tough, scaly body."
    .dexText "This POKéMON is at its strongest when it"
    .dexText "is defending its young."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry235::
    .2byte 0, 3, 2, 0xA, 1, 0, 8, 0, 0, 1, 9, 8
    .dexName "NIDORAN M"
    .dexCategory "POISON PIN"
    .dexText "The male NIDORAN has developed muscles"
    .dexText "that freely move its ears in any"
    .dexText "direction. Even the slightest sound does"
    .dexText "not escape this POKéMON`s notice."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry236::
    .2byte 0, 3, 3, 0xA, 2, 1, 1, 0, 0, 4, 3, 0
    .dexName "NIDORINO"
    .dexCategory "POISON PIN"
    .dexText "Its horn is harder than a diamond. If it"
    .dexText "senses a hostile presence, all the barbs"
    .dexText "on its back bristle up at once, and it"
    .dexText "challenges the foe with all its might."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry237::
    .2byte 0, 3, 4, 0xA, 4, 0, 7, 0, 1, 3, 6, 7
    .dexName "NIDOKING"
    .dexCategory "DRILL"
    .dexText "A NIDOKING`s thick tail packs enormously"
    .dexText "destructive power capable of toppling a"
    .dexText "metal transmission tower. Once it goes on"
    .dexText "a rampage, there is no stopping it."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry238::
    .2byte 0, 3, 5, 0xA, 2, 0, 0, 0, 0, 1, 6, 5
    .dexName "CLEFAIRY"
    .dexCategory "FAIRY"
    .dexText "On every night of a full moon, they come"
    .dexText "out to play. When dawn arrives, the tired"
    .dexText "CLEFAIRY go to sleep nestled up against"
    .dexText "each other in deep and quiet mountains."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry239::
    .2byte 0, 3, 6, 0xA, 4, 0, 3, 0, 0, 8, 8, 2
    .dexName "CLEFABLE"
    .dexCategory "FAIRY"
    .dexText "A CLEFABLE uses its wings to skip lightly"
    .dexText "as if it were flying. Its bouncy step lets"
    .dexText "it even walk on water. On quiet, moonlit"
    .dexText "nights, it strolls on lakes."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry240::
    .2byte 0, 4, 6, 0xA, 1, 0, 0, 0, 0, 1, 1, 9
    .dexName "PARAS"
    .dexCategory "MUSHROOM"
    .dexText "A PARAS has parasitic tochukaso mushrooms"
    .dexText "growing on its back. They grow by drawing"
    .dexText "nutrients from the host. They are valued"
    .dexText "as a medicine for long life."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry241::
    .2byte 0, 4, 7, 0xA, 3, 0, 3, 0, 0, 6, 5, 0
    .dexName "PARASECT"
    .dexCategory "MUSHROOM"
    .dexText "PARASECT are known to infest the roots of"
    .dexText "large trees en masse and drain nutrients."
    .dexText "When an infested tree dies, they move onto"
    .dexText "another tree all at once."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry242::
    .2byte 0, 4, 8, 0xA, 3, 0, 3, 0, 0, 6, 6, 1
    .dexName "VENONAT"
    .dexCategory "INSECT"
    .dexText "Its coat of thin, stiff hair that covers"
    .dexText "its entire body is said to have evolved"
    .dexText "for protection. Its large eyes never fail"
    .dexText "to spot even miniscule prey."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry243::
    .2byte 0, 4, 9, 0xA, 4, 1, 1, 0, 0, 2, 7, 6
    .dexName "VENOMOTH"
    .dexCategory "POISON MOTH"
    .dexText "VENOMOTH are nocturnal--they only are"
    .dexText "active at night. Their favorite prey are"
    .dexText "insects that gather around streetlights,"
    .dexText "attracted by the light in the darkness."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry244::
    .2byte 0, 5, 0, 0xA, 0, 0, 8, 0, 0, 0, 1, 8
    .dexName "DIGLETT"
    .dexCategory "MOLE"
    .dexText "DIGLETT are raised in most farms. The"
    .dexText "reason is simple--wherever they burrow,"
    .dexText "the soil is left perfectly tilled for"
    .dexText "growing delicious crops."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry245::
    .2byte 0, 5, 1, 0xA, 2, 0, 4, 0, 0, 7, 3, 4
    .dexName "DUGTRIO"
    .dexCategory "MOLE"
    .dexText "Because the triplets originally split from"
    .dexText "one body, they think exactly alike. They"
    .dexText "work cooperatively to burrow endlessly"
    .dexText "through the ground."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry246::
    .2byte 0, 5, 2, 0xA, 1, 0, 4, 0, 0, 0, 9, 3
    .dexName "MEOWTH"
    .dexCategory "SCRATCH CAT"
    .dexText "MEOWTH withdraw their sharp claws into"
    .dexText "their paws to silently sneak about. For"
    .dexText "some reason, this POKéMON loves shiny"
    .dexText "coins that glitter with light."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry247::
    .2byte 0, 5, 3, 0xA, 3, 0, 3, 0, 0, 7, 0, 5
    .dexName "PERSIAN"
    .dexCategory "CLASSY CAT"
    .dexText "A PERSIAN`s six bold whiskers sense air"
    .dexText "movements to determine what is in its"
    .dexText "vicinity. It becomes docile if grabbed by"
    .dexText "the whiskers."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry248::
    .2byte 0, 5, 6, 0xA, 1, 0, 8, 0, 0, 6, 1, 7
    .dexName "MANKEY"
    .dexCategory "PIG MONKEY"
    .dexText "When it starts shaking and its nasal"
    .dexText "breathing turns rough, it`s a sure sign of"
    .dexText "anger. However, since this happens"
    .dexText "instantly, there is no time to flee."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry249::
    .2byte 0, 5, 7, 0xA, 3, 0, 3, 0, 0, 7, 0, 5
    .dexName "PRIMEAPE"
    .dexCategory "PIG MONKEY"
    .dexText "When it becomes furious, its blood"
    .dexText "circulation becomes more robust, and its"
    .dexText "muscles are made stronger. But it also"
    .dexText "becomes much less intelligent."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry250::
    .2byte 0, 5, 8, 0xA, 2, 0, 4, 0, 0, 4, 1, 9
    .dexName "GROWLITHE"
    .dexCategory "PUPPY"
    .dexText "Its superb sense of smell ensures that"
    .dexText "this POKéMON won`t forget any scent, no"
    .dexText "matter what. It uses its sense of smell to"
    .dexText "detect the emotions of others."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry251::
    .2byte 0, 5, 9, 0xA, 6, 0, 3, 0, 3, 4, 1, 7
    .dexName "ARCANINE"
    .dexCategory "LEGENDARY"
    .dexText "This fleet-footed POKéMON is said to run"
    .dexText "over 6,200 miles in a single day and"
    .dexText "night. The fire that blazes wildly within"
    .dexText "its body is its source of power."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry252::
    .2byte 0, 6, 0, 0xA, 2, 0, 0, 0, 0, 2, 7, 3
    .dexName "POLIWAG"
    .dexCategory "TADPOLE"
    .dexText "It is possible to see this POKéMON`s"
    .dexText "spiral innards right through its thin"
    .dexText "skin. However, the skin is also very"
    .dexText "flexible. Even sharp fangs bounce right"
    .dexText "off it."
    .dexText ""

    .align 2, 0
dexEntry253::
    .2byte 0, 6, 1, 0xA, 3, 0, 3, 0, 0, 4, 4, 1
    .dexName "POLIWHIRL"
    .dexCategory "TADPOLE"
    .dexText "Its body surface is always wet and slick"
    .dexText "with an oily fluid. Because of this greasy"
    .dexText "covering, it can easily slip and slide out"
    .dexText "of the clutches of any enemy in battle."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry254::
    .2byte 0, 6, 2, 0xA, 4, 0, 3, 0, 1, 1, 9, 0
    .dexName "POLIWRATH"
    .dexCategory "TADPOLE"
    .dexText "Its highly developed muscles never grow"
    .dexText "fatigued, however much it exercises. This"
    .dexText "POKéMON can swim back and forth across the"
    .dexText "Pacific Ocean without effort."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry255::
    .2byte 0, 6, 9, 0xA, 2, 0, 4, 0, 0, 0, 8, 8
    .dexName "BELLSPROUT"
    .dexCategory "FLOWER"
    .dexText "A BELLSPROUT`s thin and flexible body lets"
    .dexText "it bend and sway to avoid any attack,"
    .dexText "however strong it may be. From its mouth,"
    .dexText "it leaks a fluid that melts even iron."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry256::
    .2byte 0, 7, 0, 0xA, 3, 0, 3, 0, 0, 1, 4, 1
    .dexName "WEEPINBELL"
    .dexCategory "FLYCATCHER"
    .dexText "At night, a WEEPINBELL hangs on to a tree"
    .dexText "branch with its hooked rear and sleeps. If"
    .dexText "it moves around in its sleep, it may wake"
    .dexText "up to find itself on the ground."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry257::
    .2byte 0, 7, 1, 0xA, 5, 0, 7, 0, 0, 3, 4, 2
    .dexName "VICTREEBEL"
    .dexCategory "FLYCATCHER"
    .dexText "The long vine extending from its head is"
    .dexText "waved about as if it were a living thing"
    .dexText "to attract prey. When an unsuspecting"
    .dexText "victim approaches, it is swallowed whole."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry258::
    .2byte 0, 7, 7, 0xA, 3, 0, 3, 0, 0, 6, 6, 1
    .dexName "PONYTA"
    .dexCategory "FIRE HORSE"
    .dexText "A PONYTA is very weak at birth. It can"
    .dexText "barely stand up. Its legs become stronger"
    .dexText "as it stumbles and falls while trying to"
    .dexText "keep up with its parent."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry259::
    .2byte 0, 7, 8, 0xA, 5, 0, 7, 0, 2, 0, 9, 4
    .dexName "RAPIDASH"
    .dexCategory "FIRE HORSE"
    .dexText "It usually canters casually in the fields"
    .dexText "and plains. But once a RAPIDASH turns"
    .dexText "serious, its fiery manes flare and blaze"
    .dexText "as it gallops its way up to 150 mph."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry260::
    .2byte 0, 7, 9, 0xA, 3, 1, 1, 0, 0, 7, 9, 4
    .dexName "SLOWPOKE"
    .dexCategory "DOPEY"
    .dexText "It catches prey by dipping its tail in"
    .dexText "water at the side of a river. But it often"
    .dexText "forgets what it is doing and spends entire"
    .dexText "days just loafing at water`s edge."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry261::
    .2byte 0, 8, 0, 0xA, 5, 0, 3, 0, 1, 7, 3, 1
    .dexName "SLOWBRO"
    .dexCategory "HERMIT CRAB"
    .dexText "Its tail has a SHELLDER firmly attached"
    .dexText "with a bite. As a result, the tail can`t"
    .dexText "be used for fishing anymore. This forces"
    .dexText "it to reluctantly swim and catch prey."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry262::
    .2byte 0, 8, 3, 0xA, 2, 0, 7, 0, 0, 3, 3, 1
    .dexName "FARFETCHD"
    .dexCategory "WILD DUCK"
    .dexText "It is always seen with a stick from a"
    .dexText "plant. Apparently, there are good sticks"
    .dexText "and bad sticks. This POKéMON occasionally"
    .dexText "fights with others over choice sticks."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry263::
    .2byte 0, 8, 6, 0xA, 3, 0, 7, 0, 1, 9, 8, 4
    .dexName "SEEL"
    .dexCategory "SEA LION"
    .dexText "SEEL hunt for prey in frigid, ice-covered"
    .dexText "seas. When it needs to breathe, it punches"
    .dexText "a hole through the ice with the sharply"
    .dexText "protruding section of its head."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry264::
    .2byte 0, 8, 7, 0xA, 5, 0, 7, 0, 2, 6, 4, 6
    .dexName "DEWGONG"
    .dexCategory "SEA LION"
    .dexText "It loves to snooze on bitterly cold ice."
    .dexText "The sight of this POKéMON sleeping on a"
    .dexText "glacier was mistakenly thought to be a"
    .dexText "mermaid by a mariner long ago."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry265::
    .2byte 0, 9, 0, 0xA, 1, 0, 0, 0, 0, 0, 8, 8
    .dexName "SHELLDER"
    .dexCategory "BIVALVE"
    .dexText "At night, it burrows a hole in the"
    .dexText "seafloor with its broad tongue to make a"
    .dexText "place to sleep. While asleep, it closes"
    .dexText "its shell, but leaves its tongue hanging"
    .dexText "out."
    .dexText ""

    .align 2, 0
dexEntry266::
    .2byte 0, 9, 1, 0xA, 4, 1, 1, 0, 2, 9, 2, 1
    .dexName "CLOYSTER"
    .dexCategory "BIVALVE"
    .dexText "It swims in the sea by swallowing water,"
    .dexText "then jetting it out toward the rear. The"
    .dexText "CLOYSTER shoots spikes from its shell"
    .dexText "using the same system."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry267::
    .2byte 0, 9, 2, 0xA, 4, 0, 3, 0, 0, 0, 0, 2
    .dexName "GASTLY"
    .dexCategory "GAS"
    .dexText "When exposed to a strong wind, a GASTLY`s"
    .dexText "gaseous body quickly dwindles away. They"
    .dexText "cluster under the eaves of houses to"
    .dexText "escape the ravages of wind."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry268::
    .2byte 0, 9, 3, 0xA, 5, 0, 3, 0, 0, 0, 0, 2
    .dexName "HAUNTER"
    .dexCategory "GAS"
    .dexText "If a HAUNTER beckons you while it is"
    .dexText "floating in darkness, don`t approach it."
    .dexText "This POKéMON will try to lick you with its"
    .dexText "tongue and steal your life away."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry269::
    .2byte 0, 9, 4, 0xA, 4, 1, 1, 0, 0, 8, 9, 3
    .dexName "GENGAR"
    .dexCategory "SHADOW"
    .dexText "Deep in the night, your shadow cast by a"
    .dexText "streetlight may suddenly overtake you. It"
    .dexText "is actually a GENGAR running past you,"
    .dexText "pretending to be your shadow."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry270::
    .2byte 0, 9, 5, 2, 8, 1, 0, 0, 4, 6, 3, 0
    .dexName "ONIX"
    .dexCategory "ROCK SNAKE"
    .dexText "There is a magnet in its brain that"
    .dexText "prevents an ONIX from losing direction"
    .dexText "while tunneling. As it grows older, its"
    .dexText "body becomes steadily rounder and"
    .dexText "smoother."
    .dexText ""

    .align 2, 0
dexEntry271::
    .2byte 0, 9, 6, 0xA, 3, 0, 3, 0, 0, 7, 1, 4
    .dexName "DROWZEE"
    .dexCategory "HYPNOSIS"
    .dexText "If your nose becomes itchy while you are"
    .dexText "sleeping, it`s a sure sign that a DROWZEE"
    .dexText "is standing above your pillow and trying"
    .dexText "to eat your dream through your nostrils."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry272::
    .2byte 0, 9, 7, 0xA, 5, 0, 3, 0, 1, 6, 6, 7
    .dexName "HYPNO"
    .dexCategory "HYPNOSIS"
    .dexText "The arcing movement and glitter of the"
    .dexText "pendulum in a HYPNO`s hand lull the foe"
    .dexText "into deep hypnosis. While searching for"
    .dexText "prey, it polishes the pendulum."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry273::
    .2byte 0, 9, 8, 0xA, 1, 0, 4, 0, 0, 1, 4, 3
    .dexName "KRABBY"
    .dexCategory "RIVER CRAB"
    .dexText "KRABBY live in holes dug into beaches. On"
    .dexText "sandy shores with little in the way of"
    .dexText "food, they can be seen squabbling with"
    .dexText "each other over territory."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry274::
    .2byte 0, 9, 9, 0xA, 4, 0, 3, 0, 1, 3, 2, 3
    .dexName "KINGLER"
    .dexCategory "PINCER"
    .dexText "It waves its huge, oversized claw in the"
    .dexText "air to communicate with others. But since"
    .dexText "the claw is so heavy, this POKéMON quickly"
    .dexText "tires."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry275::
    .2byte 1, 0, 2, 0xA, 1, 0, 4, 0, 0, 0, 5, 5
    .dexName "EXEGGCUTE"
    .dexCategory "EGG"
    .dexText "It consists of six eggs that care for each"
    .dexText "other. The eggs attract each other and"
    .dexText "spin around. When cracks increasingly"
    .dexText "appear, it is close to evolution."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry276::
    .2byte 1, 0, 3, 0xA, 6, 0, 7, 0, 2, 6, 4, 6
    .dexName "EXEGGUTOR"
    .dexCategory "COCONUT"
    .dexText "Originally from the tropics, EXEGGUTOR`s"
    .dexText "heads grow larger from exposure to strong"
    .dexText "sunlight. It is said that when the heads"
    .dexText "fall, they group to form an EXEGGCUTE."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry277::
    .2byte 1, 0, 4, 0xA, 1, 0, 4, 0, 0, 1, 4, 3
    .dexName "CUBONE"
    .dexCategory "LONELY"
    .dexText "It pines for the mother it will never see"
    .dexText "again. Seeing a likeness of its mother in"
    .dexText "the full moon, it cries. The stains on the"
    .dexText "skull it wears are from its tears."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry278::
    .2byte 1, 0, 5, 0xA, 3, 0, 3, 0, 0, 9, 9, 2
    .dexName "MAROWAK"
    .dexCategory "BONE KEEPER"
    .dexText "A MAROWAK is the evolved form of a CUBONE"
    .dexText "that has grown tough by overcoming the"
    .dexText "grief of losing its mother. Its tempered"
    .dexText "and hardened spirit is not easily broken."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry279::
    .2byte 1, 0, 6, 0xA, 4, 1, 1, 0, 1, 0, 9, 8
    .dexName "HITMONLEE"
    .dexCategory "KICKING"
    .dexText "Its legs freely stretch and contract."
    .dexText "Using these springlike limbs, it bowls"
    .dexText "over foes with devastating kicks. After"
    .dexText "battle, it rubs down its tired legs."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry280::
    .2byte 1, 0, 7, 0xA, 4, 0, 7, 0, 1, 1, 0, 7
    .dexName "HITMONCHAN"
    .dexCategory "PUNCHING"
    .dexText "A HITMONCHAN is said to possess the spirit"
    .dexText "of a boxer who aimed to become the world"
    .dexText "champion. Having an indomitable spirit"
    .dexText "means that it will never give up."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry281::
    .2byte 1, 0, 8, 0xA, 3, 1, 1, 0, 1, 4, 4, 4
    .dexName "LICKITUNG"
    .dexCategory "LICKING"
    .dexText "Whenever it sees something unfamiliar, it"
    .dexText "always licks the object because it"
    .dexText "memorizes things by texture and taste. It"
    .dexText "is somewhat put off by sour things."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry282::
    .2byte 1, 1, 3, 0xA, 3, 0, 7, 0, 0, 7, 6, 3
    .dexName "CHANSEY"
    .dexCategory "EGG"
    .dexText "CHANSEY lay nutritionally excellent eggs"
    .dexText "every day. The eggs are so delicious, they"
    .dexText "are eagerly devoured by even those people"
    .dexText "who have lost their appetite."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry283::
    .2byte 1, 1, 4, 0xA, 3, 0, 3, 0, 0, 7, 7, 2
    .dexName "TANGELA"
    .dexCategory "VINE"
    .dexText "Its vines snap off easily and painlessly"
    .dexText "if they are grabbed, allowing it to make a"
    .dexText "quick getaway. The lost vines are replaced"
    .dexText "by new growth the very next day."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry284::
    .2byte 1, 1, 5, 0xA, 7, 0, 3, 0, 1, 7, 6, 4
    .dexName "KANGASKHAN"
    .dexCategory "PARENT"
    .dexText "If you come across a young KANGASKHAN"
    .dexText "playing by itself, never try to catch it."
    .dexText "The baby`s parent is sure to be in the"
    .dexText "area, and it will become violently"
    .dexText "enraged."
    .dexText ""

    .align 2, 0
dexEntry285::
    .2byte 1, 2, 2, 0xA, 4, 0, 3, 0, 1, 2, 0, 2
    .dexName "MR MIME"
    .dexCategory "BARRIER"
    .dexText "A MR. MIME is a master of pantomime. It"
    .dexText "can convince others that something"
    .dexText "unseeable actually exists. Once believed,"
    .dexText "the imaginary object does become real."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry286::
    .2byte 1, 2, 3, 0xA, 4, 1, 1, 0, 1, 2, 3, 5
    .dexName "SCYTHER"
    .dexCategory "MANTIS"
    .dexText "Its blindingly fast speed adds to the"
    .dexText "sharpness of its twin forearm scythes. The"
    .dexText "scythes can slice through thick logs in"
    .dexText "one wicked stroke."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry287::
    .2byte 1, 2, 4, 0xA, 4, 0, 7, 0, 0, 8, 9, 5
    .dexName "JYNX"
    .dexCategory "HUMAN SHAPE"
    .dexText "A JYNX sashays rhythmically as if it were"
    .dexText "dancing. Its motions are so bouncingly"
    .dexText "alluring, people seeing it are compelled"
    .dexText "to shake their hips without noticing."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry288::
    .2byte 1, 2, 5, 0xA, 3, 0, 7, 0, 0, 6, 6, 1
    .dexName "ELECTABUZZ"
    .dexCategory "ELECTRIC"
    .dexText "When a storm approaches, it competes with"
    .dexText "others to scale heights that are likely to"
    .dexText "be stricken by lightning. Some towns use"
    .dexText "ELECTABUZZ in place of lightning rods."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry289::
    .2byte 1, 2, 6, 0xA, 4, 0, 3, 0, 0, 9, 8, 1
    .dexName "MAGMAR"
    .dexCategory "SPITFIRE"
    .dexText "In battle, it blows out intense flames"
    .dexText "from all over its body to intimidate its"
    .dexText "foe. These fiery bursts create heat waves"
    .dexText "that ignite grass and trees in the area."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry290::
    .2byte 1, 2, 8, 0xA, 4, 0, 7, 0, 1, 9, 4, 9
    .dexName "TAUROS"
    .dexCategory "WILD BULL"
    .dexText "It is not satisfied unless it is rampaging"
    .dexText "at all times. If there is no opponent for"
    .dexText "TAUROS to battle, it will charge at thick"
    .dexText "trees and knock them down to calm itself."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry291::
    .2byte 1, 3, 1, 0xA, 8, 0, 2, 0, 4, 8, 5, 0
    .dexName "LAPRAS"
    .dexCategory "TRANSPORT"
    .dexText "People have driven LAPRAS almost to the"
    .dexText "point of extinction. In the evenings, it"
    .dexText "is said to sing plaintively as it seeks"
    .dexText "what few others of its kind still remain."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry292::
    .2byte 1, 3, 2, 0xA, 1, 0, 0, 0, 0, 0, 8, 8
    .dexName "DITTO"
    .dexCategory "TRANSFORM"
    .dexText "A DITTO rearranges its cell structure to"
    .dexText "transform itself. However, if it tries to"
    .dexText "change based on its memory, it will get"
    .dexText "details wrong."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry293::
    .2byte 1, 3, 3, 0xA, 1, 0, 0, 0, 0, 1, 4, 3
    .dexName "EEVEE"
    .dexCategory "EVOLUTION"
    .dexText "An EEVEE has an unstable genetic makeup"
    .dexText "that suddenly mutates due to its"
    .dexText "environment. Radiation from various STONES"
    .dexText "causes this POKéMON to evolve."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry294::
    .2byte 1, 3, 4, 0xA, 3, 0, 3, 0, 0, 6, 3, 9
    .dexName "VAPOREON"
    .dexCategory "BUBBLE JET"
    .dexText "VAPOREON underwent a spontaneous mutation"
    .dexText "and grew fins and gills that allow them to"
    .dexText "live underwater. They have the ability to"
    .dexText "freely control water."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry295::
    .2byte 1, 3, 5, 0xA, 2, 0, 7, 0, 0, 5, 4, 0
    .dexName "JOLTEON"
    .dexCategory "LIGHTNING"
    .dexText "Its cells generate weak power that is"
    .dexText "amplified by its fur`s static electricity"
    .dexText "to drop thunderbolts. The bristling fur is"
    .dexText "made of electrically charged needles."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry296::
    .2byte 1, 3, 6, 0xA, 2, 1, 1, 0, 0, 5, 5, 1
    .dexName "FLAREON"
    .dexCategory "FLAME"
    .dexText "FLAREON`s fluffy fur releases heat into"
    .dexText "the air so that its body does not get"
    .dexText "excessively hot. Its body temperature can"
    .dexText "rise to a maximum of 1,650 degrees F."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry297::
    .2byte 1, 3, 7, 0xA, 2, 0, 7, 0, 0, 8, 0, 5
    .dexName "PORYGON"
    .dexCategory "VIRTUAL"
    .dexText "It is capable of reverting itself entirely"
    .dexText "back to program data in order to enter"
    .dexText "cyberspace. A PORYGON is copy- protected"
    .dexText "so it cannot be duplicated."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry298::
    .2byte 1, 3, 8, 0xA, 1, 0, 4, 0, 0, 1, 6, 5
    .dexName "OMANYTE"
    .dexCategory "SPIRAL"
    .dexText "One of the ancient and long-since-extinct"
    .dexText "POKéMON that have been regenerated from"
    .dexText "fossils by humans. If attacked, it"
    .dexText "withdraws into its hard shell."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry299::
    .2byte 1, 3, 9, 0xA, 3, 0, 3, 0, 0, 7, 7, 2
    .dexName "OMASTAR"
    .dexCategory "SPIRAL"
    .dexText "An OMASTAR uses its tentacles to capture"
    .dexText "its prey. It is believed to have become"
    .dexText "extinct because its shell grew too large,"
    .dexText "making its movements slow and ponderous."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry300::
    .2byte 1, 4, 0, 0xA, 1, 0, 8, 0, 0, 2, 5, 4
    .dexName "KABUTO"
    .dexCategory "SHELLFISH"
    .dexText "It is a POKéMON that has been regenerated"
    .dexText "from a fossil. However, in rare cases,"
    .dexText "living examples have been discovered."
    .dexText "KABUTO have not changed for 300 million"
    .dexText "years."
    .dexText ""

    .align 2, 0
dexEntry301::
    .2byte 1, 4, 1, 0xA, 4, 0, 3, 0, 0, 8, 9, 3
    .dexName "KABUTOPS"
    .dexCategory "SHELLFISH"
    .dexText "KABUTOPS once swam underwater to hunt for"
    .dexText "prey. It was apparently evolving from"
    .dexText "being a water dweller to living on land as"
    .dexText "evident from changes in its gills and"
    .dexText "legs."
    .dexText ""

    .align 2, 0
dexEntry302::
    .2byte 1, 4, 3, 0xA, 6, 1, 1, 1, 0, 1, 4, 1
    .dexName "SNORLAX"
    .dexCategory "SLEEPING"
    .dexText "SNORLAX`s typical day consists of nothing"
    .dexText "more than eating and sleeping. It is such"
    .dexText "a docile POKéMON that there are children"
    .dexText "who use its big belly as a place to play."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry303::
    .2byte 1, 4, 4, 0xA, 5, 0, 7, 0, 1, 2, 2, 1
    .dexName "ARTICUNO"
    .dexCategory "FREEZE"
    .dexText "One of the legendary bird POKéMON. With"
    .dexText "its long tail trailing behind, its flying"
    .dexText "form is magnificent."
    .dexText ""
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry304::
    .2byte 1, 4, 5, 0xA, 5, 0, 3, 0, 1, 1, 6, 0
    .dexName "ZAPDOS"
    .dexCategory "ELECTRIC"
    .dexText "ZAPDOS is a legendary bird POKéMON that"
    .dexText "has the ability to control electricity. It"
    .dexText "usually lives in thunderclouds. It gains"
    .dexText "power if it is stricken by lightning"
    .dexText "bolts."
    .dexText ""

    .align 2, 0
dexEntry305::
    .2byte 1, 4, 6, 0xA, 6, 0, 7, 0, 1, 3, 2, 3
    .dexName "MOLTRES"
    .dexCategory "FLAME"
    .dexText "MOLTRES is a legendary bird POKéMON that"
    .dexText "can control fire. If injured, it is said"
    .dexText "to dip its body in the molten magma of a"
    .dexText "volcano to burn and heal itself."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry306::
    .2byte 1, 4, 7, 0xA, 5, 1, 1, 0, 0, 0, 7, 3
    .dexName "DRATINI"
    .dexCategory "DRAGON"
    .dexText "A DRATINI continually molts and sloughs"
    .dexText "off its old skin. It does so because the"
    .dexText "life energy within its body steadily"
    .dexText "builds to reach uncontrollable levels."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry307::
    .2byte 1, 4, 8, 1, 3, 0, 1, 0, 0, 3, 6, 4
    .dexName "DRAGONAIR"
    .dexCategory "DRAGON"
    .dexText "A DRAGONAIR stores an enormous amount of"
    .dexText "energy inside its body. It is said to"
    .dexText "alter the weather around it by loosing"
    .dexText "energy from the crystals on its neck and"
    .dexText "tail."
    .dexText ""

    .align 2, 0
dexEntry308::
    .2byte 1, 4, 9, 0xA, 7, 0, 3, 0, 4, 6, 3, 0
    .dexName "DRAGONITE"
    .dexCategory "DRAGON"
    .dexText "It can circle the globe in just 16 hours."
    .dexText "It is a kindhearted POKéMON that leads"
    .dexText "lost and foundering ships in a storm to"
    .dexText "the safety of land."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry309::
    .2byte 1, 5, 0, 0xA, 6, 0, 7, 0, 2, 6, 9, 0
    .dexName "MEWTWO"
    .dexCategory "GENETIC"
    .dexText "A POKéMON that was created by genetic"
    .dexText "manipulation. However, even though the"
    .dexText "scientific power of humans made its body,"
    .dexText "they failed to give it a warm heart."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry310::
    .2byte 1, 5, 1, 0xA, 1, 0, 4, 0, 0, 0, 8, 8
    .dexName "MEW"
    .dexCategory "NEW SPECIES"
    .dexText "A MEW is said to possess the genes of all"
    .dexText "POKéMON. It is capable of making itself"
    .dexText "invisible at will, so it entirely avoids"
    .dexText "notice even if it approaches people."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry311::
    .2byte 1, 5, 3, 0xA, 3, 1, 1, 0, 0, 3, 4, 8
    .dexName "BAYLEEF"
    .dexCategory "LEAF"
    .dexText "A BAYLEEF`s neck is ringed by curled-up"
    .dexText "leaves. Inside each leaf is a small tree"
    .dexText "shoot. The fragrance of this shoot makes"
    .dexText "people peppy."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry312::
    .2byte 1, 5, 4, 0xA, 5, 1, 1, 0, 2, 2, 1, 6
    .dexName "MEGANIUM"
    .dexCategory "HERB"
    .dexText "The fragrance of a MEGANIUM`s flower"
    .dexText "soothes and calms emotions. In battle, it"
    .dexText "gives off more of its becalming scent to"
    .dexText "blunt the foe`s fighting spirit."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry313::
    .2byte 1, 5, 6, 0xA, 2, 1, 1, 0, 0, 4, 1, 9
    .dexName "QUILAVA"
    .dexCategory "VOLCANO"
    .dexText "It intimidates foes with intense gusts of"
    .dexText "flames and superheated air. Its quick"
    .dexText "nimbleness lets it dodge attacks even"
    .dexText "while scorching an enemy."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry314::
    .2byte 1, 5, 7, 0xA, 5, 0, 7, 0, 1, 7, 5, 3
    .dexName "TYPHLOSION"
    .dexCategory "VOLCANO"
    .dexText "It can hide behind a shimmering heat haze"
    .dexText "that it creates using its intense flames."
    .dexText "TYPHLOSION create blazing explosive blasts"
    .dexText "that burn everything to cinders."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry315::
    .2byte 1, 5, 9, 0xA, 3, 0, 7, 0, 0, 5, 5, 1
    .dexName "CROCONAW"
    .dexCategory "BIG JAW"
    .dexText "Once its jaws clamp down on its foe, it"
    .dexText "will absolutely not let go. Because the"
    .dexText "tips of its fangs are forked back like"
    .dexText "fishhooks, they become irremovably"
    .dexText "embedded."
    .dexText ""

    .align 2, 0
dexEntry316::
    .2byte 1, 6, 0, 0xA, 7, 0, 7, 0, 1, 9, 5, 8
    .dexName "FERALIGATR"
    .dexCategory "BIG JAW"
    .dexText "It opens its huge mouth to intimidate"
    .dexText "enemies. In battle, it runs using its"
    .dexText "thick and powerful hind legs to charge the"
    .dexText "foe with incredible speed."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry317::
    .2byte 1, 6, 1, 0xA, 2, 0, 7, 0, 0, 1, 3, 2
    .dexName "SENTRET"
    .dexCategory "SCOUT"
    .dexText "They take turns standing guard when it is"
    .dexText "time to sleep. The sentry awakens the"
    .dexText "others if it senses danger. If one becomes"
    .dexText "separated, it turns sleepless with fear."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry318::
    .2byte 1, 6, 2, 0xA, 5, 1, 1, 0, 0, 7, 1, 7
    .dexName "FURRET"
    .dexCategory "LONG BODY"
    .dexText "A FURRET has a very slim build. When under"
    .dexText "attack, it can squirm through narrow"
    .dexText "spaces and get away. In spite of its short"
    .dexText "limbs, it is very nimble and fleet."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry319::
    .2byte 1, 6, 3, 0xA, 2, 0, 4, 0, 0, 4, 6, 7
    .dexName "HOOTHOOT"
    .dexCategory "OWL"
    .dexText "It has an internal organ that senses the"
    .dexText "earth`s rotation. Using this special"
    .dexText "organ, a HOOTHOOT begins hooting at"
    .dexText "precisely the same time every day."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry320::
    .2byte 1, 6, 4, 0xA, 5, 0, 3, 0, 0, 8, 9, 9
    .dexName "NOCTOWL"
    .dexCategory "OWL"
    .dexText "It unfailingly catches prey in darkness."
    .dexText "NOCTOWL owe their success to superior"
    .dexText "vision that allows them to see in minimal"
    .dexText "light, and to their supple and silent"
    .dexText "wings."
    .dexText ""

    .align 2, 0
dexEntry321::
    .2byte 1, 6, 5, 0xA, 3, 0, 3, 0, 0, 2, 3, 8
    .dexName "LEDYBA"
    .dexCategory "FIVE STAR"
    .dexText "LEDYBA communicate using a fluid that they"
    .dexText "secrete from where the legs join the body."
    .dexText "They are said to convey feelings to others"
    .dexText "by altering the fluid`s scent."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry322::
    .2byte 1, 6, 6, 0xA, 4, 0, 7, 0, 0, 7, 8, 5
    .dexName "LEDIAN"
    .dexCategory "FIVE STAR"
    .dexText "It is said that in lands with clean air,"
    .dexText "where the stars fill the sky, there live"
    .dexText "many LEDIAN. For good reason, they use the"
    .dexText "light of the stars as energy."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry323::
    .2byte 1, 6, 7, 0xA, 1, 0, 8, 0, 0, 1, 8, 7
    .dexName "SPINARAK"
    .dexCategory "STRING SPIT"
    .dexText "The web it spins can be considered its"
    .dexText "second nervous system. It is said that a"
    .dexText "SPINARAK determines its prey by the tiny"
    .dexText "vibrations it feels through the web."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry324::
    .2byte 1, 6, 8, 0xA, 3, 0, 7, 0, 0, 7, 3, 9
    .dexName "ARIADOS"
    .dexCategory "LONG LEG"
    .dexText "Its feet are tipped with tiny hooked claws"
    .dexText "that enable it to scuttle on ceilings and"
    .dexText "vertical walls. It constricts its foe with"
    .dexText "thin and strong silk webbing."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry325::
    .2byte 1, 7, 3, 0xA, 1, 0, 0, 0, 0, 0, 6, 6
    .dexName "CLEFFA"
    .dexCategory "STAR SHAPE"
    .dexText "On nights with many shooting stars, CLEFFA"
    .dexText "can be seen dancing in a ring. They dance"
    .dexText "until daybreak, when they quench their"
    .dexText "thirst with the morning dew."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry326::
    .2byte 1, 7, 5, 0xA, 1, 0, 0, 0, 0, 0, 3, 3
    .dexName "TOGEPI"
    .dexCategory "SPIKE BALL"
    .dexText "As its energy, it uses the feelings of"
    .dexText "compassion and pleasure exuded by people"
    .dexText "and POKéMON. It stores up happy feelings"
    .dexText "in its shell, then shares them out."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry327::
    .2byte 1, 7, 6, 0xA, 2, 0, 0, 0, 0, 0, 7, 1
    .dexName "TOGETIC"
    .dexCategory "HAPPINESS"
    .dexText "It is said to be a POKéMON that brings"
    .dexText "good fortune. When it spots someone who is"
    .dexText "pure of heart, a TOGETIC appears and"
    .dexText "shares its happiness with that person."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry328::
    .2byte 1, 7, 9, 0xA, 2, 0, 0, 0, 0, 1, 7, 2
    .dexName "MAREEP"
    .dexCategory "WOOL"
    .dexText "Its fluffy wool rubs together and builds a"
    .dexText "static charge. The more energy is charged,"
    .dexText "the more brightly the lightbulb at the tip"
    .dexText "of its tail glows."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry329::
    .2byte 1, 8, 0, 0xA, 2, 0, 7, 0, 0, 2, 9, 3
    .dexName "FLAAFFY"
    .dexCategory "WOOL"
    .dexText "Its fleece quality changes to generate"
    .dexText "strong static electricity with a small"
    .dexText "amount of wool. The bare, slick parts of"
    .dexText "its hide are shielded against electricity."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry330::
    .2byte 1, 8, 1, 0xA, 4, 0, 7, 0, 1, 3, 5, 6
    .dexName "AMPHAROS"
    .dexCategory "LIGHT"
    .dexText "It gives off so much light that it can be"
    .dexText "seen even from space. People in the old"
    .dexText "days used its light to send signals back"
    .dexText "and forth with others far away."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry331::
    .2byte 1, 8, 5, 0xA, 3, 1, 1, 0, 0, 8, 3, 8
    .dexName "SUDOWOODO"
    .dexCategory "IMITATION"
    .dexText "It mimics a tree to avoid being attacked"
    .dexText "by enemies. But since its forelegs remain"
    .dexText "green throughout the year, it is easily"
    .dexText "identified as a fake in the winter."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry332::
    .2byte 1, 8, 6, 0xA, 3, 0, 7, 0, 0, 7, 4, 7
    .dexName "POLITOED"
    .dexCategory "FROG"
    .dexText "The curled hair on its head proves its"
    .dexText "status as a king. It is said that the"
    .dexText "longer and curlier the hair, the more"
    .dexText "respect it earns from its peers."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry333::
    .2byte 1, 8, 7, 0xA, 1, 0, 4, 0, 0, 0, 1, 1
    .dexName "HOPPIP"
    .dexCategory "COTTONWEED"
    .dexText "This POKéMON drifts and floats with the"
    .dexText "wind. If it senses the approach of strong"
    .dexText "winds, a HOPPIP links leaves with others"
    .dexText "to prepare against being blown away."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry334::
    .2byte 1, 8, 8, 0xA, 2, 0, 0, 0, 0, 0, 2, 2
    .dexName "SKIPLOOM"
    .dexCategory "COTTONWEED"
    .dexText "It blossoms when the temperature rises"
    .dexText "above 64 degrees F. Because its flower`s"
    .dexText "blooming changes with the temperature, it"
    .dexText "is sometimes used as a thermometer."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry335::
    .2byte 1, 8, 9, 0xA, 2, 0, 7, 0, 0, 0, 6, 6
    .dexName "JUMPLUFF"
    .dexCategory "COTTONWEED"
    .dexText "JUMPLUFF ride warm southern winds to cross"
    .dexText "the sea and fly to foreign lands. This"
    .dexText "POKéMON lands when it encounters cold air"
    .dexText "while it is floating."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry336::
    .2byte 1, 9, 0, 0xA, 2, 0, 7, 0, 0, 2, 5, 4
    .dexName "AIPOM"
    .dexCategory "LONG TAIL"
    .dexText "Its tail ends with a dexterous, handlike"
    .dexText "appendage. However, because it uses the"
    .dexText "tail so much, AIPOM`s real hands have"
    .dexText "become rather clumsy."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry337::
    .2byte 1, 9, 1, 0xA, 1, 0, 0, 0, 0, 0, 4, 0
    .dexName "SUNKERN"
    .dexCategory "SEED"
    .dexText "SUNKERN try to minimize movement to"
    .dexText "conserve the nutrients they have stored in"
    .dexText "their bodies for evolution. They will not"
    .dexText "eat, subsisting only on morning dew."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry338::
    .2byte 1, 9, 2, 0xA, 2, 0, 7, 0, 0, 1, 8, 7
    .dexName "SUNFLORA"
    .dexCategory "SUN"
    .dexText "SUNFLORA convert solar energy into"
    .dexText "nutrition. They are highly active in the"
    .dexText "warm daytime but suddenly stop moving as"
    .dexText "soon as the sun sets."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry339::
    .2byte 1, 9, 3, 0xA, 3, 1, 1, 0, 0, 8, 3, 8
    .dexName "YANMA"
    .dexCategory "CLEAR WING"
    .dexText "It can see 360 degrees without moving its"
    .dexText "eyes. It is a great flier capable of"
    .dexText "making sudden stops and turning midair to"
    .dexText "quickly chase down targeted prey."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry340::
    .2byte 1, 9, 4, 0xA, 1, 0, 4, 0, 0, 1, 8, 7
    .dexName "WOOPER"
    .dexCategory "WATER FISH"
    .dexText "WOOPER usually live in water but come out"
    .dexText "onto land seeking food occasionally. On"
    .dexText "land, they coat their bodies with a gooey,"
    .dexText "toxic film."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry341::
    .2byte 1, 9, 5, 0xA, 4, 0, 7, 0, 1, 6, 5, 3
    .dexName "QUAGSIRE"
    .dexCategory "WATER FISH"
    .dexText "A QUAGSIRE hunts by leaving its mouth wide"
    .dexText "open in water and waiting for its prey to"
    .dexText "blunder in. Because it doesn`t move, it"
    .dexText "does not get very hungry."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry342::
    .2byte 1, 9, 6, 0xA, 2, 1, 1, 0, 0, 5, 8, 4
    .dexName "ESPEON"
    .dexCategory "SUN"
    .dexText "An ESPEON is extremely loyal to any"
    .dexText "TRAINER it considers to be worthy. It is"
    .dexText "said to have developed precognitive powers"
    .dexText "to protect its TRAINER from harm."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry343::
    .2byte 1, 9, 7, 0xA, 3, 0, 3, 0, 0, 5, 9, 5
    .dexName "UMBREON"
    .dexCategory "MOONLIGHT"
    .dexText "UMBREON evolved from exposure to the"
    .dexText "moon`s energy pulses. It lurks in darkness"
    .dexText "and waits for its foes to move. The rings"
    .dexText "on its body glow when it leaps to attack."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry344::
    .2byte 1, 9, 8, 0xA, 1, 0, 8, 0, 0, 0, 4, 6
    .dexName "MURKROW"
    .dexCategory "DARKNESS"
    .dexText "MURKROW were feared as the alleged bearers"
    .dexText "of ill fortune. It shows strong interest"
    .dexText "in anything that sparkles. It will even"
    .dexText "try to steal rings from women."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry345::
    .2byte 1, 9, 9, 0xA, 6, 0, 7, 0, 1, 7, 5, 3
    .dexName "SLOWKING"
    .dexCategory "ROYAL"
    .dexText "It undertakes research every day to solve"
    .dexText "the mysteries of the world. However, it"
    .dexText "apparently forgets everything if the"
    .dexText "SHELLDER on its head comes off."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry346::
    .2byte 2, 0, 0, 0xA, 2, 0, 4, 0, 0, 0, 2, 2
    .dexName "MISDREAVUS"
    .dexCategory "SCREECH"
    .dexText "A MISDREAVUS frightens people with a"
    .dexText "creepy, sobbing cry. It apparently uses"
    .dexText "its red spheres to absorb the fear of foes"
    .dexText "as its nutrition."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry347::
    .2byte 2, 0, 1, 0xA, 1, 0, 8, 0, 0, 1, 1, 0
    .dexName "UNOWN"
    .dexCategory "SYMBOL"
    .dexText "This POKéMON is shaped like ancient text"
    .dexText "characters. Although research is ongoing,"
    .dexText "it is a mystery as to which came first,"
    .dexText "the ancient writings or the various UNOWN."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry348::
    .2byte 2, 0, 4, 0xA, 2, 0, 0, 0, 0, 1, 5, 9
    .dexName "PINECO"
    .dexCategory "BAGWORM"
    .dexText "A PINECO hangs from a tree branch and"
    .dexText "waits for prey. While eating, if it is"
    .dexText "disturbed by someone shaking its tree, it"
    .dexText "falls on the ground and suddenly explodes."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry349::
    .2byte 2, 0, 5, 0xA, 3, 1, 1, 0, 2, 7, 7, 3
    .dexName "FORRETRESS"
    .dexCategory "BAGWORM"
    .dexText "It keeps itself inside its steel shell."
    .dexText "The shell is opened when it is catching"
    .dexText "prey, but it is so quick that the shell`s"
    .dexText "inside cannot be seen."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry350::
    .2byte 2, 0, 6, 0xA, 4, 1, 1, 0, 0, 3, 0, 9
    .dexName "DUNSPARCE"
    .dexCategory "LAND SNAKE"
    .dexText "Its drill-tipped tail is used to burrow"
    .dexText "into the ground backwards. This POKéMON is"
    .dexText "known to make its nest in complex shapes"
    .dexText "deep under the ground."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry351::
    .2byte 2, 0, 7, 0xA, 3, 0, 7, 0, 1, 4, 2, 9
    .dexName "GLIGAR"
    .dexCategory "FLYSCORPION"
    .dexText "It glides without making a single sound."
    .dexText "It grasps the face of its foe using its"
    .dexText "hind and large front claws, then stabs"
    .dexText "with its poison barb."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry352::
    .2byte 2, 0, 8, 3, 0, 0, 2, 0, 8, 8, 1, 8
    .dexName "STEELIX"
    .dexCategory "IRON SNAKE"
    .dexText "STEELIX live even further underground than"
    .dexText "ONIX. This POKéMON is known to dig toward"
    .dexText "the earth`s core, reaching a depth of over"
    .dexText "six-tenths of a mile underground."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry353::
    .2byte 2, 0, 9, 0xA, 2, 0, 0, 0, 0, 1, 7, 2
    .dexName "SNUBBULL"
    .dexCategory "FAIRY"
    .dexText "By baring its fangs and making a scary"
    .dexText "face, it sends smaller POKéMON scurrying"
    .dexText "in terror. The SNUBBULL does seem a little"
    .dexText "sad at making its foes flee."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry354::
    .2byte 2, 1, 0, 0xA, 4, 0, 7, 0, 1, 0, 7, 4
    .dexName "GRANBULL"
    .dexCategory "FAIRY"
    .dexText "It has a particularly well-developed lower"
    .dexText "jaw. The huge fangs are heavy, causing it"
    .dexText "to tilt its head. Unless it is startled,"
    .dexText "it will not try to bite."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry355::
    .2byte 2, 1, 1, 0xA, 1, 0, 8, 0, 0, 0, 8, 6
    .dexName "QWILFISH"
    .dexCategory "BALLOON"
    .dexText "A QWILFISH uses the pressure of water it"
    .dexText "swallows to shoot toxic quills all at once"
    .dexText "from all over its body. It finds swimming"
    .dexText "to be somewhat challenging."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry356::
    .2byte 2, 1, 2, 0xA, 5, 1, 1, 0, 2, 6, 0, 1
    .dexName "SCIZOR"
    .dexCategory "PINCER"
    .dexText "A SCIZOR has a body with the hardness of"
    .dexText "steel. It is not easily fazed by ordinary"
    .dexText "sorts of attacks. It flaps its wings to"
    .dexText "regulate its body temperature."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry357::
    .2byte 2, 1, 3, 0xA, 2, 0, 0, 0, 0, 4, 5, 2
    .dexName "SHUCKLE"
    .dexCategory "MOLD"
    .dexText "A SHUCKLE hides under rocks, keeping its"
    .dexText "body concealed inside its shell while"
    .dexText "eating stored berries. The berries mix"
    .dexText "with its body fluids to become a juice."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry358::
    .2byte 2, 1, 5, 0xA, 2, 1, 1, 0, 0, 6, 1, 7
    .dexName "SNEASEL"
    .dexCategory "SHARP CLAW"
    .dexText "A SNEASEL scales trees by punching its"
    .dexText "hooked claws into the bark. It seeks out"
    .dexText "unguarded nests and steals eggs for food"
    .dexText "while the parents are away."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry359::
    .2byte 2, 1, 6, 0xA, 2, 0, 0, 0, 0, 1, 9, 4
    .dexName "TEDDIURSA"
    .dexCategory "LITTLE BEAR"
    .dexText "It licks its palms that are sweetened by"
    .dexText "being soaked in honey. A TEDDIURSA makes"
    .dexText "its own honey by blending fruits and"
    .dexText "pollen collected by BEEDRILL."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry360::
    .2byte 2, 1, 7, 0xA, 5, 1, 1, 0, 2, 7, 7, 3
    .dexName "URSARING"
    .dexCategory "HIBERNATOR"
    .dexText "In forests, it is said that there are many"
    .dexText "streams and towering trees where an"
    .dexText "URSARING gathers food. It walks through"
    .dexText "its forest collecting food every day."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry361::
    .2byte 2, 2, 0, 0xA, 1, 0, 4, 0, 0, 1, 4, 3
    .dexName "SWINUB"
    .dexCategory "PIG"
    .dexText "It roots for food by rubbing its snout"
    .dexText "against the ground. Its favorite food is a"
    .dexText "mushroom that grows under dried grass. It"
    .dexText "occasionally roots out hot springs."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry362::
    .2byte 2, 2, 1, 0xA, 3, 0, 7, 0, 1, 2, 3, 0
    .dexName "PILOSWINE"
    .dexCategory "SWINE"
    .dexText "A PILOSWINE is covered by a thick coat of"
    .dexText "long hair for enduring freezing cold. It"
    .dexText "uses its tusks to dig up food that has"
    .dexText "been buried under ice."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry363::
    .2byte 2, 2, 3, 0xA, 2, 0, 0, 0, 0, 2, 6, 5
    .dexName "REMORAID"
    .dexCategory "JET"
    .dexText "A REMORAID uses its abdominal muscles to"
    .dexText "forcefully expel swallowed water, then"
    .dexText "shoot down flying prey. When evolution"
    .dexText "approaches, it travels down rivers."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry364::
    .2byte 2, 2, 4, 0xA, 2, 1, 1, 0, 0, 6, 2, 8
    .dexName "OCTILLERY"
    .dexCategory "JET"
    .dexText "It ensnares its foe with its suction-"
    .dexText "cupped tentacles before delivering the"
    .dexText "finishing blow. If the foe turns out to be"
    .dexText "too strong, it spews ink to escape."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry365::
    .2byte 2, 2, 5, 0xA, 2, 1, 1, 0, 0, 3, 5, 3
    .dexName "DELIBIRD"
    .dexCategory "DELIVERY"
    .dexText "It carries food bundled up in its tail."
    .dexText "There was a famous explorer who managed to"
    .dexText "scale Mt. Everest thanks to a DELIBIRD"
    .dexText "sharing its food."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry366::
    .2byte 2, 2, 6, 0xA, 6, 1, 1, 0, 4, 8, 5, 0
    .dexName "MANTINE"
    .dexCategory "KITE"
    .dexText "On sunny days, schools of MANTINE can be"
    .dexText "seen elegantly leaping over the waves. It"
    .dexText "is not bothered by the REMORAID that"
    .dexText "hitches rides."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry367::
    .2byte 2, 2, 8, 0xA, 2, 0, 0, 0, 0, 2, 3, 8
    .dexName "HOUNDOUR"
    .dexCategory "DARK"
    .dexText "HOUNDOUR communicate with each other using"
    .dexText "a variety of cries to corner their prey."
    .dexText "This POKéMON`s remarkable teamwork is"
    .dexText "simply unparalleled."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry368::
    .2byte 2, 2, 9, 0xA, 4, 0, 7, 0, 0, 7, 7, 2
    .dexName "HOUNDOOM"
    .dexCategory "DARK"
    .dexText "In a HOUNDOOM pack, the one with its horns"
    .dexText "raked sharply back serves a leadership"
    .dexText "role. They choose their leader by fighting"
    .dexText "among themselves."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry369::
    .2byte 2, 3, 3, 0xA, 2, 0, 0, 0, 0, 7, 1, 7
    .dexName "PORYGON2"
    .dexCategory "VIRTUAL"
    .dexText "It was created by humans using the power"
    .dexText "of science. It has been given artificial"
    .dexText "intelligence that enables it to learn new"
    .dexText "gestures and emotions on its own."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry370::
    .2byte 2, 3, 4, 0xA, 4, 0, 7, 0, 1, 5, 7, 0
    .dexName "STANTLER"
    .dexCategory "BIG HORN"
    .dexText "STANTLER`s magnificent antlers were once"
    .dexText "traded at high prices as works of art. As"
    .dexText "a result, this POKéMON was hunted close to"
    .dexText "extinction."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry371::
    .2byte 2, 3, 5, 0xA, 3, 1, 1, 0, 1, 2, 7, 9
    .dexName "SMEARGLE"
    .dexCategory "PAINTER"
    .dexText "A SMEARGLE marks its territory using a"
    .dexText "fluid that leaks out from the tip of its"
    .dexText "tail. About 5,000 different marks left by"
    .dexText "this POKéMON have been found."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry372::
    .2byte 2, 3, 6, 0xA, 2, 0, 4, 0, 0, 4, 6, 3
    .dexName "TYROGUE"
    .dexCategory "SCUFFLE"
    .dexText "TYROGUE become stressed out if they do not"
    .dexText "get to train every day. When raising this"
    .dexText "POKéMON, the TRAINER must establish a"
    .dexText "regular training schedule."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry373::
    .2byte 2, 3, 7, 0xA, 4, 0, 7, 0, 1, 0, 5, 8
    .dexName "HITMONTOP"
    .dexCategory "HANDSTAND"
    .dexText "Its technique of kicking while spinning is"
    .dexText "a remarkable mix of both offense and"
    .dexText "defense. HITMONTOP travel faster spinning"
    .dexText "than they do walking."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry374::
    .2byte 2, 3, 8, 0xA, 1, 0, 4, 0, 0, 1, 3, 2
    .dexName "SMOOCHUM"
    .dexCategory "KISS"
    .dexText "It actively runs about, but also falls"
    .dexText "often. Whenever it falls, it will check"
    .dexText "its reflection on a lake`s surface to make"
    .dexText "sure its face hasn`t become dirty."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry375::
    .2byte 2, 3, 9, 0xA, 2, 0, 0, 0, 0, 5, 1, 8
    .dexName "ELEKID"
    .dexCategory "ELECTRIC"
    .dexText "If it touches metal and discharges the"
    .dexText "electricity it has stored in its body, an"
    .dexText "ELEKID begins swinging its arms in circles"
    .dexText "to recharge itself."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry376::
    .2byte 2, 4, 0, 0xA, 2, 0, 4, 0, 0, 4, 7, 2
    .dexName "MAGBY"
    .dexCategory "LIVE COAL"
    .dexText "If a MAGBY is spouting yellow flames from"
    .dexText "its mouth, it is in good health. When it"
    .dexText "is fatigued, black smoke will be mixed in"
    .dexText "with the flames."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry377::
    .2byte 2, 4, 1, 0xA, 3, 1, 1, 0, 1, 6, 6, 4
    .dexName "MILTANK"
    .dexCategory "MILK COW"
    .dexText "It gives over five gallons of milk daily."
    .dexText "Its sweet milk is enjoyed by children and"
    .dexText "grown-ups alike. People who can`t drink"
    .dexText "milk turn it into yogurt and eat it"
    .dexText "instead."
    .dexText ""

    .align 2, 0
dexEntry378::
    .2byte 2, 4, 2, 0xA, 4, 1, 1, 0, 1, 0, 3, 2
    .dexName "BLISSEY"
    .dexCategory "HAPPINESS"
    .dexText "If it senses sadness with its fluffy fur,"
    .dexText "a BLISSEY will rush over to the sad"
    .dexText "person, however far away, to share an egg"
    .dexText "of happiness that brings a smile to any"
    .dexText "face."
    .dexText ""

    .align 2, 0
dexEntry379::
    .2byte 2, 4, 3, 0xA, 6, 0, 3, 0, 3, 9, 2, 4
    .dexName "RAIKOU"
    .dexCategory "THUNDER"
    .dexText "RAIKOU embodies the speed of lightning."
    .dexText "Its roars send shock waves shuddering"
    .dexText "through the air and ground as if lightning"
    .dexText "bolts were crashing down."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry380::
    .2byte 2, 4, 4, 0xA, 6, 1, 1, 0, 4, 3, 6, 5
    .dexName "ENTEI"
    .dexCategory "VOLCANO"
    .dexText "ENTEI embodies the passion of magma. It is"
    .dexText "thought to have been born in the eruption"
    .dexText "of a volcano. It blasts fire that consumes"
    .dexText "all that it touches."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry381::
    .2byte 2, 4, 5, 0xA, 6, 0, 7, 0, 4, 1, 2, 3
    .dexName "SUICUNE"
    .dexCategory "AURORA"
    .dexText "SUICUNE embodies the compassion of a pure"
    .dexText "spring of water. It runs across the land"
    .dexText "with gliding elegance. It has the power to"
    .dexText "purify dirty water."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry382::
    .2byte 2, 4, 6, 0xA, 2, 0, 0, 0, 1, 5, 8, 7
    .dexName "LARVITAR"
    .dexCategory "ROCK SKIN"
    .dexText "A LARVITAR is born deep under the ground."
    .dexText "It must eat its way through the soil above"
    .dexText "and reach the surface for it to see its"
    .dexText "parents` faces."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry383::
    .2byte 2, 4, 7, 0xA, 3, 1, 1, 0, 3, 3, 5, 1
    .dexName "PUPITAR"
    .dexCategory "HARD SHELL"
    .dexText "A PUPITAR creates a gas inside its body"
    .dexText "that it ejects under compression to propel"
    .dexText "itself like a jet. Its body can withstand"
    .dexText "a collision with solid steel."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry384::
    .2byte 2, 4, 8, 0xA, 6, 0, 7, 0, 4, 4, 5, 3
    .dexName "TYRANITAR"
    .dexCategory "ARMOR"
    .dexText "A TYRANITAR is so overwhelmingly powerful,"
    .dexText "it can bring down a whole mountain to make"
    .dexText "its nest. It roams in mountains seeking"
    .dexText "new opponents to fight."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry385::
    .2byte 2, 4, 9, 1, 7, 0, 1, 0, 4, 7, 6, 2
    .dexName "LUGIA"
    .dexCategory "DIVING"
    .dexText "LUGIA is so powerful even a light"
    .dexText "fluttering of its wings can blow apart"
    .dexText "houses. As a result, it chooses to live"
    .dexText "out of sight deep under the sea."
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry386::
    .2byte 2, 5, 0, 1, 2, 0, 6, 0, 4, 3, 8, 7
    .dexName "HO-OH"
    .dexCategory "RAINBOW"
    .dexText "Its feathers--which glow in seven colors"
    .dexText "depending on the angle at which they are"
    .dexText "struck by light--are thought to bring joy."
    .dexText "It is said to live at the foot of a"
    .dexText "rainbow."
    .dexText ""

    .align 2, 0
dexEntry387::
    .2byte 2, 5, 1, 0xA, 2, 0, 0, 0, 0, 1, 1, 0
    .dexName "CELEBI"
    .dexCategory "TIME TRAVEL"
    .dexText "When CELEBI disappears deep in a forest,"
    .dexText "it is said to leave behind an egg it"
    .dexText "brought from the future."
    .dexText ""
    .dexText ""
    .dexText ""

    .align 2, 0
dexEntry388::
    .2byte 5, 2, 3, 0xA, 0, 1, 6, 0xA, 7, 9, 5, 0
    .dexName "ZEBSTRIKA"
    .dexCategory "THUNDERBOLT"
    .dexText "ZEBSTRIKA runs like lightning"
    .dexText "across open grasslands."
    .dexText "Its mane crackles with electricity"
    .dexText "when it charges into battle."
    .dexText ""
    .dexText ""
