#ifndef GUARD_CONSTANTS_BONUS_BOARD_H
#define GUARD_CONSTANTS_BONUS_BOARD_H

enum BonusBoardSubstates{
    BONUS_BOARD_SUBSTATE_ACTIVE = 0,
    BONUS_BOARD_SUBSTATE_FADETRANSITION = 1,
    BONUS_BOARD_SUBSTATE_TRANSFER_TO_MAIN_BOARD = 2,
};

#endif // GUARD_CONSTANTS_BONUS_BOARD_H