#ifndef GUARD_CONSTANTS_BONUS_BOARD_H
#define GUARD_CONSTANTS_BONUS_BOARD_H

enum BonusBoardSubstates{
    BONUS_BOARD_SUBSTATE_0 = 0,
    BONUS_BOARD_SUBSTATE_1 = 1,
    BONUS_BOARD_SUBSTATE_2 = 2,
};

#endif // GUARD_CONSTANTS_BONUS_BOARD_H