#ifndef GUARD_CONSTANTS_KYOGRE_STATES_H
#define GUARD_CONSTANTS_KYOGRE_STATES_H
#include "bonus_board.h"

enum KyogreBoardState{
    KYOGRE_BOARD_STATE_INTRO = 0,
    KYOGRE_BOARD_STATE_BATTLE_PHASE = 1,
    KYOGRE_BOARD_STATE_SUCCESS_BANNER = 2,
    KYOGRE_BOARD_STATE_SUCCESS_SCORING = 3,
    KYOGRE_BOARD_STATE_CATCH_BANNER = 4,
    KYOGRE_BOARD_STATE_CATCH_SCORING = 5,
    KYOGRE_BOARD_STATE_SCORE_COUNTING_FINISHED = 6,
};

enum KyogreEntityState{
    KYOGRE_ENTITY_STATE_INIT = 0,
    KYOGRE_ENTITY_STATE_ENTRY = 1,
    KYOGRE_ENTITY_STATE_RETURN_TO_TOP = 2,
    KYOGRE_ENTITY_STATE_DIVE = 3,
    KYOGRE_ENTITY_STATE_IDLE = 4,
    KYOGRE_ENTITY_STATE_SPAWN_WHIRLPOOLS = 5,
    KYOGRE_ENTITY_STATE_SHOCKWAVE = 6,
    KYOGRE_ENTITY_STATE_SUFFICIENT_HITS = 7,
    KYOGRE_ENTITY_STATE_PRESUMED_UNREACHABLE = 8,
    KYOGRE_ENTITY_STATE_PREPARE_LEAVING = 9,
    KYOGRE_ENTITY_STATE_CAPTURE = 10,
    KYOGRE_ENTITY_STATE_UNDERWATER = 11,
    KYOGRE_ENTITY_STATE_LEAP = 12,
    KYOGRE_ENTITY_STATE_FINISHED = 13,
};

enum KyogreCollisionMode{
    KYOGRE_COLLISION_MODE_NONE = 0,
    KYOGRE_COLLISION_MODE_TOP_POSITION = 1,
    KYOGRE_COLLISION_MODE_EMERGING_FROM_WATER = 2,
    KYOGRE_COLLISION_MODE_JUMPING = 3,
};

enum KyogreFreezePhase{
    KYOGRE_FREEZE_PHASE_0 = 0,
    KYOGRE_FREEZE_PHASE_1 = 1,
    KYOGRE_FREEZE_PHASE_2 = 2,
    KYOGRE_FREEZE_PHASE_3 = 3,
    KYOGRE_FREEZE_PHASE_4 = 4,
    KYOGRE_FREEZE_PHASE_5 = 5,
    KYOGRE_FREEZE_PHASE_6 = 6,
    KYOGRE_FREEZE_PHASE_7 = 7,
};

enum KyogreWhirlpoolPhase{
    KYOGRE_WHIRLPOOL_PHASE_0 = 0,
    KYOGRE_WHIRLPOOL_PHASE_1 = 1,
    KYOGRE_WHIRLPOOL_PHASE_2 = 2,
    KYOGRE_WHIRLPOOL_PHASE_3 = 3,
    KYOGRE_WHIRLPOOL_PHASE_4 = 4,
    KYOGRE_WHIRLPOOL_PHASE_5 = 5,
};

#endif //GUARD_CONSTANTS_KYOGRE_STATES_H