#ifndef GUARD_CONSTANTS_KYOGRE_STATES_H
#define GUARD_CONSTANTS_KYOGRE_STATES_H
#include "bonus_board.h"

enum KyogreBoardState{
    KYOGRE_BOARD_STATE_INTRO = 0,
    KYOGRE_BOARD_STATE_BATTLE_PHASE = 1,
    KYOGRE_BOARD_STATE_SUCCESS_BANNER = 2,
    KYOGRE_BOARD_STATE_SUCCESS_SCORING = 3,
    KYOGRE_BOARD_STATE_CATCH_BANNER = 4,
    KYOGRE_BOARD_STATE_CATCH_SCORING = 5,
    KYOGRE_BOARD_STATE_SCORE_COUNTING_FINISHED = 6,
};

enum KyogreEntityState{
    KYOGRE_ENTITY_STATE_0 = 0,
    KYOGRE_ENTITY_STATE_1 = 1,
    KYOGRE_ENTITY_STATE_2 = 2,
    KYOGRE_ENTITY_STATE_3 = 3,
    KYOGRE_ENTITY_STATE_4 = 4,
    KYOGRE_ENTITY_STATE_5 = 5,
    KYOGRE_ENTITY_STATE_6 = 6,
    KYOGRE_ENTITY_STATE_7 = 7,
    KYOGRE_ENTITY_STATE_8 = 8,
    KYOGRE_ENTITY_STATE_9 = 9,
    KYOGRE_ENTITY_STATE_10 = 10,
    KYOGRE_ENTITY_STATE_11 = 11,
    KYOGRE_ENTITY_STATE_12 = 12,
    KYOGRE_ENTITY_STATE_13 = 13,
};

enum KyogreCollisionMode{
    KYOGRE_COLLISION_MODE_NONE = 0,
    KYOGRE_COLLISION_MODE_1 = 1,
    KYOGRE_COLLISION_MODE_2 = 2,
    KYOGRE_COLLISION_MODE_3 = 3,
};

enum KyogreFreezePhase{
    KYOGRE_FREEZE_PHASE_0 = 0,
    KYOGRE_FREEZE_PHASE_1 = 1,
    KYOGRE_FREEZE_PHASE_2 = 2,
    KYOGRE_FREEZE_PHASE_3 = 3,
    KYOGRE_FREEZE_PHASE_4 = 4,
    KYOGRE_FREEZE_PHASE_5 = 5,
    KYOGRE_FREEZE_PHASE_6 = 6,
    KYOGRE_FREEZE_PHASE_7 = 7,
};

enum KyogreWhirlpoolPhase{
    KYOGRE_WHIRLPOOL_PHASE_0 = 0,
    KYOGRE_WHIRLPOOL_PHASE_1 = 1,
    KYOGRE_WHIRLPOOL_PHASE_2 = 2,
    KYOGRE_WHIRLPOOL_PHASE_3 = 3,
    KYOGRE_WHIRLPOOL_PHASE_4 = 4,
    KYOGRE_WHIRLPOOL_PHASE_5 = 5,
};

#endif //GUARD_CONSTANTS_KYOGRE_STATES_H