#ifndef GUARD_CONSTANTS_MAIN_BOARD_H
#define GUARD_CONSTANTS_MAIN_BOARD_H

#include "center_screen_states.h"

enum MainBoardTrapHoles{
    NOT_TRAPPED = 0,
    TRAP_CATCH_HOLE = 1,
    TRAP_EGG_HOLE = 2,
    TRAP_EVO_SHOP_HOLE = 3,
    TRAP_CENTER_HOLE = 4,
};

enum MainBoardState{
    MAIN_BOARD_STATE_BOARD_INTRO = 0,
    MAIN_BOARD_STATE_DEFAULT = 1,
    MAIN_BOARD_STATE_BONUS_HOLE_ACTIVE = 2,
    MAIN_BOARD_STATE_BOSS_HOLE_ACTIVE = 3,

    MAIN_BOARD_STATE_ACTIVITY_BASE = 4,
    MAIN_BOARD_STATE_CATCH_EM_MODE = 4,
    MAIN_BOARD_STATE_EGG_HATCH_MODE = 5,
    MAIN_BOARD_STATE_EVO_MODE = 6,
    MAIN_BOARD_STATE_TRAVEL_MODE = 7,
    MAIN_BOARD_STATE_JIRACHI_CATCH_MODE = 8,
};

enum BoardIntroSubstates{
    BOARD_INTRO_SUBSTATE_INIT = 0,
    BOARD_INTRO_SUBSTATE_SETUP_GRAPHICS = 1,
    BOARD_INTRO_SUBSTATE_SCROLL = 2,
    BOARD_INTRO_SUBSTATE_START_AREA_SPINNER = 3,
    BOARD_INTRO_SUBSTATE_WAIT_FOR_LAUNCH = 4,
    BOARD_INTRO_SUBSTATE_AREA_SELECTION_STOPPING = 5,
    BOARD_INTRO_SUBSTATE_AREA_SELECTED_FX = 6,
};

enum DefaultModeSubstates{
    DEFAULT_MODE_SUBSTATE_INIT = 0,
};

enum BonusHoleSubstates{
    BONUS_HOLE_SUBSTATE_INIT = 0,
    BONUS_HOLE_SUBSTATE_OPEN_TRAP_DOOR = 1,
    BONUS_HOLE_SUBSTATE_GRAVITY_WELL = 2,
    BONUS_HOLE_SUBSTATE_START_ROULETTE = 3,
    BONUS_HOLE_SUBSTATE_RUN_ROULETTE = 4,
    BONUS_HOLE_SUBSTATE_START_CLOSING = 5,
    BONUS_HOLE_SUBSTATE_BOARD_STATE_CLEANUP = 6,
    BONUS_HOLE_SUBSTATE_RETURN_TO_DEFAULT_TIMER = 7,
};

enum BossHoleSubstates{
    BOSS_HOLE_SUBSTATE_INIT_DELAY = 0,
    BOSS_HOLE_SUBSTATE_OPEN_TRAP_DOOR = 1,
    BOSS_HOLE_SUBSTATE_GRAVITY_WELL = 2,
    BOSS_HOLE_SUBSTATE_DISPLAY_CONFIRMATION = 3,
    BOSS_HOLE_SUBSTATE_AWAIT_CONFIRMATION = 4,
    BOSS_HOLE_SUBSTATE_PREPARE_BONUS_TRANSFER = 5,
    BOSS_HOLE_SUBSTATE_CANCEL_BONUS = 6,
    BOSS_HOLE_SUBSTATE_BOARD_STATE_CLEANUP = 7,
    BOSS_HOLE_SUBSTATE_RETURN_TO_DEFAULT = 8,
};

enum CatchEmModeSubstates{
    CATCH_EM_SUBSTATE_BUILD_WEIGHTS = 0,
    CATCH_EM_SUBSTATE_SELECT_SPECIES = 1,
    CATCH_EM_SUBSTATE_LOAD_MON_GRAPHICS = 2,
    CATCH_EM_SUBSTATE_SETUP_TILE_OVERLAY = 3,
    CATCH_EM_SUBSTATE_START_MODE_BANNER = 4,
    CATCH_EM_SUBSTATE_AWAITING_BUMPER_HITS = 5,
    CATCH_EM_SUBSTATE_LOAD_MON_SPRITE = 6,
    CATCH_EM_SUBSTATE_ANIMATE_MON_APPEAR = 7,
    CATCH_EM_SUBSTATE_SETUP_CATCH_HIT_COUNT = 8,
    CATCH_EM_SUBSTATE_CATCH_HIT_PHASE = 9,
    CATCH_EM_SUBSTATE_END_CATCH_HIT_PHASE = 10,
    CATCH_EM_SUBSTATE_BOARD_STATE_CLEANUP = 11,
    CATCH_EM_SUBSTATE_BOARD_PREPARE_NEXT_MODE = 12,
};

enum EggHatchModeSubstates{
    EGG_HATCH_SUBSTATE_INIT = 0,
    EGG_HATCH_SUBSTATE_1 = 1,
    EGG_HATCH_SUBSTATE_2 = 2,
    EGG_HATCH_SUBSTATE_3 = 3,
    EGG_HATCH_SUBSTATE_4 = 4,
    EGG_HATCH_SUBSTATE_5 = 5,
    EGG_HATCH_SUBSTATE_6 = 6,
    EGG_HATCH_SUBSTATE_7 = 7,
    EGG_HATCH_SUBSTATE_8 = 8,
};

enum EvolutionModeSubstates{
    EVOLUTION_SUBSTATE_INIT = 0,
    EVOLUTION_SUBSTATE_1 = 1,
    EVOLUTION_SUBSTATE_2 = 2,
    EVOLUTION_SUBSTATE_3 = 3,
    EVOLUTION_SUBSTATE_4 = 4,
    EVOLUTION_SUBSTATE_5 = 5,
    EVOLUTION_SUBSTATE_6 = 6,
    EVOLUTION_SUBSTATE_7 = 7,
    EVOLUTION_SUBSTATE_8 = 8,
    EVOLUTION_SUBSTATE_9 = 9,
    EVOLUTION_SUBSTATE_10 = 10,
};

enum TravelModeSubstates{
    TRAVEL_SUBSTATE_INIT = 0,
    TRAVEL_SUBSTATE_1 = 1,
    TRAVEL_SUBSTATE_2 = 2,
    TRAVEL_SUBSTATE_3 = 3,
    TRAVEL_SUBSTATE_4 = 4,
    TRAVEL_SUBSTATE_5 = 5,
    TRAVEL_SUBSTATE_6 = 6,
    TRAVEL_SUBSTATE_7 = 7,
};

enum JirachiCatchSubstates{
    JIRACHI_CATCH_SUBSTATE_INIT = 0,
    JIRACHI_CATCH_SUBSTATE_1 = 1,
    JIRACHI_CATCH_SUBSTATE_2 = 2,
    JIRACHI_CATCH_SUBSTATE_3 = 3,
    JIRACHI_CATCH_SUBSTATE_4 = 4,
    JIRACHI_CATCH_SUBSTATE_5 = 5,
    JIRACHI_CATCH_SUBSTATE_6 = 6,
};

enum BoardStateDispatchStates{
    BOARD_STATE_DISPATCHER_STATE_INIT = 0,
    BOARD_STATE_DISPATCHER_STATE_RUNNING = 1,
    BOARD_STATE_DISPATCHER_STATE_CHANGING = 2,
};

#endif // GUARD_CONSTANTS_MAIN_BOARD_H