#ifndef GUARD_CONSTANTS_RAYQUAZA_STATES_H
#define GUARD_CONSTANTS_RAYQUAZA_STATES_H
#include "bonus_board.h"

enum RayquazaEntityState{
    RAYQUAZA_ENTITY_STATE_0 = 0,
    RAYQUAZA_ENTITY_STATE_1 = 1,
    RAYQUAZA_ENTITY_STATE_2 = 2,
    RAYQUAZA_ENTITY_STATE_3 = 3,
    RAYQUAZA_ENTITY_STATE_4 = 4,
    RAYQUAZA_ENTITY_STATE_5 = 5,
    RAYQUAZA_ENTITY_STATE_6 = 6,
    RAYQUAZA_ENTITY_STATE_7 = 7,
    RAYQUAZA_ENTITY_STATE_8 = 8,
    RAYQUAZA_ENTITY_STATE_9 = 9,
    RAYQUAZA_ENTITY_STATE_10 = 10,
    RAYQUAZA_ENTITY_STATE_11 = 11,
    RAYQUAZA_ENTITY_STATE_12 = 12,
    RAYQUAZA_ENTITY_STATE_13 = 13,
    RAYQUAZA_ENTITY_STATE_14 = 14,
    RAYQUAZA_ENTITY_STATE_15 = 15,
};

#endif //GUARD_CONSTANTS_RAYQUAZA_STATES_H