#ifndef GUARD_CONSTANTS_SAPPHIRE_STATES_H
#define GUARD_CONSTANTS_SAPPHIRE_STATES_H
#include "main_board.h"

enum SapphireCollisionTrigger{
    SAPPHIRE_TRIGGER_MODE_START_BALL_LOCK = 1,
    SAPPHIRE_TRIGGER_CHANGE_LAYER_UP = 2,
    SAPPHIRE_TRIGGER_CHANGE_LAYER_DOWN = 3,
    SAPPHIRE_TRIGGER_TARGET_SWITCH = 4,
    SAPPHIRE_TRIGGER_BALL_LAUNCH_POSITION = 5,
    SAPPHIRE_TRIGGER_6 = 6,
    SAPPHIRE_TRIGGER_SHOCK_WALL = 7,
    SAPPHIRE_TRIGGER_UPPER_LANE_ROLLOVER = 8,
    SAPPHIRE_TRIGGER_LOWER_LANE_ROLLOVER = 9,
    SAPPHIRE_TRIGGER_HOLE_ROLLOVER = 10,
    SAPPHIRE_TRIGGER_PIKA_KICKBACK_ROLLOVER_TRIGGER = 11,
    SAPPHIRE_TRIGGER_PIKA_CHARGE_SPINNER = 12,
    SAPPHIRE_TRIGGER_HATCH_MACHINE_ALTERNATING_TRIGGER_TYPE_A = 13,
    SAPPHIRE_TRIGGER_HATCH_MACHINE_ALTERNATING_TRIGGER_TYPE_B = 14,
    SAPPHIRE_TRIGGER_PELIPPER_ENTITY_TRIGGER = 15,
};

enum SapphireCollisionZone{
    SAPPHIRE_ZONE_LAUNCH_CHUTE = 0,
    SAPPHIRE_ZONE_COIN_LANE_TOP = 1,
    SAPPHIRE_ZONE_EVO_LANE_TOP = 2,
    SAPPHIRE_ZONE_LEFT_BALL_UPGRADE_LANE = 3,
    SAPPHIRE_ZONE_CENTER_BALL_UPGRADE_LANE = 4,
    SAPPHIRE_ZONE_RIGHT_BALL_UPGRADE_LANE = 5,
    SAPPHIRE_ZONE_GET_LANE_TOP = 6,
    SAPPHIRE_ZONE_COIN_LANE_BOTTOM = 7,
    SAPPHIRE_ZONE_EVO_LANE_BOTTOM = 8,
    SAPPHIRE_ZONE_GET_LANE_BOTTOM = 9,
    SAPPHIRE_ZONE_H_OUTLANE = 10,
    SAPPHIRE_ZONE_O_INLANE = 11,
    SAPPHIRE_ZONE_L_INLANE = 12,
    SAPPHIRE_ZONE_E_OUTLANE = 13,
    SAPPHIRE_ZONE_HATCH_ALTERNATER_A = 14,
    SAPPHIRE_ZONE_HATCH_ALTERNATER_B = 15,
};

enum SeedotState{
    SEEDOT_STATE_OFF_BOARD = 0,
    SEEDOT_STATE_DROPPING_IN = 1,
    SEEDOT_STATE_WAITING = 2,
    SEEDOT_STATE_LEAVING = 3
};

enum ZigzagoonState{
    ZIGZAGOON_STATE_SITTING = 0,
    ZIGZAGOON_STATE_PRIMED = 1,
    ZIGZAGOON_STATE_SIGNALED = 2,
    ZIGZAGOON_STATE_LEAPING = 3,
    ZIGZAGOON_STATE_RETURN_TO_NORMAL = 4
};

enum PelipperStates{
    PELIPPER_STATE_NORMAL = 0,
    PELIPPER_STATE_WATCHING_RAMP = 1,
    PELIPPER_STATE_OPENED_MOUTH = 2,
    PELIPPER_STATE_CLOSING_MOUTH = 3,
    PELIPPER_STATE_TAKEOFF = 4,
    PELIPPER_STATE_FLY_OFF_BOARD = 5,
    PELIPPER_STATE_WARP_TO_SPHEAL_BOARD = 6,
    PELIPPER_STATE_SET_SWOOP_FROM_TOP_LEFT = 7,
    PELIPPER_STATE_SWOOP = 8,
    PELIPPER_STATE_FLY_IN_FROM_RIGHT = 9,
    PELIPPER_STATE_RETURN_TO_NORMAL = 10
};

#endif //GUARD_CONSTANTS_SAPPHIRE_STATES_H